"""One-shot builder for data/phase_academic_bank.json — run then delete if desired."""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "phase_academic_bank.json"

bank: list[dict] = []


def add(
    sid: str,
    subject: str,
    shs: str,
    style: str,
    diff: int,
    q: str,
    opts: dict,
    ans: str,
    exp: str,
) -> None:
    bank.append(
        {
            "id": sid,
            "subject": subject,
            "shs_level": shs,
            "exam_style": style,
            "difficulty": diff,
            "question_text": q,
            "options": opts,
            "correct_answer": ans,
            "explanation": exp,
        }
    )


def bulk(prefix: str, subject: str, shs: str, rows: list) -> None:
    for i, (q, o, a, e, d) in enumerate(rows, 1):
        add(f"{prefix}-{i:03d}", subject, shs, "classroom", d, q, o, a, e)


# ── English ──────────────────────────────────────────────────────────────────
bulk(
    "eng-shs1",
    "english",
    "SHS 1",
    [
        (
            'Which word is a noun in: "The students studied hard for the test"?',
            {"A": "studied", "B": "hard", "C": "students", "D": "for"},
            "C",
            '"Students" names people and is a noun.',
            2,
        ),
        (
            "Choose the correct article: ___ apple a day keeps the doctor away.",
            {"A": "A", "B": "An", "C": "The", "D": "No article"},
            "B",
            '"Apple" begins with a vowel sound, so use "an".',
            1,
        ),
        (
            'Identify the adjective: "She wore a bright yellow dress."',
            {"A": "wore", "B": "bright", "C": "dress", "D": "She"},
            "B",
            '"Bright" describes the dress.',
            2,
        ),
        (
            "Which sentence is correctly punctuated?",
            {
                "A": "Where are you going.",
                "B": "Where are you going?",
                "C": "Where are you going!",
                "D": "where are you going",
            },
            "B",
            "Questions end with a question mark.",
            1,
        ),
        (
            'The opposite of "brave" is',
            {"A": "bold", "B": "cowardly", "C": "strong", "D": "clever"},
            "B",
            '"Cowardly" is an antonym of "brave".',
            2,
        ),
        (
            'Choose the correct past tense of "go".',
            {"A": "goed", "B": "gone", "C": "went", "D": "going"},
            "C",
            'The simple past of "go" is "went".',
            1,
        ),
        (
            "In poetry, a group of lines is often called a",
            {"A": "paragraph", "B": "stanza", "C": "chapter", "D": "verse only"},
            "B",
            "A stanza is a grouped set of lines in a poem.",
            3,
        ),
        (
            'Which is a synonym of "happy"?',
            {"A": "sad", "B": "angry", "C": "joyful", "D": "tired"},
            "C",
            '"Joyful" means the same as happy.',
            1,
        ),
        (
            'Subject–verb agreement: "The boy ___ to school every day."',
            {"A": "go", "B": "goes", "C": "going", "D": "gone"},
            "B",
            'Singular subject "boy" takes "goes".',
            2,
        ),
        (
            "A letter written to a friend is called a ___ letter.",
            {"A": "formal", "B": "business", "C": "informal", "D": "official"},
            "C",
            "Letters to friends are informal.",
            2,
        ),
        (
            "Which word is spelled correctly?",
            {"A": "recieve", "B": "receive", "C": "receeve", "D": "receve"},
            "B",
            "i before e except after c → receive.",
            3,
        ),
        (
            "The main idea of a passage is also called the",
            {"A": "title only", "B": "central theme", "C": "footnote", "D": "index"},
            "B",
            "The central theme is the main idea.",
            3,
        ),
    ],
)

bulk(
    "eng-shs2",
    "english",
    "SHS 2",
    [
        (
            'Identify the figure of speech: "The classroom was a zoo."',
            {"A": "simile", "B": "metaphor", "C": "alliteration", "D": "irony"},
            "B",
            'A metaphor compares without "like" or "as".',
            5,
        ),
        (
            "Which is a complex sentence?",
            {
                "A": "I ran.",
                "B": "I ran and jumped.",
                "C": "I ran because I was late.",
                "D": "Run!",
            },
            "C",
            "A complex sentence has a dependent clause.",
            5,
        ),
        (
            'Choose the correct relative pronoun: "The girl ___ won the prize is my sister."',
            {"A": "which", "B": "who", "C": "whom", "D": "whose"},
            "B",
            '"Who" refers to people as subject.',
            4,
        ),
        (
            "In an argumentative essay, the writer mainly aims to",
            {
                "A": "tell a story",
                "B": "persuade the reader",
                "C": "describe a place",
                "D": "define a word",
            },
            "B",
            "Argumentative writing seeks to persuade.",
            5,
        ),
        (
            '"Break a leg" means',
            {"A": "injure yourself", "B": "good luck", "C": "run away", "D": "be careful"},
            "B",
            "It is an idiom wishing good luck.",
            4,
        ),
        (
            'Active to passive: "The teacher marked the scripts."',
            {
                "A": "The scripts marked the teacher.",
                "B": "The scripts were marked by the teacher.",
                "C": "The scripts are marking.",
                "D": "Marked the scripts the teacher.",
            },
            "B",
            'Object becomes subject; verb uses "were marked".',
            6,
        ),
        (
            "A summary should mainly",
            {
                "A": "copy every sentence",
                "B": "restate key points briefly",
                "C": "add new opinions",
                "D": "ignore the main idea",
            },
            "B",
            "Summaries condense main points.",
            5,
        ),
        (
            "Which word is an adverb?",
            {"A": "quick", "B": "quickly", "C": "quickness", "D": "quicken"},
            "B",
            '"Quickly" modifies a verb.',
            4,
        ),
        (
            "Cohesion in writing is improved by using",
            {
                "A": "random words",
                "B": "connectives like however and therefore",
                "C": "only short sentences",
                "D": "no paragraphs",
            },
            "B",
            "Connectives link ideas smoothly.",
            6,
        ),
        (
            "The register of a school report is usually",
            {"A": "slang", "B": "formal", "C": "text-message style", "D": "poetic"},
            "B",
            "Official school writing is formal.",
            5,
        ),
        (
            'Choose the correctly reported speech: He said, "I am tired."',
            {
                "A": "He said he is tired.",
                "B": "He said he was tired.",
                "C": "He said I am tired.",
                "D": "He said he will be tired.",
            },
            "B",
            "Present becomes past in reported speech.",
            6,
        ),
        (
            "Alliteration is the repetition of",
            {
                "A": "vowel sounds only in rhymes",
                "B": "initial consonant sounds",
                "C": "whole sentences",
                "D": "punctuation marks",
            },
            "B",
            "Alliteration repeats starting consonant sounds.",
            5,
        ),
    ],
)

bulk(
    "eng-shs3",
    "english",
    "SHS 3",
    [
        (
            "In literary appreciation, tone refers to the",
            {
                "A": "length of the text",
                "B": "writer's attitude toward the subject",
                "C": "number of characters",
                "D": "publisher's name",
            },
            "B",
            "Tone is the writer's attitude.",
            8,
        ),
        (
            "A thesis statement in an essay should be",
            {
                "A": "vague and long",
                "B": "clear and arguable",
                "C": "a question only",
                "D": "a quotation only",
            },
            "B",
            "A thesis states a clear claim.",
            8,
        ),
        (
            'Which device is used in "The wind whispered secrets"?',
            {"A": "hyperbole", "B": "personification", "C": "oxymoron", "D": "pun"},
            "B",
            "Wind is given human action.",
            7,
        ),
        (
            "In comprehension, inference means",
            {
                "A": "copying the text",
                "B": "drawing a conclusion from clues",
                "C": "ignoring context",
                "D": "memorising dates",
            },
            "B",
            "Inference uses evidence to conclude.",
            8,
        ),
        (
            "A rhetorical question is asked to",
            {
                "A": "get a factual answer",
                "B": "create effect, not expect an answer",
                "C": "test grammar",
                "D": "start a list",
            },
            "B",
            "Rhetorical questions emphasise a point.",
            7,
        ),
        (
            'Choose the most formal synonym of "kids".',
            {"A": "guys", "B": "children", "C": "buddies", "D": "mates"},
            "B",
            '"Children" is more formal.',
            7,
        ),
        (
            "Irony occurs when",
            {
                "A": "something happens as expected",
                "B": "outcome contradicts expectation",
                "C": "words rhyme",
                "D": "a story ends happily",
            },
            "B",
            "Irony involves contrast with expectation.",
            9,
        ),
        (
            "In summary writing, irrelevant details should be",
            {"A": "emphasised", "B": "omitted", "C": "quoted in full", "D": "repeated"},
            "B",
            "Summaries drop non-essential detail.",
            8,
        ),
        (
            "A topic sentence usually",
            {
                "A": "ends every paragraph only",
                "B": "states the paragraph's main idea",
                "C": "lists references",
                "D": "is always a question",
            },
            "B",
            "It introduces the main idea of a paragraph.",
            7,
        ),
        (
            "Ambiguity in language means a word or sentence has",
            {
                "A": "no meaning",
                "B": "more than one possible meaning",
                "C": "only one dialect form",
                "D": "incorrect spelling",
            },
            "B",
            "Ambiguous language can be read in multiple ways.",
            9,
        ),
        (
            "Which is the best concluding strategy for an essay?",
            {
                "A": "Introduce a brand-new argument",
                "B": "Restate the thesis and synthesise points",
                "C": "Ask the examiner's name",
                "D": "Copy the introduction word for word",
            },
            "B",
            "Conclusions synthesise without new claims.",
            9,
        ),
        (
            "Register shift means changing language according to",
            {
                "A": "font size",
                "B": "audience and situation",
                "C": "paper colour",
                "D": "exam time only",
            },
            "B",
            "Register matches audience and context.",
            8,
        ),
    ],
)

# ── Core Maths ───────────────────────────────────────────────────────────────
bulk(
    "math-shs1",
    "core_maths",
    "SHS 1",
    [
        ("What is 15% of 200?", {"A": "20", "B": "25", "C": "30", "D": "35"}, "C", "0.15 × 200 = 30.", 2),
        ("Simplify: 3x + 5x", {"A": "8x", "B": "15x", "C": "2x", "D": "8"}, "A", "Like terms: 3x+5x=8x.", 1),
        ("The HCF of 12 and 18 is", {"A": "2", "B": "3", "C": "6", "D": "36"}, "C", "Highest common factor is 6.", 2),
        ("Convert 3/4 to a decimal.", {"A": "0.25", "B": "0.5", "C": "0.75", "D": "1.25"}, "C", "3÷4=0.75.", 1),
        (
            "If a triangle has angles 40° and 60°, the third angle is",
            {"A": "80°", "B": "90°", "C": "100°", "D": "70°"},
            "A",
            "Angles in a triangle sum to 180°.",
            3,
        ),
        ("Evaluate: 2³", {"A": "6", "B": "8", "C": "9", "D": "5"}, "B", "2×2×2=8.", 1),
        (
            "The perimeter of a square of side 5 cm is",
            {"A": "10 cm", "B": "20 cm", "C": "25 cm", "D": "15 cm"},
            "B",
            "4×5=20 cm.",
            2,
        ),
        ("Solve: x + 7 = 15", {"A": "x=7", "B": "x=8", "C": "x=22", "D": "x=1"}, "B", "x=15-7=8.", 2),
        ("Which is a prime number?", {"A": "9", "B": "15", "C": "17", "D": "21"}, "C", "17 has only factors 1 and 17.", 3),
        (
            "0.2 as a fraction in lowest terms is",
            {"A": "1/2", "B": "1/5", "C": "2/5", "D": "1/10"},
            "B",
            "0.2=2/10=1/5.",
            3,
        ),
        (
            "Area of a rectangle 8 cm by 3 cm is",
            {"A": "11 cm²", "B": "24 cm²", "C": "22 cm²", "D": "5 cm²"},
            "B",
            "8×3=24.",
            2,
        ),
        (
            "Round 3.678 to 2 decimal places.",
            {"A": "3.67", "B": "3.68", "C": "3.70", "D": "3.6"},
            "B",
            "Third decimal is 8, so round up.",
            3,
        ),
    ],
)

bulk(
    "math-shs2",
    "core_maths",
    "SHS 2",
    [
        ("Solve: 2x − 5 = 11", {"A": "x=3", "B": "x=8", "C": "x=16", "D": "x=6"}, "B", "2x=16 → x=8.", 5),
        (
            "The gradient of the line through (0,2) and (4,10) is",
            {"A": "1", "B": "2", "C": "3", "D": "4"},
            "B",
            "(10-2)/(4-0)=2.",
            5,
        ),
        (
            "Factorise: x² − 9",
            {"A": "(x−3)(x+3)", "B": "(x−9)(x+1)", "C": "(x−3)²", "D": "x(x−9)"},
            "A",
            "Difference of squares.",
            6,
        ),
        ("sin 30° equals", {"A": "1", "B": "1/2", "C": "√3/2", "D": "0"}, "B", "Standard value sin 30°=1/2.", 5),
        (
            "If probability of rain is 0.3, probability it does not rain is",
            {"A": "0.3", "B": "0.7", "C": "1.3", "D": "0"},
            "B",
            "Complement: 1−0.3=0.7.",
            4,
        ),
        (
            "Expand: (x+2)(x+3)",
            {"A": "x²+5x+6", "B": "x²+6x+5", "C": "x²+x+6", "D": "2x+5"},
            "A",
            "x²+3x+2x+6=x²+5x+6.",
            5,
        ),
        ("Mean of 4, 6, 8, 10 is", {"A": "6", "B": "7", "C": "8", "D": "28"}, "B", "(4+6+8+10)/4=7.", 4),
        (
            "Solve simultaneously: x+y=5, x−y=1. What is x?",
            {"A": "2", "B": "3", "C": "4", "D": "1"},
            "B",
            "Add: 2x=6 → x=3.",
            6,
        ),
        (
            "Convert 45° to radians (in terms of π).",
            {"A": "π/2", "B": "π/3", "C": "π/4", "D": "π/6"},
            "C",
            "45°=π/4 radians.",
            7,
        ),
        ("The LCM of 8 and 12 is", {"A": "4", "B": "24", "C": "96", "D": "16"}, "B", "LCM(8,12)=24.", 4),
        (
            "If y ∝ x and y=10 when x=2, y when x=5 is",
            {"A": "15", "B": "20", "C": "25", "D": "50"},
            "C",
            "k=5; y=5×5=25.",
            6,
        ),
        (
            "Simplify: (a²b³)/(ab)",
            {"A": "ab²", "B": "a³b⁴", "C": "a/b", "D": "b/a"},
            "A",
            "a^(2-1) b^(3-1) → ab².",
            5,
        ),
    ],
)

bulk(
    "math-shs3",
    "core_maths",
    "SHS 3",
    [
        (
            "If log₁₀ 2 ≈ 0.3010, log₁₀ 8 is approximately",
            {"A": "0.3010", "B": "0.6020", "C": "0.9030", "D": "1.2040"},
            "C",
            "log 8 = log(2³)=3 log 2 ≈ 0.9030.",
            9,
        ),
        (
            "The quadratic formula for ax²+bx+c=0 is",
            {
                "A": "x=(-b±√(b²−4ac))/(2a)",
                "B": "x=b±√(b²−4ac)",
                "C": "x=(-b)/(2a)",
                "D": "x=√(b²−4ac)",
            },
            "A",
            "Standard quadratic formula.",
            8,
        ),
        ("Differentiate: y = 3x²", {"A": "6x", "B": "3x", "C": "x²", "D": "6"}, "A", "d/dx(3x²)=6x.", 9),
        (
            "In a right triangle, if opposite=3 and hypotenuse=5, sin θ =",
            {"A": "3/5", "B": "4/5", "C": "3/4", "D": "5/3"},
            "A",
            "sin=opposite/hypotenuse.",
            8,
        ),
        (
            "The sum of an AP with first term a, common difference d, n terms is",
            {"A": "n/2[2a+(n−1)d]", "B": "n(a+d)", "C": "a+(n−1)d", "D": "n²d"},
            "A",
            "Standard AP sum formula.",
            9,
        ),
        (
            "If P(A)=0.4 and P(B)=0.5 and A,B independent, P(A∩B)=",
            {"A": "0.9", "B": "0.2", "C": "0.1", "D": "0.4"},
            "B",
            "Independent: product 0.4×0.5=0.2.",
            8,
        ),
        (
            "Solve: x² − 5x + 6 = 0",
            {"A": "x=2 or 3", "B": "x=1 or 6", "C": "x=−2 or −3", "D": "x=5 or 6"},
            "A",
            "(x−2)(x−3)=0.",
            8,
        ),
        (
            "The volume of a cylinder is",
            {"A": "πr²h", "B": "2πr", "C": "πrh", "D": "4/3πr³"},
            "A",
            "V=πr²h.",
            7,
        ),
        (
            "If matrix A = [[1,2],[3,4]], det(A) =",
            {"A": "−2", "B": "2", "C": "10", "D": "−10"},
            "A",
            "1×4−2×3=−2.",
            10,
        ),
        ("∫ 2x dx =", {"A": "x² + C", "B": "2x² + C", "C": "x + C", "D": "2 + C"}, "A", "Antiderivative of 2x is x²+C.", 10),
        (
            "Standard deviation measures",
            {"A": "central value only", "B": "spread of data", "C": "mode only", "D": "sample size"},
            "B",
            "SD quantifies dispersion.",
            8,
        ),
        ("If 2ˣ = 16, then x =", {"A": "2", "B": "3", "C": "4", "D": "8"}, "C", "16=2⁴ so x=4.", 7),
    ],
)

# ── Integrated Science ───────────────────────────────────────────────────────
bulk(
    "sci-shs1",
    "integrated_science",
    "SHS 1",
    [
        (
            "Which organ pumps blood around the body?",
            {"A": "Liver", "B": "Heart", "C": "Lung", "D": "Kidney"},
            "B",
            "The heart pumps blood.",
            1,
        ),
        (
            "Water boils at ___ at standard pressure.",
            {"A": "0°C", "B": "50°C", "C": "100°C", "D": "212°C only in C"},
            "C",
            "Boiling point of water is 100°C.",
            1,
        ),
        (
            "Photosynthesis mainly occurs in the",
            {"A": "roots", "B": "leaves", "C": "flowers", "D": "seeds"},
            "B",
            "Leaves contain chloroplasts for photosynthesis.",
            2,
        ),
        (
            "Which is a renewable energy source?",
            {"A": "Coal", "B": "Petrol", "C": "Solar", "D": "Diesel"},
            "C",
            "Solar energy is renewable.",
            2,
        ),
        (
            "The SI unit of force is the",
            {"A": "joule", "B": "watt", "C": "newton", "D": "pascal"},
            "C",
            "Force is measured in newtons.",
            3,
        ),
        (
            "An acid turns blue litmus",
            {"A": "blue", "B": "red", "C": "green", "D": "unchanged"},
            "B",
            "Acids turn blue litmus red.",
            2,
        ),
        (
            "Which blood cells help fight infection?",
            {"A": "Red blood cells", "B": "White blood cells", "C": "Platelets", "D": "Plasma only"},
            "B",
            "White cells defend against pathogens.",
            3,
        ),
        (
            "The process of changing liquid to gas is",
            {"A": "condensation", "B": "evaporation", "C": "freezing", "D": "melting"},
            "B",
            "Evaporation is liquid → gas.",
            2,
        ),
        (
            "Which planet is closest to the Sun?",
            {"A": "Earth", "B": "Venus", "C": "Mercury", "D": "Mars"},
            "C",
            "Mercury is nearest the Sun.",
            2,
        ),
        (
            "Bones are joined at",
            {"A": "muscles", "B": "joints", "C": "tendons only", "D": "skin"},
            "B",
            "Joints connect bones.",
            1,
        ),
        (
            "A food chain always starts with a",
            {"A": "consumer", "B": "producer", "C": "decomposer", "D": "predator"},
            "B",
            "Producers (plants) start food chains.",
            3,
        ),
        (
            "Which gas do humans inhale for respiration?",
            {"A": "Carbon dioxide", "B": "Oxygen", "C": "Nitrogen only", "D": "Hydrogen"},
            "B",
            "Oxygen is used in respiration.",
            1,
        ),
    ],
)

bulk(
    "sci-shs2",
    "integrated_science",
    "SHS 2",
    [
        ("Ohm's law states that V =", {"A": "IR", "B": "I/R", "C": "R/I", "D": "I+R"}, "A", "V=IR.", 5),
        (
            "The chemical symbol for sodium is",
            {"A": "S", "B": "So", "C": "Na", "D": "Sd"},
            "C",
            "Sodium is Na.",
            4,
        ),
        (
            "Mitosis produces cells that are",
            {"A": "genetically identical", "B": "always gametes", "C": "haploid only", "D": "dead"},
            "A",
            "Mitosis yields identical diploid cells.",
            6,
        ),
        (
            "A catalyst",
            {
                "A": "is used up in a reaction",
                "B": "speeds up a reaction without being consumed",
                "C": "always slows reactions",
                "D": "changes the products only",
            },
            "B",
            "Catalysts lower activation energy and remain.",
            5,
        ),
        (
            "Sound cannot travel through",
            {"A": "air", "B": "water", "C": "steel", "D": "vacuum"},
            "D",
            "Sound needs a medium.",
            4,
        ),
        ("The pH of a neutral solution is", {"A": "0", "B": "7", "C": "14", "D": "1"}, "B", "Neutral pH is 7.", 4),
        (
            "Which organelle is the powerhouse of the cell?",
            {"A": "Nucleus", "B": "Mitochondrion", "C": "Ribosome", "D": "Vacuole"},
            "B",
            "Mitochondria produce ATP.",
            5,
        ),
        (
            "Reflection of light on a plane mirror: angle of incidence equals",
            {"A": "90° always", "B": "angle of reflection", "C": "0°", "D": "twice the refraction"},
            "B",
            "i = r for reflection.",
            5,
        ),
        (
            "An alloy is",
            {"A": "a pure element", "B": "a mixture of metals", "C": "only a gas", "D": "a type of plastic"},
            "B",
            "Alloys are metal mixtures.",
            5,
        ),
        (
            "Ecology studies",
            {
                "A": "only stars",
                "B": "interactions among organisms and environment",
                "C": "computer networks",
                "D": "grammar",
            },
            "B",
            "Ecology is about organism–environment relations.",
            4,
        ),
        (
            "Acceleration is change of",
            {"A": "distance only", "B": "velocity with time", "C": "mass", "D": "temperature"},
            "B",
            "a = Δv/Δt.",
            6,
        ),
        (
            "Which deficiency disease is linked to lack of vitamin C?",
            {"A": "Scurvy", "B": "Rickets", "C": "Beriberi", "D": "Night blindness"},
            "A",
            "Scurvy is vitamin C deficiency.",
            5,
        ),
    ],
)

bulk(
    "sci-shs3",
    "integrated_science",
    "SHS 3",
    [
        (
            "In genetics, a genotype is",
            {"A": "physical appearance only", "B": "genetic makeup", "C": "environment", "D": "diet"},
            "B",
            "Genotype is the allele combination.",
            8,
        ),
        (
            "The mole is a unit of",
            {"A": "mass only", "B": "amount of substance", "C": "temperature", "D": "pressure"},
            "B",
            "One mole is 6.02×10²³ entities.",
            8,
        ),
        (
            "Newton's second law can be written as",
            {"A": "F=ma", "B": "F=mv", "C": "F=m/a", "D": "F=a/m"},
            "A",
            "Force equals mass times acceleration.",
            7,
        ),
        (
            "Electrolysis of acidified water produces",
            {"A": "only oxygen", "B": "hydrogen and oxygen", "C": "only nitrogen", "D": "carbon dioxide only"},
            "B",
            "Water yields H₂ and O₂.",
            9,
        ),
        (
            "Homeostasis means",
            {
                "A": "constant internal conditions",
                "B": "rapid growth only",
                "C": "cell division only",
                "D": "extinction",
            },
            "A",
            "Maintaining stable internal environment.",
            8,
        ),
        (
            "A series circuit has",
            {"A": "one path for current", "B": "many independent paths", "C": "no current", "D": "only capacitors"},
            "A",
            "Series = single current path.",
            7,
        ),
        (
            "The greenhouse effect is mainly caused by gases that",
            {
                "A": "reflect all sunlight to space",
                "B": "trap heat in the atmosphere",
                "C": "create oxygen",
                "D": "cool the oceans instantly",
            },
            "B",
            "Greenhouse gases retain infrared heat.",
            8,
        ),
        (
            "DNA carries",
            {"A": "energy only", "B": "genetic information", "C": "oxygen in blood", "D": "hormones only"},
            "B",
            "DNA stores genetic information.",
            8,
        ),
        (
            "Latent heat is energy absorbed or released during",
            {
                "A": "temperature change only",
                "B": "change of state at constant temperature",
                "C": "nuclear fission only",
                "D": "sound production",
            },
            "B",
            "Latent heat accompanies phase change.",
            9,
        ),
        (
            "Which particle has a negative charge?",
            {"A": "Proton", "B": "Neutron", "C": "Electron", "D": "Nucleus"},
            "C",
            "Electrons are negative.",
            7,
        ),
        (
            "Antibiotics are mainly effective against",
            {"A": "viruses only", "B": "bacteria", "C": "all diseases", "D": "nutrient deficiency"},
            "B",
            "Antibiotics target bacteria.",
            8,
        ),
        (
            "Sustainable development aims to",
            {
                "A": "use resources without regard for future",
                "B": "meet present needs without harming future generations",
                "C": "stop all industry",
                "D": "increase pollution",
            },
            "B",
            "Classic sustainability definition.",
            9,
        ),
    ],
)

# ── Social Studies ───────────────────────────────────────────────────────────
bulk(
    "soc-shs1",
    "social_studies",
    "SHS 1",
    [
        (
            "Ghana gained independence in",
            {"A": "1957", "B": "1960", "C": "1945", "D": "1979"},
            "A",
            "Independence Day is 6 March 1957.",
            2,
        ),
        (
            "The capital city of Ghana is",
            {"A": "Kumasi", "B": "Accra", "C": "Tamale", "D": "Cape Coast"},
            "B",
            "Accra is the capital.",
            1,
        ),
        (
            "A nuclear family usually consists of",
            {
                "A": "parents and their children",
                "B": "only grandparents",
                "C": "the whole clan",
                "D": "neighbours only",
            },
            "A",
            "Nuclear family = parents + children.",
            2,
        ),
        (
            "Which is a civic responsibility?",
            {
                "A": "Paying taxes",
                "B": "Ignoring laws",
                "C": "Refusing to vote always",
                "D": "Damaging public property",
            },
            "A",
            "Paying taxes is a civic duty.",
            2,
        ),
        (
            "The longest river in Ghana is the",
            {"A": "Pra", "B": "Volta", "C": "Ankobra", "D": "Tano"},
            "B",
            "The Volta is Ghana's longest river.",
            3,
        ),
        (
            "Culture includes",
            {
                "A": "only food",
                "B": "shared values, customs and way of life",
                "C": "only music",
                "D": "weather only",
            },
            "B",
            "Culture is a people's way of life.",
            2,
        ),
        (
            "Which body makes laws in Ghana?",
            {"A": "Parliament", "B": "Police only", "C": "Traditional councils alone", "D": "Schools"},
            "A",
            "Parliament is the legislature.",
            3,
        ),
        (
            "A map's key or legend helps you",
            {
                "A": "fold the map",
                "B": "interpret symbols",
                "C": "measure rainfall",
                "D": "count population directly",
            },
            "B",
            "The legend explains map symbols.",
            2,
        ),
        (
            "Environmental sanitation means",
            {
                "A": "keeping surroundings clean and healthy",
                "B": "planting only cash crops",
                "C": "building more roads only",
                "D": "ignoring waste",
            },
            "A",
            "Sanitation is about clean, healthy surroundings.",
            2,
        ),
        (
            "The currency of Ghana is the",
            {"A": "Naira", "B": "Cedi", "C": "Dollar", "D": "Pound"},
            "B",
            "Ghana uses the cedi.",
            1,
        ),
        (
            "Peer pressure can be",
            {
                "A": "only negative",
                "B": "positive or negative",
                "C": "always illegal",
                "D": "unrelated to friends",
            },
            "B",
            "Peers can influence for good or bad.",
            3,
        ),
        (
            "Which is a natural resource of Ghana?",
            {"A": "Software licenses", "B": "Gold", "C": "Imported cars only", "D": "Foreign films"},
            "B",
            "Gold is a major natural resource.",
            2,
        ),
    ],
)

bulk(
    "soc-shs2",
    "social_studies",
    "SHS 2",
    [
        (
            "The 1992 Constitution of Ghana establishes",
            {"A": "military rule", "B": "a democratic republic", "C": "a monarchy only", "D": "no rights"},
            "B",
            "Ghana is a constitutional democracy.",
            5,
        ),
        (
            "Population density is",
            {"A": "total births only", "B": "people per unit area", "C": "number of cities", "D": "average age"},
            "B",
            "Density = population ÷ area.",
            4,
        ),
        (
            "Which is a cause of rural–urban migration?",
            {
                "A": "Search for jobs and better services",
                "B": "More farmland in cities",
                "C": "Cooler weather only",
                "D": "No schools in cities",
            },
            "A",
            "People move for employment and amenities.",
            5,
        ),
        (
            "Human rights include the right to",
            {"A": "break any law", "B": "life and dignity", "C": "harm others", "D": "ignore taxes always"},
            "B",
            "Fundamental rights include life and dignity.",
            4,
        ),
        (
            "A referendum is used to",
            {
                "A": "elect class prefects only",
                "B": "decide major national issues by popular vote",
                "C": "appoint ministers only",
                "D": "set school fees",
            },
            "B",
            "Referendums put issues to the people.",
            6,
        ),
        (
            "Sustainable agriculture aims to",
            {
                "A": "exhaust soils quickly",
                "B": "produce food while protecting the environment",
                "C": "ban all farming",
                "D": "use only imported food",
            },
            "B",
            "It balances production and conservation.",
            5,
        ),
        (
            "Ethnic diversity in Ghana means",
            {
                "A": "one culture only",
                "B": "many ethnic groups and cultures",
                "C": "no traditional leaders",
                "D": "identical languages",
            },
            "B",
            "Ghana has multiple ethnic groups.",
            4,
        ),
        (
            "Which institution fights corruption in Ghana?",
            {
                "A": "CHRAJ / related anti-corruption bodies",
                "B": "Football clubs",
                "C": "Markets only",
                "D": "Tour guides",
            },
            "A",
            "CHRAJ and related agencies address corruption.",
            6,
        ),
        (
            "Globalisation increases",
            {
                "A": "isolation of countries",
                "B": "interdependence among countries",
                "C": "only local trade",
                "D": "border walls only",
            },
            "B",
            "Globalisation links economies and cultures.",
            5,
        ),
        (
            "A citizen differs from a foreigner mainly by",
            {
                "A": "height",
                "B": "legal membership of the state",
                "C": "favourite food",
                "D": "school uniform",
            },
            "B",
            "Citizenship is legal membership.",
            5,
        ),
        (
            "Conflict resolution at community level often uses",
            {
                "A": "dialogue and mediation",
                "B": "ignoring problems",
                "C": "more conflict",
                "D": "only foreign armies",
            },
            "A",
            "Mediation and dialogue settle disputes.",
            5,
        ),
        (
            "Adolescent reproductive health education helps young people",
            {
                "A": "avoid all friends",
                "B": "make informed, responsible choices",
                "C": "stop schooling",
                "D": "ignore adults always",
            },
            "B",
            "It supports informed decisions.",
            4,
        ),
    ],
)

bulk(
    "soc-shs3",
    "social_studies",
    "SHS 3",
    [
        (
            "Separation of powers means",
            {
                "A": "one person holds all power",
                "B": "executive, legislature and judiciary are distinct",
                "C": "no elections",
                "D": "army rules",
            },
            "B",
            "Powers are divided among arms of government.",
            8,
        ),
        (
            "GDP measures",
            {
                "A": "population size",
                "B": "value of goods and services produced",
                "C": "literacy only",
                "D": "rainfall",
            },
            "B",
            "GDP is output value in a period.",
            8,
        ),
        (
            "Which best describes nation building?",
            {
                "A": "Destroying infrastructure",
                "B": "Uniting people and developing the state",
                "C": "Ignoring national symbols",
                "D": "Ending education",
            },
            "B",
            "Nation building strengthens unity and development.",
            7,
        ),
        (
            "An NGO is typically",
            {
                "A": "a government ministry",
                "B": "a non-governmental organisation",
                "C": "a political party only",
                "D": "a police unit",
            },
            "B",
            "NGOs are independent of government.",
            7,
        ),
        (
            "Climate change adaptation means",
            {
                "A": "ignoring climate risks",
                "B": "adjusting practices to cope with climate impacts",
                "C": "increasing emissions only",
                "D": "banning science",
            },
            "B",
            "Adaptation adjusts to climate impacts.",
            9,
        ),
        (
            "The African Union aims mainly to",
            {
                "A": "colonise Africa",
                "B": "promote African unity and cooperation",
                "C": "end all trade",
                "D": "replace all languages",
            },
            "B",
            "AU fosters continental cooperation.",
            8,
        ),
        (
            "Rule of law implies",
            {
                "A": "leaders are above the law",
                "B": "everyone is subject to the law",
                "C": "laws are optional",
                "D": "only the poor obey laws",
            },
            "B",
            "No one is above the law.",
            8,
        ),
        (
            "Youth unemployment can be reduced by",
            {
                "A": "skills training and entrepreneurship support",
                "B": "banning education",
                "C": "closing all businesses",
                "D": "ignoring skills gaps",
            },
            "A",
            "Skills and enterprise create opportunities.",
            8,
        ),
        (
            "Press freedom supports democracy by",
            {
                "A": "hiding information",
                "B": "enabling informed public debate",
                "C": "banning criticism",
                "D": "replacing elections",
            },
            "B",
            "A free press informs citizens.",
            9,
        ),
        (
            "Decentralisation in Ghana involves",
            {
                "A": "all power in Accra only",
                "B": "transferring some power to local assemblies",
                "C": "ending local government",
                "D": "military zones only",
            },
            "B",
            "District assemblies exercise local authority.",
            8,
        ),
        (
            "A mixed economy combines",
            {
                "A": "only private ownership",
                "B": "public and private sector roles",
                "C": "no markets",
                "D": "barter only",
            },
            "B",
            "Mixed economies have both state and private activity.",
            7,
        ),
        (
            "National cohesion is strengthened by",
            {
                "A": "discrimination",
                "B": "tolerance and equal opportunity",
                "C": "excluding minorities",
                "D": "banning dialogue",
            },
            "B",
            "Inclusion and fairness build cohesion.",
            9,
        ),
    ],
)

# ── WASSCE-style (Phase 3 extra pool) ────────────────────────────────────────
wassce_rows = [
    (
        "english",
        'Which option best completes: "Neither the teacher nor the students ___ present."',
        {"A": "was", "B": "were", "C": "is", "D": "be"},
        "B",
        'With neither…nor, verb agrees with nearer subject "students".',
        11,
    ),
    (
        "english",
        'In a WASSCE comprehension passage, "reading between the lines" means',
        {
            "A": "skipping lines",
            "B": "inferring unstated meaning",
            "C": "counting words",
            "D": "copying answers",
        },
        "B",
        "It means inferring implied meaning.",
        12,
    ),
    (
        "english",
        "The most suitable register for a letter to a District Chief Executive is",
        {"A": "slang", "B": "formal", "C": "chat abbreviations", "D": "pidgin only"},
        "B",
        "Official letters use formal register.",
        11,
    ),
    (
        "english",
        "A summary that exceeds the word limit usually loses marks because it",
        {
            "A": "is too creative",
            "B": "fails task constraints",
            "C": "uses correct grammar",
            "D": "has a title",
        },
        "B",
        "Length limits are part of the task.",
        10,
    ),
    (
        "english",
        "Irony in a prose extract is best identified when",
        {
            "A": "characters always tell the truth",
            "B": "events contradict expectations",
            "C": "the setting is described",
            "D": "dialogue is missing",
        },
        "B",
        "Irony hinges on contrast with expectation.",
        12,
    ),
    (
        "english",
        "Choose the correctly punctuated sentence.",
        {
            "A": "However the plan failed.",
            "B": "However, the plan failed.",
            "C": "However the plan, failed.",
            "D": "However the, plan failed.",
        },
        "B",
        'Introductory "However" takes a comma.',
        10,
    ),
    (
        "english",
        "In literature, a tragic hero typically has a",
        {
            "A": "perfect life",
            "B": "fatal flaw leading to downfall",
            "C": "comic role only",
            "D": "silent part",
        },
        "B",
        "Hamartia drives tragedy.",
        12,
    ),
    (
        "english",
        "Coherence in an essay is mainly achieved through",
        {
            "A": "random examples",
            "B": "logical organisation and linking devices",
            "C": "longer words only",
            "D": "no paragraphs",
        },
        "B",
        "Organisation and links create coherence.",
        11,
    ),
    (
        "english",
        "Which is an example of hyperbole?",
        {
            "A": "He is as brave as a lion.",
            "B": "I have told you a million times.",
            "C": "The classroom was a zoo.",
            "D": "The wind whispered.",
        },
        "B",
        "Hyperbole is deliberate exaggeration.",
        11,
    ),
    (
        "english",
        "A topic sentence that is too broad for one paragraph should be",
        {
            "A": "kept unchanged",
            "B": "narrowed to a focused claim",
            "C": "deleted always",
            "D": "turned into a poem",
        },
        "B",
        "Focus improves paragraph unity.",
        10,
    ),
    (
        "core_maths",
        "If 3ˣ = 81, then x =",
        {"A": "3", "B": "4", "C": "5", "D": "27"},
        "B",
        "81=3⁴.",
        11,
    ),
    (
        "core_maths",
        "The roots of x² − 7x + 10 = 0 are",
        {"A": "2 and 5", "B": "1 and 10", "C": "−2 and −5", "D": "7 and 10"},
        "A",
        "(x−2)(x−5)=0.",
        11,
    ),
    (
        "core_maths",
        "A man invests GH¢800 at 5% simple interest per annum. Interest after 2 years is",
        {"A": "GH¢40", "B": "GH¢80", "C": "GH¢800", "D": "GH¢16"},
        "B",
        "I=PRT/100=800×5×2/100=80.",
        12,
    ),
    (
        "core_maths",
        "If tan θ = 3/4 in a right triangle, sin θ =",
        {"A": "3/5", "B": "4/5", "C": "3/4", "D": "5/3"},
        "A",
        "Opp=3, adj=4, hyp=5 → sin=3/5.",
        12,
    ),
    (
        "core_maths",
        "The 5th term of an AP with first term 3 and common difference 4 is",
        {"A": "15", "B": "19", "C": "23", "D": "7"},
        "B",
        "a5=a+(5−1)d=3+16=19.",
        11,
    ),
    (
        "core_maths",
        "P(A∪B)=P(A)+P(B)−P(A∩B). If P(A)=0.6, P(B)=0.5, P(A∩B)=0.2, then P(A∪B)=",
        {"A": "0.9", "B": "1.1", "C": "0.3", "D": "0.7"},
        "A",
        "0.6+0.5−0.2=0.9.",
        12,
    ),
    (
        "core_maths",
        "Differentiate y=x³ − 2x with respect to x.",
        {"A": "3x² − 2", "B": "x² − 2", "C": "3x − 2", "D": "3x²"},
        "A",
        "Power rule.",
        13,
    ),
    (
        "core_maths",
        "The area of a circle of radius 7 cm (take π=22/7) is",
        {"A": "44 cm²", "B": "154 cm²", "C": "22 cm²", "D": "49 cm²"},
        "B",
        "πr²=(22/7)×49=154.",
        10,
    ),
    (
        "core_maths",
        "If log x = 2 (common log), then x =",
        {"A": "20", "B": "100", "C": "200", "D": "0.02"},
        "B",
        "x=10²=100.",
        11,
    ),
    (
        "core_maths",
        "A bag has 3 red and 2 blue balls. Probability of drawing a red ball at random is",
        {"A": "2/5", "B": "3/5", "C": "3/2", "D": "1/5"},
        "B",
        "3 red out of 5.",
        10,
    ),
    (
        "integrated_science",
        "During anaerobic respiration in muscles, glucose is converted mainly to",
        {"A": "oxygen", "B": "lactic acid", "C": "starch", "D": "protein"},
        "B",
        "Anaerobic muscle respiration yields lactic acid.",
        11,
    ),
    (
        "integrated_science",
        "Which statement about isotopes is correct?",
        {
            "A": "Same mass number, different atomic number",
            "B": "Same atomic number, different mass number",
            "C": "Different elements entirely",
            "D": "No neutrons",
        },
        "B",
        "Isotopes share Z, differ in A.",
        12,
    ),
    (
        "integrated_science",
        "A transformer works on the principle of",
        {
            "A": "electrostatic induction only",
            "B": "mutual induction",
            "C": "photoelectric effect",
            "D": "radioactivity",
        },
        "B",
        "Changing flux induces emf via mutual induction.",
        12,
    ),
    (
        "integrated_science",
        "Eutrophication in water bodies is often caused by",
        {
            "A": "excess nutrients from fertilisers",
            "B": "pure distilled water",
            "C": "lack of sunlight only",
            "D": "low temperatures only",
        },
        "A",
        "Nutrient overload drives algal blooms.",
        11,
    ),
    (
        "integrated_science",
        "In the electromagnetic spectrum, which has the highest frequency?",
        {"A": "Radio waves", "B": "Microwaves", "C": "Infrared", "D": "Gamma rays"},
        "D",
        "Gamma rays have highest frequency.",
        12,
    ),
    (
        "integrated_science",
        "A balanced chemical equation must have",
        {
            "A": "equal numbers of atoms of each element on both sides",
            "B": "equal volumes only",
            "C": "same colour products",
            "D": "only one product",
        },
        "A",
        "Mass/atoms conserved.",
        10,
    ),
    (
        "integrated_science",
        "The endocrine system regulates the body using",
        {"A": "only nerves", "B": "hormones", "C": "bones", "D": "skin pigments"},
        "B",
        "Hormones are chemical messengers.",
        11,
    ),
    (
        "integrated_science",
        "Which practice conserves soil?",
        {
            "A": "Deforestation on slopes",
            "B": "Contour ploughing",
            "C": "Overgrazing",
            "D": "Burning all cover crops",
        },
        "B",
        "Contour ploughing reduces erosion.",
        11,
    ),
    (
        "integrated_science",
        "Kirchhoff's current law states that",
        {
            "A": "voltage is zero everywhere",
            "B": "sum of currents into a junction equals sum leaving",
            "C": "resistance is infinite",
            "D": "power is constant",
        },
        "B",
        "Charge conservation at a node.",
        13,
    ),
    (
        "integrated_science",
        "Vaccines help the body by",
        {
            "A": "destroying all white cells",
            "B": "stimulating immune memory against a pathogen",
            "C": "replacing antibiotics always",
            "D": "increasing sugar only",
        },
        "B",
        "Vaccines train adaptive immunity.",
        12,
    ),
    (
        "social_studies",
        "Which feature best characterises good governance?",
        {
            "A": "Secrecy and no accountability",
            "B": "Transparency, accountability and participation",
            "C": "Rule by force only",
            "D": "Ignoring the constitution",
        },
        "B",
        "Good governance is open and accountable.",
        11,
    ),
    (
        "social_studies",
        "Structural unemployment is mainly caused by",
        {
            "A": "temporary seasonal work only",
            "B": "mismatch between workers' skills and job needs",
            "C": "one-day strikes only",
            "D": "public holidays",
        },
        "B",
        "Skills–jobs mismatch drives structural unemployment.",
        12,
    ),
    (
        "social_studies",
        "The principle of checks and balances aims to",
        {
            "A": "concentrate power",
            "B": "prevent abuse of power",
            "C": "end all government",
            "D": "replace courts with police",
        },
        "B",
        "Arms of government restrain each other.",
        11,
    ),
    (
        "social_studies",
        "Which factor most directly fuels rapid urbanisation in Ghana?",
        {
            "A": "Rural–urban migration",
            "B": "Decreasing city jobs",
            "C": "Ban on transport",
            "D": "Closing universities",
        },
        "A",
        "Migration swells urban populations.",
        10,
    ),
    (
        "social_studies",
        "A pluralistic society is one that",
        {
            "A": "allows only one culture",
            "B": "recognises diverse groups and interests",
            "C": "bans religions",
            "D": "has no laws",
        },
        "B",
        "Pluralism values diversity.",
        11,
    ),
    (
        "social_studies",
        "Foreign direct investment (FDI) typically involves",
        {
            "A": "tourists buying souvenirs",
            "B": "foreign firms investing in productive assets in a country",
            "C": "only remittances",
            "D": "school fees abroad",
        },
        "B",
        "FDI is long-term productive investment.",
        12,
    ),
    (
        "social_studies",
        "Which is a key function of the judiciary?",
        {
            "A": "Making all laws alone",
            "B": "Interpreting laws and administering justice",
            "C": "Collecting taxes",
            "D": "Running elections alone",
        },
        "B",
        "Courts interpret and apply law.",
        10,
    ),
    (
        "social_studies",
        "Gender equity policies aim to",
        {
            "A": "exclude men always",
            "B": "promote fairness of opportunity for all genders",
            "C": "end education for girls",
            "D": "ignore unpaid care work forever",
        },
        "B",
        "Equity seeks fair opportunities.",
        11,
    ),
    (
        "social_studies",
        "Desertification is accelerated by",
        {
            "A": "afforestation",
            "B": "overgrazing and deforestation",
            "C": "irrigation management",
            "D": "soil conservation",
        },
        "B",
        "Vegetation loss drives desertification.",
        12,
    ),
    (
        "social_studies",
        "In democratic elections, universal adult suffrage means",
        {
            "A": "only the rich vote",
            "B": "adult citizens generally have the right to vote",
            "C": "children vote",
            "D": "appointments replace voting",
        },
        "B",
        "Suffrage is the adult right to vote.",
        10,
    ),
]

prefix_map = {
    "english": "eng",
    "core_maths": "math",
    "integrated_science": "sci",
    "social_studies": "soc",
}
for i, (subj, q, o, a, e, d) in enumerate(wassce_rows, 1):
    add(f"{prefix_map[subj]}-wassce-{i:03d}", subj, "SHS 3", "wassce", d, q, o, a, e)

if __name__ == "__main__":
    OUT.write_text(json.dumps(bank, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(bank)} questions to {OUT}")
    print("by level/style:", dict(Counter((q["shs_level"], q["exam_style"]) for q in bank)))
    print("by subject:", dict(Counter(q["subject"] for q in bank)))
