"""
cleanup_bad_questions.py

Removes fake placeholder questions that were generated by the old
_mock_questions() fallback in ai_agent.py. These are templated
questions like "Adaptive X puzzle: If Difficulty=..." that shouldn't
exist in the database.
"""
import asyncio
from sqlalchemy import select, delete
from app.database import AsyncSessionLocal
from app.assessment.models import Question


async def cleanup():
    async with AsyncSessionLocal() as db:
        # Find all bad questions
        result = await db.execute(
            select(Question).where(Question.question.like("Adaptive % puzzle%"))
        )
        bad_questions = result.scalars().all()

        if not bad_questions:
            print("[OK] No bad placeholder questions found in the database.")
            return

        print(f"Found {len(bad_questions)} bad question(s):")
        for q in bad_questions:
            print(f"  - ID {q.id}: {q.question[:60]}...")

        # Delete them
        for q in bad_questions:
            await db.delete(q)

        await db.commit()
        print(f"\n[DELETED] {len(bad_questions)} bad question(s) cleaned up.")


if __name__ == "__main__":
    asyncio.run(cleanup())
