"""
add_remaining_social_studies.py
Appends modules 5-12 to the Social Studies SHS 2 lessons file.
"""
import re

filepath = "app/lib/generatedSocialStudiesSHS2Lessons.ts"

with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

# The remaining modules placeholder
placeholder = """  // ── MODULES 5-12 (abbreviated for length, but comprehensive in production) ──

  // For brevity, the remaining modules follow the same pattern.
  // Each module has 2 lessons with the same quality structure.

];"""

if placeholder not in content:
    print("ERROR: Placeholder not found!")
    exit(1)

modules_5_12 = """
  // ────────────────────────────────────────────────────────────────────────────
  // MODULE 5: NATIONALISM, CITIZENSHIP AND NATION BUILDING
  // ────────────────────────────────────────────────────────────────────────────

  {
    id: "soc-st-2-s5t1",
    title: "Nationalism and the Independence Struggle",
    subject: "Social Studies",
    subjectIcon: "🏛️",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 3,
    estimatedMinutes: 18,
    xpReward: 45,
    prerequisites: ["soc-st-2-s4t3"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s5t1-intro", type: "info", content: "**Nationalism and the Independence Struggle**\\\\n\\\\nNationalism is the desire of a people to govern themselves and control their own destiny. In Ghana, nationalism grew as a response to colonial rule and led to the independence movement that achieved freedom on March 6, 1957.\\\\n\\\\nIn this lesson, we will explore the rise of nationalism in Ghana and the key events that led to independence." },
      { id: "soc-st-2-s5t1-content-1", type: "info", content: "**The Rise of Nationalism in the Gold Coast**\\\\n\\\\n**Factors that Contributed to the Rise of Nationalism:**\\\\n\\\\n**1. Education:** Western-educated Ghanaians were exposed to ideas of democracy, freedom, and self-determination. They began to question colonial rule.\\\\n\\\\n**2. Ex-Servicemen:** Ghanaian soldiers who fought for Britain in World War II returned with military experience and expectations of better treatment. When these expectations were not met, they became leaders in the nationalist movement.\\\\n\\\\n**3. Economic Grievances:** The colonial economy favoured British interests. Farmers were paid low prices for cocoa, and there were few opportunities for Ghanaians in business and industry.\\\\n\\\\n**4. The 1948 Accra Riots:** Following the shooting of ex-servicemen peacefully marching to present a petition to the Governor, widespread riots broke out in Accra. This marked a turning point in the nationalist movement.\\\\n\\\\n**5. The Role of Newspapers:** Nationalist newspapers like the *Accra Evening News* spread nationalist ideas and mobilised public opinion." },
      { id: "soc-st-2-s5t1-content-2", type: "info", content: "**Key Organisations and Leaders**\\\\n\\\\n**The United Gold Coast Convention (UGCC):**\\\\n• Founded in 1947 by J.B. Danquah, George Grant, and others\\\\n• Aimed to achieve self-government in the shortest possible time\\\\n• Composed mainly of the educated elite and traditional rulers\\\\n• Kwame Nkrumah was invited to become the General Secretary\\\\n\\\\n**The Convention People's Party (CPP):**\\\\n• Founded by Kwame Nkrumah in 1949 after breaking away from the UGCC\\\\n• Slogan: \\\"Self-Government Now!\\\"\\\\n• Mass-based party that appealed to ordinary people\\\\n• Organised Positive Action campaigns of civil disobedience\\\\n\\\\n**Key Leaders of the Independence Movement:**\\\\n• **Kwame Nkrumah:** First Prime Minister and President of Ghana, pan-Africanist leader\\\\n• **J.B. Danquah:** Scholar, lawyer, and founding father of Ghanaian nationalism\\\\n• **Edward Akufo-Addo:** One of the UGCC founders, later Chief Justice and President\\\\n• **Emmanuel Obetsebi-Lamptey:** Lawyer and nationalist\\\\n• **William Ofori Atta:** One of the UGCC founders" },
      { id: "soc-st-2-s5t1-content-3", type: "info", content: "**The Road to Independence**\\\\n\\\\n**Timeline of Key Events:**\\\\n• **1947:** UGCC formed\\\\n• **1948:** Accra Riots and arrest of the Big Six (Nkrumah, Danquah, Akufo-Addo, Obetsebi-Lamptey, Ofori Atta, Ako-Adjei)\\\\n• **1949:** Nkrumah forms CPP\\\\n• **1950:** Positive Action campaign — strikes and boycotts\\\\n• **1951:** First general election — CPP wins overwhelmingly\\\\n• **1951:** Nkrumah released from prison to become Leader of Government Business\\\\n• **1954:** Second general election — CPP wins again\\\\n• **1956:** Third general election — CPP wins, independence demanded\\\\n• **March 6, 1957:** Ghana declares independence — the first sub-Saharan African country to do so!\\\\n\\\\n**The Big Six:** The six leaders arrested after the 1948 riots are remembered as the founding fathers of Ghana: Kwame Nkrumah, J.B. Danquah, Edward Akufo-Addo, Emmanuel Obetsebi-Lamptey, William Ofori Atta, and Ebenezer Ako-Adjei." },
      { id: "soc-st-2-s5t1-exercise", type: "question", content: "Check your understanding:", exercise: { question: "When did Ghana gain independence?", options: ["March 6, 1956", "March 6, 1957", "July 1, 1960", "February 12, 1951"], correctIndex: 1, explanation: "Ghana declared independence on March 6, 1957, becoming the first sub-Saharan African country to gain independence from colonial rule." } },
      { id: "soc-st-2-s5t1-summary", type: "info", content: "✅ **Key Takeaways: Nationalism and the Independence Struggle**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The factors that contributed to the rise of nationalism in Ghana\\\\n• The key organisations (UGCC, CPP) and leaders\\\\n• The timeline of events leading to independence on March 6, 1957\\\\n\\\\nGhana's independence inspired liberation movements across Africa." },
      { id: "soc-st-2-s5t1-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Nationalism — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "Which party was founded by Kwame Nkrumah with the slogan 'Self-Government Now!'?", options: ["UGCC", "CPP", "NCBWA", "ARPS"], correctIndex: 1, explanation: "The Convention People's Party (CPP) was founded by Nkrumah in 1949 with the slogan 'Self-Government Now!'" }, { question: "Who are the Big Six in Ghana's independence history?", options: ["Six members of parliament", "Six leaders arrested after the 1948 Accra Riots", "Six traditional chiefs", "Six British governors"], correctIndex: 1, explanation: "The Big Six were the six nationalist leaders arrested after the 1948 Accra Riots: Nkrumah, Danquah, Akufo-Addo, Obetsebi-Lamptey, Ofori Atta, and Ako-Adjei." } ] } }
    ]
  },

  {
    id: "soc-st-2-s5t2",
    title: "Citizenship and Nation Building",
    subject: "Social Studies",
    subjectIcon: "🏛️",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 2,
    estimatedMinutes: 16,
    xpReward: 40,
    prerequisites: ["soc-st-2-s5t1"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s5t2-intro", type: "info", content: "**Citizenship and Nation Building**\\\\n\\\\nCitizenship is the status of being a member of a nation, with rights and responsibilities. Nation building is the process of constructing a national identity and developing the institutions, infrastructure, and economy of a country.\\\\n\\\\nIn this lesson, we will explore what it means to be a Ghanaian citizen and how citizens contribute to building the nation." },
      { id: "soc-st-2-s5t2-content-1", type: "info", content: "**Citizenship in Ghana**\\\\n\\\\n**How Citizenship is Acquired:**\\\\n\\\\n**1. By Birth:** A person born in Ghana or born outside Ghana to a Ghanaian parent is a citizen by birth.\\\\n\\\\n**2. By Registration:** Non-Ghanaians who have lived in Ghana for a specified period can apply for citizenship.\\\\n\\\\n**3. By Naturalisation:** Foreigners who meet certain conditions (residency, good character, knowledge of Ghanaian culture) can be granted citizenship.\\\\n\\\\n**Rights of Ghanaian Citizens:**\\\\n• Right to vote in elections\\\\n• Right to be voted for (stand for public office)\\\\n• Right to own property\\\\n• Right to freedom of speech and assembly\\\\n• Right to education and healthcare\\\\n• Right to equal treatment under the law\\\\n\\\\n**Responsibilities of Citizens:**\\\\n• Obeying the law\\\\n• Paying taxes\\\\n• Protecting the environment\\\\n• Serving on juries when called\\\\n• Participating in national development\\\\n• Defending the nation when necessary" },
      { id: "soc-st-2-s5t2-content-2", type: "info", content: "**Nation Building — Our Collective Responsibility**\\\\n\\\\nNation building involves every citizen contributing to the development of the country.\\\\n\\\\n**Areas of Nation Building:**\\\\n\\\\n**1. Political Development:**\\\\n• Participating in elections and democratic processes\\\\n• Promoting peace and stability\\\\n• Respecting the rule of law\\\\n\\\\n**2. Economic Development:**\\\\n• Engaging in productive work\\\\n• Starting and growing businesses\\\\n• Supporting local industries\\\\n• Paying taxes\\\\n\\\\n**3. Social Development:**\\\\n• Promoting education and skills development\\\\n• Supporting healthcare and sanitation\\\\n• Helping the vulnerable in society\\\\n\\\\n**4. Cultural Development:**\\\\n• Preserving Ghanaian culture and traditions\\\\n• Promoting national unity despite diversity\\\\n• Celebrating our heritage\\\\n\\\\n**5. Infrastructure Development:**\\\\n• Maintaining public facilities\\\\n• Reporting broken infrastructure\\\\n• Participating in community projects" },
      { id: "soc-st-2-s5t2-activity-1", type: "info", content: "**Activity 5.2 — Being an Active Citizen**\\\\n\\\\n1. List three responsibilities you have as a citizen of Ghana.\\\\n2. Identify one way you can contribute to nation building in your community.\\\\n3. Create a short presentation titled \\\"How Students Can Help Build Ghana\\\" and share it with your class.\\\\n4. Discuss: Why is it important for citizens to be actively involved in nation building?" },
      { id: "soc-st-2-s5t2-exercise", type: "question", content: "Test your understanding:", exercise: { question: "What is one responsibility of a Ghanaian citizen?", options: ["Ignoring the law", "Paying taxes", "Avoiding community service", "Only voting if interested"], correctIndex: 1, explanation: "Paying taxes is a fundamental responsibility of citizens. Taxes fund public services like schools, hospitals, roads, and security." } },
      { id: "soc-st-2-s5t2-summary", type: "info", content: "✅ **Key Takeaways: Citizenship and Nation Building**\\\\n\\\\nIn this lesson, you learned about:\\\\n• How Ghanaian citizenship is acquired\\\\n• The rights and responsibilities of citizens\\\\n• How citizens can contribute to nation building\\\\n\\\\nEvery citizen has a role to play in building the Ghana we want." },
      { id: "soc-st-2-s5t2-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Citizenship — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "What is nation building?", options: ["Only the government's responsibility", "The process of constructing national identity and developing the country", "Building physical structures", "A political campaign"], correctIndex: 1, explanation: "Nation building is the process of constructing a national identity and developing the institutions, infrastructure, and economy of a country." }, { question: "Which of the following is a right of Ghanaian citizens?", options: ["Right to ignore taxes", "Right to vote", "Right to break laws", "Right to avoid jury duty"], correctIndex: 1, explanation: "Ghanaian citizens have the right to vote in elections, among other political, economic, and social rights." } ] } }
    ]
  },

  // ────────────────────────────────────────────────────────────────────────────
  // MODULE 6: LEISURE AND TOURISM
  // ────────────────────────────────────────────────────────────────────────────

  {
    id: "soc-st-2-s6t1",
    title: "Understanding Leisure and Tourism",
    subject: "Social Studies",
    subjectIcon: "🏖️",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 1,
    estimatedMinutes: 14,
    xpReward: 35,
    prerequisites: ["soc-st-2-s5t2"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s6t1-intro", type: "info", content: "**Understanding Leisure and Tourism**\\\\n\\\\nLeisure is free time when we are not working or studying — time we can use to relax, have fun, or pursue personal interests. Tourism involves travelling to places for leisure, business, or other purposes.\\\\n\\\\nIn this lesson, we will explore the concepts of leisure and tourism and their importance to individuals and the economy." },
      { id: "soc-st-2-s6t1-content-1", type: "info", content: "**What is Leisure?**\\\\n\\\\nLeisure refers to the time when a person is not engaged in work, study, or other obligatory activities. It is time for relaxation, recreation, and personal development.\\\\n\\\\n**Types of Leisure Activities:**\\\\n\\\\n**Physical Activities:** Sports, exercise, dancing, hiking\\\\n**Social Activities:** Visiting friends, attending parties, community gatherings\\\\n**Cultural Activities:** Festivals, concerts, visiting museums\\\\n**Creative Activities:** Drawing, writing, music, crafts\\\\n**Quiet Activities:** Reading, watching movies, listening to music\\\\n**Outdoor Activities:** Fishing, camping, nature walks\\\\n\\\\n**Benefits of Leisure:**\\\\n• Improves physical and mental health\\\\n• Reduces stress\\\\n• Strengthens social bonds\\\\n• Develops skills and talents\\\\n• Enhances quality of life\\\\n\\\\n**Factors That Influence Choice of Leisure Activities:**\\\\n• Age\\\\n• Income\\\\n• Education\\\\n• Culture and background\\\\n• Available facilities\\\\n• Personal interests" },
      { id: "soc-st-2-s6t1-content-2", type: "info", content: "**Understanding Tourism**\\\\n\\\\nTourism is travel for pleasure, business, or other purposes. Tourists are people who travel to and stay in places outside their usual environment for not more than one year.\\\\n\\\\n**Types of Tourism:**\\\\n\\\\n**1. Domestic Tourism:** Travelling within one's own country (e.g., a Ghanaian visiting Kakum National Park)\\\\n\\\\n**2. International Tourism:** Travelling to another country\\\\n   • **Inbound Tourism:** Foreigners visiting Ghana\\\\n   • **Outbound Tourism:** Ghanaians travelling abroad\\\\n\\\\n**Forms of Tourism:**\\\\n• **Eco-tourism:** Nature-based tourism focusing on conservation\\\\n• **Cultural Tourism:** Visiting historical sites and cultural attractions\\\\n• **Adventure Tourism:** Activities like hiking, rafting, and climbing\\\\n• **Beach Tourism:** Relaxing at beach resorts\\\\n• **Medical Tourism:** Travelling for healthcare\\\\n• **Business Tourism:** Travelling for conferences and meetings\\\\n\\\\n**Importance of Tourism:**\\\\n• Creates jobs (hotels, transport, tour guides)\\\\n• Earns foreign exchange\\\\n• Promotes cultural exchange\\\\n• Preserves cultural heritage\\\\n• Supports local businesses\\\\n• Develops infrastructure" },
      { id: "soc-st-2-s6t1-activity-1", type: "info", content: "**Activity 6.1 — Tourism in My Community**\\\\n\\\\n1. Identify tourist attractions in your community or region.\\\\n2. Research one tourist site and find out:\\\\n   • Where it is located\\\\n   • What makes it special\\\\n   • How many people visit each year\\\\n   • How it benefits the local community\\\\n3. Present your findings to the class." },
      { id: "soc-st-2-s6t1-exercise", type: "question", content: "Test your understanding:", exercise: { question: "What is the difference between domestic and international tourism?", options: ["There is no difference", "Domestic tourism is within one's own country; international tourism is to other countries", "Domestic tourism is cheaper", "International tourism is only for business"], correctIndex: 1, explanation: "Domestic tourism involves travelling within one's own country, while international tourism involves travelling to other countries." } },
      { id: "soc-st-2-s6t1-summary", type: "info", content: "✅ **Key Takeaways: Understanding Leisure and Tourism**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The meaning and benefits of leisure\\\\n• Types of leisure activities\\\\n• The concept of tourism and its different forms\\\\n• The economic and social importance of tourism" },
      { id: "soc-st-2-s6t1-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Leisure and Tourism — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "Which of the following is an example of eco-tourism?", options: ["Shopping in Accra mall", "Visiting Kakum National Park", "Attending a conference", "Going to the cinema"], correctIndex: 1, explanation: "Eco-tourism focuses on nature and conservation. Visiting a national park like Kakum is an example of eco-tourism." }, { question: "What is one economic benefit of tourism to Ghana?", options: ["It costs the country money", "It creates jobs and earns foreign exchange", "It only benefits foreigners", "It destroys the environment"], correctIndex: 1, explanation: "Tourism creates jobs in hotels, transport, and guiding, and earns foreign exchange for the country." } ] } }
    ]
  },

  {
    id: "soc-st-2-s6t2",
    title: "Tourism in Ghana",
    subject: "Social Studies",
    subjectIcon: "🏖️",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 2,
    estimatedMinutes: 16,
    xpReward: 40,
    prerequisites: ["soc-st-2-s6t1"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s6t2-intro", type: "info", content: "**Tourism in Ghana**\\\\n\\\\nGhana is blessed with abundant tourist attractions — from beautiful beaches and national parks to historic castles and vibrant cultural festivals. Tourism is one of the fastest-growing sectors of Ghana's economy.\\\\n\\\\nIn this lesson, we will explore Ghana's major tourist attractions and the potential of the tourism industry." },
      { id: "soc-st-2-s6t2-content-1", type: "info", content: "**Major Tourist Attractions in Ghana**\\\\n\\\\n**Historical and Heritage Sites:**\\\\n• **Cape Coast Castle and Elmina Castle:** UNESCO World Heritage sites, reminders of the trans-Atlantic slave trade\\\\n• **Kwame Nkrumah Memorial Park:** Dedicated to Ghana's first President\\\\n• **Fort Christiansborg (Osu Castle):** Seat of government for many years\\\\n• **Independence Square:** Symbol of Ghana's freedom\\\\n\\\\n**Natural Attractions:**\\\\n• **Kakum National Park:** Canopy walkway, rainforest, diverse wildlife\\\\n• **Mole National Park:** Largest wildlife reserve in Ghana, elephants and antelopes\\\\n• **Wli Waterfalls:** Highest waterfall in West Africa\\\\n• **Lake Volta:** The largest man-made lake in the world\\\\n• **Boti Falls:** Twin waterfalls in the Eastern Region\\\\n• **Ada and Kokrobite Beaches:** Beautiful coastal resorts\\\\n\\\\n**Cultural Attractions:**\\\\n• **Panafest:** Pan-African Historical Theatre Festival\\\\n• **Homowo Festival (Ga):** Harvest festival\\\\n• **Aboakyer Festival (Effutu):** Deer hunting festival\\\\n• **Bakatue Festival (Elmina):** Fishing festival\\\\n• **Kente weaving villages:** Bonwire in Ashanti Region" },
      { id: "soc-st-2-s6t2-content-2", type: "info", content: "**Developing Tourism in Ghana**\\\\n\\\\n**Strengths of Ghana's Tourism Industry:**\\\\n• Rich cultural heritage and history\\\\n• Political stability\\\\n• Warm and welcoming people\\\\n• Diverse attractions (beaches, parks, castles, festivals)\\\\n• English-speaking country\\\\n\\\\n**Challenges Facing the Tourism Industry:**\\\\n• Inadequate infrastructure (roads, airports, hotels)\\\\n• Limited marketing and promotion\\\\n• High cost of domestic air travel\\\\n• Seasonal nature of tourism\\\\n• Competition from other destinations\\\\n• Conservation and maintenance of sites\\\\n\\\\n**Strategies to Boost Tourism:**\\\\n• Improve infrastructure\\\\n• Train more tour guides and hospitality staff\\\\n• Promote domestic tourism among Ghanaians\\\\n• Use digital marketing to reach international tourists\\\\n• Develop new attractions and experiences\\\\n• Protect and maintain existing sites\\\\n• Encourage community participation in tourism" },
      { id: "soc-st-2-s6t2-activity-1", type: "info", content: "**Activity 6.2 — Promoting Ghanaian Tourism**\\\\n\\\\nDesign a poster or short video promoting one tourist attraction in Ghana. Include:\\\\n1. The name and location of the attraction\\\\n2. What makes it special\\\\n3. How visitors can get there\\\\n4. Why people should visit\\\\n\\\\nDisplay your poster in class or share your video with classmates." },
      { id: "soc-st-2-s6t2-exercise", type: "question", content: "Test your understanding:", exercise: { question: "Which national park in Ghana is famous for its canopy walkway?", options: ["Mole National Park", "Kakum National Park", "Shai Hills Reserve", "Digya National Park"], correctIndex: 1, explanation: "Kakum National Park is famous for its canopy walkway, a series of suspension bridges high above the rainforest floor." } },
      { id: "soc-st-2-s6t2-summary", type: "info", content: "✅ **Key Takeaways: Tourism in Ghana**\\\\n\\\\nIn this lesson, you learned about:\\\\n• Major tourist attractions in Ghana (historical, natural, cultural)\\\\n• The strengths and challenges of Ghana's tourism industry\\\\n• Strategies to develop and promote tourism\\\\n\\\\nTourism has great potential to contribute to Ghana's economic development." },
      { id: "soc-st-2-s6t2-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Tourism in Ghana — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "Which festival is celebrated by the people of Elmina?", options: ["Homowo", "Bakatue", "Aboakyer", "Damba"], correctIndex: 1, explanation: "Bakatue is a fishing festival celebrated by the people of Elmina." }, { question: "What is a major challenge facing Ghana's tourism industry?", options: ["Too many tourists", "Inadequate infrastructure", "No attractions", "Ghanaians dislike tourism"], correctIndex: 1, explanation: "Inadequate infrastructure including roads, airports, and hotels is a major challenge facing Ghana's tourism industry." } ] } }
    ]
  },

  // ────────────────────────────────────────────────────────────────────────────
  // MODULE 7: REVOLUTIONS THAT CHANGED THE WORLD
  // ────────────────────────────────────────────────────────────────────────────

  {
    id: "soc-st-2-s7t1",
    title: "Major Revolutions in History",
    subject: "Social Studies",
    subjectIcon: "🔥",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 3,
    estimatedMinutes: 18,
    xpReward: 45,
    prerequisites: ["soc-st-2-s6t2"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s7t1-intro", type: "info", content: "**Major Revolutions in History**\\\\n\\\\nRevolutions are fundamental and rapid changes in political, social, or economic systems. Throughout history, revolutions have transformed societies and shaped the world we live in today.\\\\n\\\\nIn this lesson, we will explore some of the most significant revolutions in world history and their impact." },
      { id: "soc-st-2-s7t1-content-1", type: "info", content: "**The Agricultural Revolution (c. 10,000 BCE)**\\\\n\\\\nThe transition from hunting and gathering to settled agriculture.\\\\n\\\\n**Key Changes:**\\\\n• Humans began domesticating plants and animals\\\\n• Permanent settlements replaced nomadic lifestyles\\\\n• Food surplus led to population growth\\\\n• Specialisation of labour (crafts, trade, governance)\\\\n• Development of writing and record-keeping\\\\n\\\\n**Impact:** Laid the foundation for civilisation itself, including the rise of cities, trade, and organised government.\\\\n\\\\n**The Industrial Revolution (1760–1840)**\\\\n\\\\nThe shift from manual labour to machine-based manufacturing.\\\\n\\\\n**Key Changes:**\\\\n• Invention of steam engine, spinning jenny, power loom\\\\n• Rise of factories and mass production\\\\n• Urbanisation as people moved to cities for work\\\\n• Improved transportation (railways, steamships)\\\\n• New social classes (industrial workers and capitalists)\\\\n\\\\n**Impact:** Transformed economies, societies, and daily life. Led to modern capitalism, but also to poor working conditions and environmental pollution." },
      { id: "soc-st-2-s7t1-content-2", type: "info", content: "**The French Revolution (1789–1799)**\\\\n\\\\nA revolution that overthrew the French monarchy and established a republic.\\\\n\\\\n**Causes:**\\\\n• Extreme inequality between the rich nobility and poor commoners\\\\n• Financial crisis and heavy taxation\\\\n• Enlightenment ideas of liberty, equality, fraternity\\\\n• Food shortages and economic hardship\\\\n\\\\n**Key Events:**\\\\n• Storming of the Bastille (July 14, 1789)\\\\n• Declaration of the Rights of Man and of the Citizen\\\\n• Reign of Terror under Robespierre\\\\n• Rise of Napoleon Bonaparte\\\\n\\\\n**Impact:** Spread ideas of democracy, nationalism, and human rights across Europe and the world.\\\\n\\\\n**The Russian Revolution (1917)**\\\\n\\\\nOverthrew the Russian monarchy and established the world's first communist state.\\\\n\\\\n**Causes:**\\\\n• Autocratic rule of the Tsar\\\\n• Defeat in World War I\\\\n• Economic hardship and food shortages\\\\n• Rise of revolutionary ideas (Marxism)\\\\n\\\\n**Impact:** Led to the creation of the Soviet Union, inspired communist movements worldwide, and shaped 20th-century geopolitics." },
      { id: "soc-st-2-s7t1-content-3", type: "info", content: "**Other Important Revolutions**\\\\n\\\\n**The American Revolution (1775–1783):**\\\\n• Thirteen American colonies fought for independence from Britain\\\\n• Led to the creation of the United States of America\\\\n• Established democratic principles and a constitution based on separation of powers\\\\n\\\\n**The Haitian Revolution (1791–1804):**\\\\n• Enslaved Africans in Haiti revolted against French colonial rule\\\\n• Successfully abolished slavery and established an independent nation\\\\n• The only successful slave revolt in history\\\\n\\\\n**The Scientific Revolution (16th–17th Century):**\\\\n• Transformation in scientific thinking — Copernicus, Galileo, Newton\\\\n• Shift from religious to empirical explanations of the natural world\\\\n• Laid the foundation for modern science and technology\\\\n\\\\n**The Digital Revolution (Late 20th Century):**\\\\n• Rise of computers, the internet, and digital technology\\\\n• Transformed communication, work, education, and entertainment\\\\n• Continues to reshape every aspect of modern life" },
      { id: "soc-st-2-s7t1-exercise", type: "question", content: "Test your understanding:", exercise: { question: "Which revolution is associated with the slogan 'Liberty, Equality, Fraternity'?", options: ["American Revolution", "French Revolution", "Russian Revolution", "Industrial Revolution"], correctIndex: 1, explanation: "The French Revolution was inspired by Enlightenment ideas of liberty, equality, and fraternity." } },
      { id: "soc-st-2-s7t1-summary", type: "info", content: "✅ **Key Takeaways: Major Revolutions in History**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The Agricultural, Industrial, and Digital Revolutions\\\\n• The French, American, Russian, and Haitian Revolutions\\\\n• The causes, key events, and impacts of each revolution\\\\n\\\\nRevolutions have profoundly shaped the political, social, and economic systems of the modern world." },
      { id: "soc-st-2-s7t1-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Major Revolutions — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "What was a major cause of the French Revolution?", options: ["Too much equality", "Extreme inequality and financial crisis", "Industrialisation", "Foreign invasion"], correctIndex: 1, explanation: "The French Revolution was caused by extreme inequality between classes, financial crisis, and Enlightenment ideas." }, { question: "What is the significance of the Haitian Revolution?", options: ["It was the first revolution in Europe", "It was the only successful slave revolt in history", "It started the Industrial Revolution", "It ended colonialism in Africa"], correctIndex: 1, explanation: "The Haitian Revolution was the only successful slave revolt in history, leading to the establishment of an independent Haiti." } ] } }
    ]
  },

  {
    id: "soc-st-2-s7t2",
    title: "Impact of Revolutions on Society",
    subject: "Social Studies",
    subjectIcon: "🔥",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 2,
    estimatedMinutes: 16,
    xpReward: 40,
    prerequisites: ["soc-st-2-s7t1"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s7t2-intro", type: "info", content: "**Impact of Revolutions on Society**\\\\n\\\\nRevolutions do not only change political systems — they transform every aspect of society, including culture, economy, and daily life. Understanding the impact of past revolutions helps us appreciate the world we live in and prepare for future changes.\\\\n\\\\nIn this lesson, we will analyse the broad impacts of revolutions on society." },
      { id: "soc-st-2-s7t2-content-1", type: "info", content: "**Political Impacts of Revolutions**\\\\n\\\\n**Spread of Democracy and Human Rights:**\\\\n• The American and French Revolutions established the principle that government should be based on the consent of the governed\\\\n• Inspired movements for democracy worldwide\\\\n• Led to the Universal Declaration of Human Rights (1948)\\\\n\\\\n**Rise of Nationalism:**\\\\n• Revolutions often strengthen national identity\\\\n• People began to identify with their nation rather than their local region\\\\n• Nationalism became a powerful force in world politics\\\\n\\\\n**New Forms of Government:**\\\\n• End of absolute monarchy in many countries\\\\n• Rise of republics, democracies, and constitutional monarchies\\\\n• The Russian Revolution introduced communism as an alternative system\\\\n\\\\n**Decolonisation:**\\\\n• The ideals of revolution inspired colonised peoples to demand independence\\\\n• Ghana's independence movement was influenced by revolutionary ideas\\\\n• African and Asian countries gained independence after World War II" },
      { id: "soc-st-2-s7t2-content-2", type: "info", content: "**Economic and Social Impacts**\\\\n\\\\n**Economic Transformations:**\\\\n• The Industrial Revolution created the modern capitalist economy\\\\n• Mass production made goods cheaper and more accessible\\\\n• New industries and jobs emerged\\\\n• Economic inequality became a major social issue\\\\n\\\\n**Social Changes:**\\\\n• The French Revolution abolished feudalism and aristocratic privileges\\\\n• Women's rights movements were inspired by revolutionary ideas\\\\n• Education became more widely available\\\\n• Urbanisation changed family structures and community life\\\\n\\\\n**Cultural Impacts:**\\\\n• Revolutions often produced new art, music, and literature\\\\n• The Russian Revolution led to avant-garde art and architecture\\\\n• The Scientific Revolution changed how people understood the world\\\\n• The Digital Revolution created global connectivity\\\\n\\\\n**Lessons for Today:**\\\\n• Change is possible when people unite for a common cause\\\\n• Revolutions often have both positive and negative consequences\\\\n• Peaceful change is possible through democratic processes\\\\n• The struggle for justice and equality continues in every generation" },
      { id: "soc-st-2-s7t2-activity-1", type: "info", content: "**Activity 7.2 — Connecting Revolutions to Today**\\\\n\\\\nChoose one revolution studied in this module and answer:\\\\n1. What changes did this revolution bring?\\\\n2. Do we still feel the effects of this revolution today? How?\\\\n3. What lessons can we learn from this revolution?\\\\n4. How can we apply these lessons to address current challenges in Ghana?\\\\n\\\\nWrite a short essay or create a presentation." },
      { id: "soc-st-2-s7t2-exercise", type: "question", content: "Test your understanding:", exercise: { question: "How did the American and French Revolutions influence modern government?", options: ["They established the principle of government by consent of the governed", "They brought back monarchy", "They had no lasting impact", "They abolished all governments"], correctIndex: 0, explanation: "These revolutions established that government should be based on the consent of the governed, inspiring democracy worldwide." } },
      { id: "soc-st-2-s7t2-summary", type: "info", content: "✅ **Key Takeaways: Impact of Revolutions on Society**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The political impacts of revolutions (democracy, nationalism, decolonisation)\\\\n• The economic and social transformations brought by revolutions\\\\n• Cultural changes and lessons for today\\\\n\\\\nRevolutions remind us that ordinary people can change the course of history." },
      { id: "soc-st-2-s7t2-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Impact of Revolutions — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "Which revolution led to the rise of communism as a major political system?", options: ["French Revolution", "American Revolution", "Russian Revolution", "Industrial Revolution"], correctIndex: 2, explanation: "The Russian Revolution of 1917 established the world's first communist state and inspired communist movements worldwide." }, { question: "How did revolutions influence decolonisation in Africa?", options: ["They had no effect", "Revolutionary ideas of freedom and self-determination inspired independence movements", "Colonial powers granted independence willingly", "Revolutions made Africa less interested in independence"], correctIndex: 1, explanation: "The ideals of revolution — freedom, self-determination, and democracy — inspired colonised peoples in Africa and Asia to demand independence." } ] } }
    ]
  },

  // ────────────────────────────────────────────────────────────────────────────
  // MODULE 8: THE YOUTH AND NATIONAL DEVELOPMENT
  // ────────────────────────────────────────────────────────────────────────────

  {
    id: "soc-st-2-s8t1",
    title: "The Role of Youth in National Development",
    subject: "Social Studies",
    subjectIcon: "👥",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 2,
    estimatedMinutes: 16,
    xpReward: 40,
    prerequisites: ["soc-st-2-s7t2"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s8t1-intro", type: "info", content: "**The Role of Youth in National Development**\\\\n\\\\nYoung people are the future of every nation. In Ghana, youth (people aged 15–35) make up a significant portion of the population. The energy, creativity, and enthusiasm of young people are essential resources for national development.\\\\n\\\\nIn this lesson, we will explore the role of youth in Ghana's development and how young people can contribute to building the nation." },
      { id: "soc-st-2-s8t1-content-1", type: "info", content: "**Who Are the Youth?**\\\\n\\\\nThe National Youth Policy of Ghana defines youth as persons aged 15 to 35 years. This group represents a significant portion — over 35% — of Ghana's population.\\\\n\\\\n**Importance of Youth to National Development:**\\\\n\\\\n**1. Demographic Dividend:** A large youth population can drive economic growth if young people are healthy, educated, and employed.\\\\n\\\\n**2. Innovation and Creativity:** Young people often bring fresh ideas and innovative solutions to problems.\\\\n\\\\n**3. Energy and Enthusiasm:** Youth have the energy and drive to take on challenges and push for change.\\\\n\\\\n**4. Adaptability:** Young people are quick to learn new skills and adapt to new technologies.\\\\n\\\\n**5. Social Change:** Throughout history, young people have been at the forefront of movements for social and political change.\\\\n\\\\n**6. Continuity and Leadership:** Today's youth are tomorrow's leaders, professionals, and entrepreneurs." },
      { id: "soc-st-2-s8t1-content-2", type: "info", content: "**How Youth Can Contribute to National Development**\\\\n\\\\n**1. Education and Skills Development:**\\\\n• Take education seriously and strive for excellence\\\\n• Develop practical skills (vocational, digital, entrepreneurial)\\\\n• Pursue lifelong learning\\\\n\\\\n**2. Civic Engagement:**\\\\n• Register to vote and participate in elections\\\\n• Join youth organisations and community groups\\\\n• Volunteer for community service\\\\n• Be informed about national issues\\\\n\\\\n**3. Entrepreneurship and Employment:**\\\\n• Start small businesses\\\\n• Create jobs for others\\\\n• Innovate and solve local problems\\\\n• Develop a strong work ethic\\\\n\\\\n**4. Social Responsibility:**\\\\n• Promote peace and national unity\\\\n• Protect the environment\\\\n• Help the less fortunate\\\\n• Be a positive role model\\\\n\\\\n**5. Technology and Innovation:**\\\\n• Use technology for learning and productivity\\\\n• Develop digital skills\\\\n• Create solutions using technology" },
      { id: "soc-st-2-s8t1-activity-1", type: "info", content: "**Activity 8.1 — Youth Action Plan**\\\\n\\\\nCreate a personal action plan for how you will contribute to national development. Include:\\\\n\\\\n1. What skills do you want to develop?\\\\n2. How will you use your education to help your community?\\\\n3. What community service activities can you participate in?\\\\n4. How can you be a positive role model for others?\\\\n5. What goals do you have for contributing to Ghana's development?\\\\n\\\\nShare your action plan with a partner and discuss how you can support each other." },
      { id: "soc-st-2-s8t1-exercise", type: "question", content: "Test your understanding:", exercise: { question: "Why are young people important for national development?", options: ["They are not important", "They bring energy, creativity, and are future leaders", "Only adults can contribute", "Youth should only focus on school"], correctIndex: 1, explanation: "Young people bring energy, creativity, and innovation. They are the future leaders and drivers of economic growth and social change." } },
      { id: "soc-st-2-s8t1-summary", type: "info", content: "✅ **Key Takeaways: The Role of Youth in National Development**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The definition and importance of youth in Ghana\\\\n• How youth can contribute to national development\\\\n• The importance of education, civic engagement, and entrepreneurship\\\\n\\\\nEvery young Ghanaian has the power to make a difference in their community and nation." },
      { id: "soc-st-2-s8t1-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Youth and Development — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "What age range does Ghana's National Youth Policy define as youth?", options: ["10–25", "15–35", "18–40", "12–30"], correctIndex: 1, explanation: "Ghana's National Youth Policy defines youth as persons aged 15 to 35 years." }, { question: "What is the 'demographic dividend'?", options: ["A payment to young people", "Economic growth potential from a large youth population", "A tax on young workers", "A scholarship programme"], correctIndex: 1, explanation: "The demographic dividend refers to the economic growth potential that can result from a large, healthy, educated, and employed youth population." } ] } }
    ]
  },

  {
    id: "soc-st-2-s8t2",
    title: "Youth Empowerment and Skills Development",
    subject: "Social Studies",
    subjectIcon: "👥",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 2,
    estimatedMinutes: 16,
    xpReward: 40,
    prerequisites: ["soc-st-2-s8t1"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s8t2-intro", type: "info", content: "**Youth Empowerment and Skills Development**\\\\n\\\\nYouth empowerment is the process of providing young people with the resources, skills, opportunities, and support they need to reach their full potential and contribute to society.\\\\n\\\\nIn this lesson, we will explore various youth empowerment programmes and the importance of skills development for employment and entrepreneurship." },
      { id: "soc-st-2-s8t2-content-1", type: "info", content: "**Youth Empowerment Programmes in Ghana**\\\\n\\\\n**Government Programmes:**\\\\n\\\\n**1. National Youth Authority (NYA):**\\\\n• Coordinates youth development activities\\\\n• Runs skills training and leadership programmes\\\\n\\\\n**2. Youth Employment Agency (YEA):**\\\\n• Creates employment opportunities for young people\\\\n• Provides modules in community policing, sanitation, and teaching assistantships\\\\n\\\\n**3. Nation Builders Corps (NABCO):**\\\\n• Provided temporary employment for graduate youth in public services\\\\n\\\\n**4. Free Senior High School (Free SHS) Policy:**\\\\n• Provides free secondary education to all Ghanaian students\\\\n• Increases access to education and reduces drop-out rates\\\\n\\\\n**5. Technical and Vocational Education and Training (TVET):**\\\\n• Offers practical skills training\\\\n• Prepares youth for employment and self-employment\\\\n\\\\n**Non-Governmental Initiatives:**\\\\n• Youth leadership programmes by NGOs\\\\n• Entrepreneurship training centres\\\\n• Mentorship and internship programmes" },
      { id: "soc-st-2-s8t2-content-2", type: "info", "content": "**Skills for the 21st Century**\\\\n\\\\nTo succeed in today's world, young people need a combination of academic knowledge and practical skills.\\\\n\\\\n**Essential Skills:**\\\\n\\\\n**1. Digital Skills:** Computer literacy, coding, social media management, online research\\\\n\\\\n**2. Communication Skills:** Speaking clearly, writing well, listening actively\\\\n\\\\n**3. Critical Thinking:** Analysing information, solving problems, making decisions\\\\n\\\\n**4. Creativity and Innovation:** Thinking of new ideas, finding better ways to do things\\\\n\\\\n**5. Collaboration:** Working in teams, respecting diverse perspectives\\\\n\\\\n**6. Financial Literacy:** Managing money, budgeting, saving, investing\\\\n\\\\n**7. Entrepreneurial Skills:** Identifying opportunities, starting businesses, managing projects\\\\n\\\\n**Challenges Facing Youth Empowerment:**\\\\n• Unemployment and underemployment\\\\n• Inadequate skills training facilities\\\\n• Limited access to capital for business\\\\n• Gender inequality in opportunities\\\\n• Rural-urban disparities\\\\n\\\\n**How Youth Can Take Initiative:**\\\\n• Seek out learning opportunities online\\\\n• Join youth clubs and organisations\\\\n• Participate in volunteer work\\\\n• Develop multiple skills (not just academic)\\\\n• Network with professionals and mentors" },
      { id: "soc-st-2-s8t2-activity-1", type: "info", content: "**Activity 8.2 — Skills Inventory**\\\\n\\\\nCreate a personal skills inventory:\\\\n\\\\n1. List three skills you already have\\\\n2. List three skills you want to develop\\\\n3. How will you develop these skills? (online courses, practice, mentorship, etc.)\\\\n4. How can these skills help you contribute to national development?\\\\n\\\\nShare your inventory with a classmate and discuss how you can learn from each other." },
      { id: "soc-st-2-s8t2-exercise", type: "question", content: "Test your understanding:", exercise: { question: "Which government policy provides free secondary education to all Ghanaian students?", options: ["TVET", "Free SHS", "NABCO", "YEA"], correctIndex: 1, explanation: "The Free Senior High School (Free SHS) Policy provides free secondary education to all Ghanaian students, increasing access to education." } },
      { id: "soc-st-2-s8t2-summary", type: "info", content: "✅ **Key Takeaways: Youth Empowerment and Skills Development**\\\\n\\\\nIn this lesson, you learned about:\\\\n• Youth empowerment programmes in Ghana\\\\n• Essential skills for the 21st century\\\\n• Challenges facing youth empowerment and how to overcome them\\\\n\\\\nInvesting in skills development is the best way for young people to secure their future and contribute to national development." },
      { id: "soc-st-2-s8t2-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Youth Empowerment — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "Which agency is responsible for creating employment opportunities for Ghanaian youth?", options: ["NYA", "YEA", "FDA", "EPA"], correctIndex: 1, explanation: "The Youth Employment Agency (YEA) creates employment opportunities for young people through various modules." }, { question: "Why is digital literacy an important skill for today's youth?", options: ["It is not important", "Most jobs and opportunities now require digital skills", "Only programmers need it", "It is only for entertainment"], correctIndex: 1, explanation: "Digital literacy is essential because most jobs, education, and business opportunities now require basic digital skills." } ] } }
    ]
  },

  // ────────────────────────────────────────────────────────────────────────────
  // MODULE 9: ECONOMIC ACTIVITIES IN GHANA
  // ────────────────────────────────────────────────────────────────────────────

  {
    id: "soc-st-2-s9t1",
    title: "Types of Economic Activities",
    subject: "Social Studies",
    subjectIcon: "💼",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 1,
    estimatedMinutes: 14,
    xpReward: 35,
    prerequisites: ["soc-st-2-s8t2"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s9t1-intro", type: "info", content: "**Types of Economic Activities**\\\\n\\\\nEconomic activities are actions that involve the production, distribution, and consumption of goods and services. These activities are the foundation of any economy, providing livelihoods for people and generating wealth for the nation.\\\\n\\\\nIn this lesson, we will explore the different types of economic activities and the sectors of the Ghanaian economy." },
      { id: "soc-st-2-s9t1-content-1", type: "info", content: "**Classification of Economic Activities**\\\\n\\\\nEconomic activities are classified into three main sectors:\\\\n\\\\n**1. Primary Sector (Extractive Industries):**\\\\nInvolves extracting raw materials from nature.\\\\n• Agriculture (farming, fishing, forestry)\\\\n• Mining and quarrying (gold, bauxite, manganese, diamonds)\\\\n• Oil and gas extraction\\\\n• Forestry and logging\\\\n\\n**2. Secondary Sector (Manufacturing and Processing):**\\\\nInvolves processing raw materials into finished goods.\\\\n• Food processing\\\\n• Textile and garment manufacturing\\\\n• Wood processing and furniture making\\\\n• Cement and construction materials\\\\n• Chemical and pharmaceutical production\\\\n\\n**3. Tertiary Sector (Services):**\\\\nInvolves providing services rather than goods.\\\\n• Education\\\\n• Healthcare\\\\n• Banking and finance\\\\n• Transportation\\\\n• Tourism and hospitality\\\\n• Trade and commerce\\\\n• Information technology" },
      { id: "soc-st-2-s9t1-content-2", type: "info", content: "**Ghana's Economy — Key Sectors**\\\\n\\\\n**Agriculture:**\\\\n• Employs about 40% of Ghana's workforce\\\\n• Major crops: cocoa, maize, rice, cassava, yam, plantain\\\\n• Cocoa is Ghana's most important export crop\\\\n• Faces challenges: climate change, outdated methods, limited irrigation\\\\n\\\\n**Industry:**\\\\n• Includes manufacturing, mining, and construction\\\\n• Gold is Ghana's most valuable mineral export\\\\n• Oil and gas production began in 2010\\\\n• Manufacturing includes food processing, textiles, and cement\\\\n\\\\n**Services:**\\\\n• Fastest growing sector of the economy\\\\n• Includes banking, telecommunications, education, healthcare\\\\n• Financial technology (fintech) is rapidly growing\\\\n• Tourism is an important service sector\\\\n\\\\n**Informal Sector:**\\\\n• A significant part of Ghana's economy\\\\n• Includes small-scale traders, artisans, and service providers\\\\n• Provides employment but often lacks regulation and social protection" },
      { id: "soc-st-2-s9t1-activity-1", type: "info", content: "**Activity 9.1 — Economic Activities in My Community**\\\\n\\\\n1. Identify five economic activities in your community.\\\\n2. Classify each into primary, secondary, or tertiary sector.\\\\n3. Interview a family member or neighbour about their economic activity.\\\\n4. Present your findings to the class, highlighting how these activities contribute to the local economy." },
      { id: "soc-st-2-s9t1-exercise", type: "question", content: "Test your understanding:", exercise: { question: "Which sector of the economy involves processing raw materials into finished products?", options: ["Primary sector", "Secondary sector", "Tertiary sector", "Quaternary sector"], correctIndex: 1, explanation: "The secondary sector involves manufacturing and processing raw materials into finished goods." } },
      { id: "soc-st-2-s9t1-summary", type: "info", content: "✅ **Key Takeaways: Types of Economic Activities**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The three sectors of economic activities: primary, secondary, tertiary\\\\n• Ghana's key economic sectors and their importance\\\\n• The role of the informal sector\\\\n\\\\nUnderstanding the economy helps us make informed decisions about our careers and contributions to national development." },
      { id: "soc-st-2-s9t1-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Economic Activities — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "Mining is an example of which economic sector?", options: ["Primary", "Secondary", "Tertiary", "Formal"], correctIndex: 0, explanation: "Mining is a primary sector activity because it involves extracting raw materials from nature." }, { question: "What percentage of Ghana's workforce is employed in agriculture?", options: ["About 20%", "About 40%", "About 60%", "About 80%"], correctIndex: 1, explanation: "Agriculture employs about 40% of Ghana's workforce, making it the largest employer." } ] } }
    ]
  },

  {
    id: "soc-st-2-s9t2",
    title: "Economic Development and Challenges",
    subject: "Social Studies",
    subjectIcon: "💼",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 2,
    estimatedMinutes: 16,
    xpReward: 40,
    prerequisites: ["soc-st-2-s9t1"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s9t2-intro", type: "info", content: "**Economic Development and Challenges**\\\\n\\\\nGhana has made significant economic progress since independence, but the country still faces many challenges on the path to development. Understanding these challenges and the strategies to address them is essential for building a prosperous nation.\\\\n\\\\nIn this lesson, we will explore Ghana's economic development journey and the challenges that need to be overcome." },
      { id: "soc-st-2-s9t2-content-1", type: "info", content: "**Ghana's Economic Development Journey**\\\\n\\\\n**Independence Era (1957–1960s):**\\\\n• Kwame Nkrumah focused on industrialisation\\\\n• Built the Akosombo Dam for hydroelectric power\\\\n• Established factories and state-owned enterprises\\\\n\\\\n**Economic Decline (1970s–1980s):**\\\\n• Political instability and military coups\\\\n• Decline in cocoa prices\\\\n• Economic mismanagement\\\\n• High inflation and debt\\\\n\\\\n**Structural Adjustment (1980s–1990s):**\\\\n• IMF and World Bank structural adjustment programmes\\\\n• Economic reforms, privatisation, and liberalisation\\\\n• Return to constitutional rule in 1992\\\\n\\\\n**Recent Growth (2000s–Present):**\\\\n• Strong economic growth (averaging 5–8% annually)\\\\n• Discovery of oil and gas in 2007\\\\n• Improved infrastructure\\\\n• Ghana achieved lower-middle-income status" },
      { id: "soc-st-2-s9t2-content-2", type: "info", content: "**Current Economic Challenges**\\\\n\\\\n**1. Unemployment:**\\\\n• Particularly among youth and graduates\\\\n• Mismatch between skills and job market needs\\\\n\\\\n**2. Inflation and Cost of Living:**\\\\n• Rising prices affect purchasing power\\\\n• Impacts the most vulnerable citizens\\\\n\\\\n**3. Debt:**\\\\n• High public debt limits government spending on development\\\\n• Interest payments consume a significant portion of revenue\\\\n\\\\n**4. Dependence on Primary Exports:**\\\\n• Economy relies heavily on cocoa, gold, and oil\\\\n• Vulnerable to price fluctuations in global markets\\\\n\\\\n**5. Infrastructure Deficit:**\\\\n• Inadequate roads, electricity, water, and internet\\\\n• Constrains business and economic growth\\\\n\\\\n**6. Corruption:**\\\\n• Diverts resources from development\\\\n• Undermines trust in public institutions\\\\n\\\\n**Strategies for Economic Transformation:**\\\\n• Add value to primary products through processing\\\\n• Promote industrialisation and manufacturing\\\\n• Invest in education and skills development\\\\n• Improve infrastructure (roads, ports, energy, digital)\\\\n• Support small and medium enterprises (SMEs)\\\\n• Promote economic diversification" },
      { id: "soc-st-2-s9t2-activity-1", type: "info", content: "**Activity 9.2 — Solving Economic Challenges**\\\\n\\\\nIn groups, choose one economic challenge facing Ghana and develop a proposal to address it. Include:\\\\n\\\\n1. What is the challenge?\\\\n2. Who is most affected?\\\\n3. What are the causes?\\\\n4. What solutions do you propose?\\\\n5. Who should be responsible for implementing these solutions?\\\\n\\\\nPresent your proposal to the class." },
      { id: "soc-st-2-s9t2-exercise", type: "question", content: "Test your understanding:", exercise: { question: "What is one of Ghana's main economic challenges?", options: ["Too much industrialisation", "High unemployment among youth", "No natural resources", "Too many exports"], correctIndex: 1, explanation: "Unemployment, particularly among youth and graduates, is one of Ghana's major economic challenges." } },
      { id: "soc-st-2-s9t2-summary", type: "info", content: "✅ **Key Takeaways: Economic Development and Challenges**\\\\n\\\\nIn this lesson, you learned about:\\\\n• Ghana's economic development journey since independence\\\\n• Current economic challenges facing the country\\\\n• Strategies for economic transformation\\\\n\\\\nBuilding a prosperous Ghana requires addressing our economic challenges and leveraging our strengths." },
      { id: "soc-st-2-s9t2-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Economic Challenges — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "Why is Ghana's dependence on primary exports a challenge?", options: ["Primary exports are illegal", "Prices fluctuate in global markets and raw exports generate less value", "Ghana has no primary products", "It is not a challenge"], correctIndex: 1, explanation: "Dependence on primary exports like cocoa, gold, and oil makes the economy vulnerable to price fluctuations and generates less value than processed goods." }, { question: "What major industrial project did Nkrumah initiate for hydroelectric power?", options: ["Bui Dam", "Akosombo Dam", "Takoradi Power Plant", "Tema Oil Refinery"], correctIndex: 1, explanation: "Kwame Nkrumah built the Akosombo Dam on the Volta River to generate hydroelectric power for industrialisation." } ] } }
    ]
  },

  // ────────────────────────────────────────────────────────────────────────────
  // MODULE 10: ENTREPRENEURSHIP, WORKPLACE CULTURE AND PRODUCTIVITY
  // ────────────────────────────────────────────────────────────────────────────

  {
    id: "soc-st-2-s10t1",
    title: "Entrepreneurship and Business",
    subject: "Social Studies",
    subjectIcon: "🚀",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 2,
    estimatedMinutes: 16,
    xpReward: 40,
    prerequisites: ["soc-st-2-s9t2"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s10t1-intro", type: "info", content: "**Entrepreneurship and Business**\\\\n\\\\nEntrepreneurship is the process of starting and running a business, taking on financial risk in the hope of profit. Entrepreneurs are people who identify opportunities, gather resources, and create value.\\\\n\\\\nIn this lesson, we will explore the importance of entrepreneurship for economic development and the qualities of successful entrepreneurs." },
      { id: "soc-st-2-s10t1-content-1", type: "info", content: "**What is Entrepreneurship?**\\\\n\\\\nEntrepreneurship involves:\\\\n• Identifying a need or opportunity in the market\\\\n• Developing a product or service to meet that need\\\\n• Gathering resources (capital, labour, materials)\\\\n• Taking calculated risks\\\\n• Creating value for customers and society\\\\n\\\\n**Types of Businesses:**\\\\n\\\\n1. **Sole Proprietorship:** One person owns and runs the business\\\\n2. **Partnership:** Two or more people share ownership\\\\n3. **Limited Liability Company (LLC):** Owners have limited personal liability\\\\n4. **Corporation:** A separate legal entity owned by shareholders\\\\n5. **Cooperative:** Owned and operated by members for mutual benefit\\\\n\\\\n**Importance of Entrepreneurship:**\\\\n• Creates jobs and reduces unemployment\\\\n• Drives innovation and economic growth\\\\n• Provides goods and services to communities\\\\n• Generates tax revenue for the government\\\\n• Promotes self-reliance and reduces poverty" },
      { id: "soc-st-2-s10t1-content-2", type: "info", "content": "**Qualities of a Successful Entrepreneur**\\\\n\\\\n**1. Creativity and Innovation:** Seeing opportunities where others see problems\\\\n\\\\n**2. Self-motivation:** Being driven by internal goals, not external pressure\\\\n\\\\n**3. Risk-taking:** Willingness to take calculated risks\\\\n\\\\n**4. Resilience:** Ability to bounce back from failures and setbacks\\\\n\\\\n**5. Adaptability:** willingness to adjust to changing conditions\\\\n\\\\n**6. Vision:** Having a clear idea of what you want to achieve\\\\n\\\\n**7. Leadership:** Inspiring and managing others\\\\n\\\\n**8. Financial Management:** Understanding money, budgeting, and profit\\\\n\\\\n**9. Communication:** Clearly expressing ideas to customers, partners, and employees\\\\n\\\\n**10. Customer Focus:** Understanding and meeting customer needs\\\\n\\\\n**Examples of Ghanaian Entrepreneurs:**\\\\n• Esther Ocloo — Founder of Nkulenu Industries\\\\n• Dr. Sam Jonah — Business executive and leader\\\\n• Patricia Obo-Nai — First female CEO of Vodafone Ghana\\\\n• Ibrahim Mahama — Businessman and philanthropist" },
      { id: "soc-st-2-s10t1-activity-1", type: "info", content: "**Activity 10.1 — My Business Idea**\\\\n\\\\n1. Identify a problem in your community or school.\\\\n2. Develop a business idea that could solve this problem.\\\\n3. Write a simple business plan including:\\\\n   • What product or service you will offer\\\\n   • Who your customers will be\\\\n   • What resources you need\\\\n   • How you will make a profit\\\\n4. Present your business idea to the class." },
      { id: "soc-st-2-s10t1-exercise", type: "question", content: "Test your understanding:", exercise: { question: "What is entrepreneurship?", options: ["Working for the government", "Starting and running a business with financial risk", "Being employed by a company", "Studying business at school"], correctIndex: 1, explanation: "Entrepreneurship is the process of starting and running a business, taking on financial risk in the hope of profit." } },
      { id: "soc-st-2-s10t1-summary", type: "info", content: "✅ **Key Takeaways: Entrepreneurship and Business**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The meaning and importance of entrepreneurship\\\\n• Types of business ownership\\\\n• Qualities of successful entrepreneurs\\\\n\\\\nEntrepreneurship is a powerful tool for creating jobs, solving problems, and building wealth." },
      { id: "soc-st-2-s10t1-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Entrepreneurship — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "Which type of business is owned by one person?", options: ["Partnership", "Sole proprietorship", "Corporation", "Cooperative"], correctIndex: 1, explanation: "A sole proprietorship is owned and run by one person, who has full control and bears all the risk." }, { question: "Why is resilience important for entrepreneurs?", options: ["It is not important", "Businesses face setbacks, and resilience helps entrepreneurs recover and continue", "Resilience guarantees profit", "Only large companies need resilience"], correctIndex: 1, explanation: "Entrepreneurs face many challenges and setbacks. Resilience helps them bounce back, learn from failures, and keep going." } ] } }
    ]
  },

  {
    id: "soc-st-2-s10t2",
    title: "Workplace Culture and Productivity",
    subject: "Social Studies",
    subjectIcon: "🚀",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 2,
    estimatedMinutes: 16,
    xpReward: 40,
    prerequisites: ["soc-st-2-s10t1"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s10t2-intro", type: "info", content: "**Workplace Culture and Productivity**\\\\n\\\\nWorkplace culture refers to the shared values, attitudes, and behaviours that characterise an organisation. A positive workplace culture contributes to productivity — the efficiency with which goods and services are produced.\\\\n\\\\nIn this lesson, we will explore the elements of a positive workplace culture and how productivity can be improved." },
      { id: "soc-st-2-s10t2-content-1", type: "info", content: "**Elements of a Positive Workplace Culture**\\\\n\\\\n**1. Respect and Dignity:** All employees are treated with respect regardless of their position.\\\\n\\\\n**2. Communication:** Open and honest communication between management and staff.\\\\n\\\\n**3. Teamwork:** Collaboration and mutual support among colleagues.\\\\n\\\\n**4. Professionalism:** High standards of conduct, punctuality, and work ethic.\\\\n\\\\n**5. Safety:** A safe and healthy work environment.\\\\n\\\\n**6. Recognition:** Appreciation and reward for good work.\\\\n\\\\n**7. Growth Opportunities:** Training and career advancement opportunities.\\\\n\\\\n**8. Work-Life Balance:** Respect for employees' personal time and family responsibilities.\\\\n\\\\n**Negative Workplace Behaviours to Avoid:**\\\\n• Absenteeism and lateness\\\\n• Dishonesty and theft\\\\n• Gossip and conflict\\\\n• Discrimination and harassment\\\\n• Negligence and carelessness" },
      { id: "soc-st-2-s10t2-content-2", type: "info", content: "**Understanding and Improving Productivity**\\\\n\\\\nProductivity is the measure of output per unit of input (labour, capital, materials). Higher productivity means producing more with the same resources.\\\\n\\\\n**Factors Affecting Productivity:**\\\\n\\\\n**1. Worker Skills and Motivation:**\\\\n• Well-trained and motivated workers are more productive\\\\n• Regular training and fair compensation improve performance\\\\n\\\\n**2. Technology and Equipment:**\\\\n• Modern tools and technology increase efficiency\\\\n• Regular maintenance of equipment is essential\\\\n\\\\n**3. Management and Leadership:**\\\\n• Good management organises work effectively\\\\n• Clear goals and feedback improve performance\\\\n\\\\n**4. Working Conditions:**\\\\n• Safe, comfortable work environments improve productivity\\\\n• Adequate lighting, ventilation, and facilities matter\\\\n\\\\n**5. Workplace Relationships:**\\\\n• Good relationships between workers and management boost morale\\\\n• Teamwork increases collective output\\\\n\\\\n**National Productivity:**\\\\n• Ghana's national productivity affects economic growth\\\\n• Improving productivity is essential for competing globally\\\\n• Every worker contributes to national productivity" },
      { id: "soc-st-2-s10t2-activity-1", type: "info", content: "**Activity 10.2 — Workplace Culture**\\\\n\\\\n1. Imagine you are the manager of a small business. List three things you would do to create a positive workplace culture.\\\\n2. Identify three factors that affect productivity in your school.\\\\n3. Discuss with a partner: How can students develop good work habits that will help them in future employment?" },
      { id: "soc-st-2-s10t2-exercise", type: "question", content: "Test your understanding:", exercise: { question: "What is workplace culture?", options: ["The physical building where people work", "Shared values, attitudes, and behaviours in an organisation", "The salary workers receive", "The number of employees"], correctIndex: 1, explanation: "Workplace culture refers to the shared values, attitudes, and behaviours that characterise an organisation." } },
      { id: "soc-st-2-s10t2-summary", type: "info", content: "✅ **Key Takeaways: Workplace Culture and Productivity**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The elements of a positive workplace culture\\\\n• Factors that affect productivity\\\\n• How individuals can contribute to productivity\\\\n\\\\nA positive workplace culture and high productivity are essential for individual success and national development." },
      { id: "soc-st-2-s10t2-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Workplace Culture — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "Which of the following is an element of a positive workplace culture?", options: ["Gossip and conflict", "Open communication", "Lateness", "Dishonesty"], correctIndex: 1, explanation: "Open and honest communication between management and staff is an essential element of a positive workplace culture." }, { question: "How does technology affect productivity?", options: ["It has no effect", "Modern technology increases efficiency and productivity", "Technology always reduces productivity", "Only manual work is productive"], correctIndex: 1, explanation: "Modern technology and equipment increase efficiency, allowing workers to produce more output with the same input." } ] } }
    ]
  },

  // ────────────────────────────────────────────────────────────────────────────
  // MODULE 11: CONSUMER RIGHTS, PROTECTION & RESPONSIBILITIES
  // ────────────────────────────────────────────────────────────────────────────

  {
    id: "soc-st-2-s11t1",
    title: "Consumer Rights and Protection",
    subject: "Social Studies",
    subjectIcon: "🛡️",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 2,
    estimatedMinutes: 16,
    xpReward: 40,
    prerequisites: ["soc-st-2-s10t2"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s11t1-intro", type: "info", content: "**Consumer Rights and Protection**\\\\n\\\\nEvery day, we buy goods and services — food, clothes, phone credit, transport. As consumers, we have rights that protect us from unfair practices. Consumer protection involves laws and organisations that ensure consumers are treated fairly.\\\\n\\\\nIn this lesson, we will explore consumer rights and the institutions that protect consumers in Ghana." },
      { id: "soc-st-2-s11t1-content-1", type: "info", content: "**Consumer Rights**\\\\n\\\\nThe United Nations has outlined eight basic consumer rights:\\\\n\\\\n**1. Right to Safety:** Protection against hazardous goods\\\\n**2. Right to be Informed:** Access to accurate information about products\\\\n**3. Right to Choose:** Access to a variety of products at competitive prices\\\\n**4. Right to be Heard:** Consumers' interests are represented in government policy\\\\n**5. Right to Satisfaction of Basic Needs:** Access to essential goods like food, water, shelter\\\\n**6. Right to Redress:** Compensation for faulty goods or poor services\\\\n**7. Right to Consumer Education:** Knowledge about consumer rights and responsibilities\\\\n**8. Right to a Healthy Environment:** Living and working in a safe environment\\\\n\\\\n**Consumer Responsibilities:**\\\\n• Be informed before buying\\\\n• Use products safely\\\\n• Keep receipts and records\\\\n• Report unfair practices\\\\n• Respect the rights of sellers" },
      { id: "soc-st-2-s11t1-content-2", type: "info", content: "**Consumer Protection Institutions in Ghana**\\\\n\\\\n**1. Food and Drugs Authority (FDA):**\\\\n• Regulates the manufacture, import, and sale of food, drugs, cosmetics, and medical devices\\\\n• Ensures products are safe for consumption\\\\n• Recalls unsafe products from the market\\\\n\\\\n**2. Ghana Standards Authority (GSA):**\\\\n• Sets standards for goods and services\\\\n• Tests products for quality and safety\\\\n• Issues certification marks for quality products\\\\n\\\\n**3. Consumer Protection Agency (CPA):**\\\\n• Educates consumers about their rights\\\\n• Investigates consumer complaints\\\\n• Mediates between consumers and businesses\\\\n\\\\n**4. National Communications Authority (NCA):**\\\\n• Regulates the telecommunications sector\\\\n• Protects consumers from unfair practices by phone and internet companies\\\\n\\\\n**5. Public Utilities Regulatory Commission (PURC):**\\\\n• Regulates electricity and water tariffs\\\\n• Protects consumers from unfair utility charges\\\\n\\\\n**How to Lodge a Complaint:**\\\\n1. Contact the seller first\\\\n2. If unresolved, contact the relevant regulatory body\\\\n3. Provide evidence (receipt, product, photos)\\\\n4. Follow up until the issue is resolved" },
      { id: "soc-st-2-s11t1-activity-1", type: "info", content: "**Activity 11.1 — Consumer Scenarios**\\\\n\\\\nIn groups, discuss these scenarios and identify which consumer right is being violated:\\\\n\\\\n1. A shop sells expired canned goods without warning labels.\\\\n2. A mobile phone company increases call rates without notifying customers.\\\\n3. A student buys a pen that stops working after one day, and the seller refuses a refund.\\\\n4. A company advertises medicine with false claims about its effectiveness.\\\\n\\\\nWhat should the consumer do in each case?" },
      { id: "soc-st-2-s11t1-exercise", type: "question", content: "Test your understanding:", exercise: { question: "Which agency regulates the safety of food and drugs in Ghana?", options: ["GSA", "FDA", "PURC", "NCA"], correctIndex: 1, explanation: "The Food and Drugs Authority (FDA) regulates the manufacture, import, and sale of food, drugs, cosmetics, and medical devices in Ghana." } },
      { id: "soc-st-2-s11t1-summary", type: "info", content: "✅ **Key Takeaways: Consumer Rights and Protection**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The eight basic consumer rights\\\\n• Consumer protection institutions in Ghana\\\\n• How to lodge a complaint\\\\n\\\\nKnowing your consumer rights empowers you to make informed choices and seek redress when necessary." },
      { id: "soc-st-2-s11t1-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Consumer Rights — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "What does the right to be informed mean for consumers?", options: ["Consumers must inform sellers about their needs", "Consumers have access to accurate information about products", "Only sellers need information", "Information is not important"], correctIndex: 1, explanation: "The right to be informed means consumers should have access to accurate information about products, including ingredients, prices, and expiry dates." }, { question: "Which institution regulates electricity and water tariffs in Ghana?", options: ["FDA", "GSA", "PURC", "NCA"], correctIndex: 2, explanation: "The Public Utilities Regulatory Commission (PURC) regulates electricity and water tariffs and protects consumers from unfair charges." } ] } }
    ]
  },

  {
    id: "soc-st-2-s11t2",
    title: "Consumer Rights and the Law",
    subject: "Social Studies",
    subjectIcon: "🛡️",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 2,
    estimatedMinutes: 14,
    xpReward: 35,
    prerequisites: ["soc-st-2-s11t1"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s11t2-intro", type: "info", content: "**Consumer Rights and the Law**\\\\n\\\\nConsumer rights are protected by laws in Ghana. These laws establish the legal framework for fair trade, product safety, and consumer redress. Understanding these laws helps consumers assert their rights and hold businesses accountable.\\\\n\\\\nIn this lesson, we will explore the legal framework for consumer protection in Ghana." },
      { id: "soc-st-2-s11t2-content-1", type: "info", content: "**Consumer Protection Laws in Ghana**\\\\n\\\\n**Key Legislation:**\\\\n\\\\n**1. Consumer Protection Act (2020):**\\\\n• The main law protecting consumers in Ghana\\\\n• Prohibits unfair trade practices\\\\n• Establishes the rights of consumers\\\\n• Provides for redress when rights are violated\\\\n\\\\n**2. Food and Drugs Act:**\\\\n• Regulates the manufacture and sale of food, drugs, and cosmetics\\\\n• Prohibits the sale of adulterated or expired products\\\\n\\\\n**3. Weights and Measures Act:**\\\\n• Ensures accurate measurements in trade\\\\n• Prevents cheating through false scales or measures\\\\n\\\\n**4. Sale of Goods Act:**\\\\n• Establishes rules for contracts of sale\\\\n• Implied terms about quality and fitness for purpose\\\\n\\\\n**5. Competition and Fair Trading Act:**\\\\n• Promotes competition\\\\n• Prevents monopolies and anti-competitive practices\\\\n\\\\n**6. Cyber Security Act:**\\\\n• Protects consumers in online transactions\\\\n• Addresses cybercrime and data protection" },
      { id: "soc-st-2-s11t2-content-2", type: "info", content: "**Consumer Redress Mechanisms**\\\\n\\\\nWhen a consumer's rights are violated, there are several avenues for redress:\\\\n\\\\n**1. Negotiation with the Seller:**\\\\nMany issues can be resolved by talking directly to the seller or business.\\\\n\\\\n**2. Complaint to Regulatory Body:**\\\\nIf negotiation fails, complain to the relevant regulatory body (FDA, GSA, PURC, etc.).\\\\n\\\\n**3. Alternative Dispute Resolution (ADR):**\\\\nMediation or arbitration can resolve disputes without going to court.\\\\n\\\\n**4. Small Claims Court:**\\\\nFor disputes involving smaller amounts of money, the small claims court provides a quick and affordable process.\\\\n\\\\n**5. High Court:**\\\\nFor serious cases involving large amounts, the case can be taken to the High Court.\\\\n\\\\n**Tips for Effective Complaints:**\\\\n• Keep receipts and evidence\\\\n• Write down details (date, time, what happened)\\\\n• Be polite but firm\\\\n• Know your rights before complaining\\\\n• Follow up if you don't get a response" },
      { id: "soc-st-2-s11t2-exercise", type: "question", content: "Test your understanding:", exercise: { question: "Which law is the main consumer protection legislation in Ghana?", options: ["Food and Drugs Act", "Consumer Protection Act (2020)", "Sale of Goods Act", "Weights and Measures Act"], correctIndex: 1, explanation: "The Consumer Protection Act (2020) is the main law protecting consumers in Ghana, prohibiting unfair trade practices and establishing consumer rights." } },
      { id: "soc-st-2-s11t2-summary", type: "info", content: "✅ **Key Takeaways: Consumer Rights and the Law**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The key laws that protect consumers in Ghana\\\\n• Consumer redress mechanisms\\\\n• How to make effective complaints\\\\n\\\\nThe law provides powerful tools for consumers — knowing your rights is the first step to protecting them." },
      { id: "soc-st-2-s11t2-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Consumer Law — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "What does the Weights and Measures Act regulate?", options: ["Food safety", "Accurate measurements in trade", "Telecommunications", "Drug quality"], correctIndex: 1, explanation: "The Weights and Measures Act ensures accurate measurements in trade, preventing cheating through false scales or measures." }, { question: "Which court is appropriate for resolving a small consumer dispute?", options: ["High Court", "Supreme Court", "Small Claims Court", "Traditional court"], correctIndex: 2, explanation: "The Small Claims Court provides a quick and affordable process for resolving disputes involving smaller amounts of money." } ] } }
    ]
  },

  // ────────────────────────────────────────────────────────────────────────────
  // MODULE 12: FINANCIAL LITERACY
  // ────────────────────────────────────────────────────────────────────────────

  {
    id: "soc-st-2-s12t1",
    title: "Understanding Money and Banking",
    subject: "Social Studies",
    subjectIcon: "💰",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 1,
    estimatedMinutes: 14,
    xpReward: 35,
    prerequisites: ["soc-st-2-s11t2"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s12t1-intro", type: "info", content: "**Understanding Money and Banking**\\\\n\\\\nFinancial literacy is the ability to understand and manage money effectively. It is an essential life skill that helps individuals make informed financial decisions, avoid debt traps, and build wealth over time.\\\\n\\\\nIn this lesson, we will explore the concept of money, the banking system, and how to manage personal finances." },
      { id: "soc-st-2-s12t1-content-1", type: "info", content: "**What is Money?**\\\\n\\\\nMoney is anything that is widely accepted as a medium of exchange for goods and services.\\\\n\\\\n**Functions of Money:**\\\\n1. **Medium of Exchange:** Used to buy goods and services\\\\n2. **Store of Value:** Preserves value over time\\\\n3. **Unit of Account:** Provides a standard measure of value\\\\n4. **Standard of Deferred Payment:** Used for credit and future payments\\\\n\\\\n**Types of Money:**\\\\n• **Cash:** Physical currency (coins and banknotes)\\\\n• **Bank Deposits:** Money held in bank accounts\\\\n• **Digital Money:** Mobile money, e-currency, online payments\\\\n\\\\n**History of Money in Ghana:**\\\\n• Before colonisation: Gold dust, cowrie shells, barter trade\\\\n• Colonial era: British West African currency\\\\n• Independence: Ghanaian pound (1958)\\\\n• 1965: Ghanaian cedi introduced\\\\n• 2007: New Ghana cedi (GH¢) — 1 new cedi = 10,000 old cedis" },
      { id: "soc-st-2-s12t1-content-2", type: "info", content: "**The Banking System in Ghana**\\\\n\\\\nBanks are financial institutions that accept deposits, provide loans, and offer other financial services.\\\\n\\\\n**Types of Banks in Ghana:**\\\\n\\\\n**1. Commercial Banks:**\\\\n• Accept deposits from individuals and businesses\\\\n• Provide loans and credit facilities\\\\n• Offer savings and current accounts\\\\n• Examples: GCB Bank, Ecobank, Stanbic Bank\\\\n\\\\n**2. Rural and Community Banks:**\\\\n• Serve rural communities\\\\n• Provide banking services where commercial banks are not present\\\\n\\\\n**3. Savings and Loans Companies:**\\\\n• Specialise in savings accounts and small loans\\\\n\\\\n**4. Microfinance Institutions:**\\\\n• Provide small loans to low-income individuals and small businesses\\\\n\\\\n**Bank Services:**\\\\n• Savings accounts\\\\n• Current (chequing) accounts\\\\n• Fixed deposit accounts\\\\n• Loans and mortgages\\\\n• Money transfers\\\\n• Mobile banking\\\\n• ATM services" },
      { id: "soc-st-2-s12t1-content-3", type: "info", content: "**Digital Financial Services**\\\\n\\\\n**Mobile Money (MoMo):**\\\\n• A service that allows users to store, send, and receive money using a mobile phone\\\\n• Providers: MTN MoMo, Vodafone Cash, AirtelTigo Money\\\\n• No bank account needed — only a mobile phone\\\\n\\\\n**Advantages of Mobile Money:**\\\\n• Convenient and accessible\\\\n• No need for a bank account\\\\n• Can send and receive money instantly\\\\n• Pay bills and buy goods\\\\n• Safe and secure\\\\n\\\\n**Internet Banking:**\\\\n• Access bank accounts online\\\\n• Transfer money, pay bills, check balances\\\\n\\\\n**Tips for Safe Digital Banking:**\\\\n• Never share your PIN or password\\\\n• Use strong passwords\\\\n• Beware of phishing scams\\\\n• Keep your phone secure\\\\n• Report lost phones and SIM cards immediately" },
      { id: "soc-st-2-s12t1-activity-1", type: "info", "content": "**Activity 12.1 — Understanding Banking**\\\\n\\\\n1. Visit a bank or mobile money agent in your community and find out about the services they offer.\\\\n2. Ask a parent or guardian about the importance of saving money in a bank.\\\\n3. Create a simple budget for a week, tracking how you spend money.\\\\n4. Discuss: Why is it important to save money rather than spending everything you receive?" },
      { id: "soc-st-2-s12t1-exercise", type: "question", content: "Test your understanding:", exercise: { question: "What is the name of Ghana's currency?", options: ["Ghana pound", "Cedi", "Franc", "Dollar"], correctIndex: 1, explanation: "Ghana's currency is the cedi (GH¢). The new Ghana cedi was introduced in 2007, replacing the old cedi at a rate of 1 new cedi = 10,000 old cedis." } },
      { id: "soc-st-2-s12t1-summary", type: "info", content: "✅ **Key Takeaways: Understanding Money and Banking**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The functions and types of money\\\\n• The banking system in Ghana\\\\n• Digital financial services like mobile money\\\\n\\nFinancial literacy is an essential skill for managing personal finances effectively." },
      { id: "soc-st-2-s12t1-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Money and Banking — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "Which of the following is NOT a function of money?", options: ["Medium of exchange", "Store of value", "Source of power", "Unit of account"], correctIndex: 2, explanation: "The four functions of money are: medium of exchange, store of value, unit of account, and standard of deferred payment." }, { question: "What is mobile money?", options: ["Money kept under a mattress", "A service to store, send, and receive money using a mobile phone", "A type of bank account", "A loan from a mobile phone company"], correctIndex: 1, explanation: "Mobile money (MoMo) is a service that allows users to store, send, and receive money using a mobile phone without needing a bank account." } ] } }
    ]
  },

  {
    id: "soc-st-2-s12t2",
    title: "Savings, Investment and Budgeting",
    subject: "Social Studies",
    subjectIcon: "💰",
    programme: "Both",
    unitId: "social-studies",
    difficulty: 2,
    estimatedMinutes: 16,
    xpReward: 40,
    prerequisites: ["soc-st-2-s12t1"],
    shsLevels: ["SHS 2"],
    suggestedLevel: "SHS 2",
    steps: [
      { id: "soc-st-2-s12t2-intro", type: "info", content: "**Savings, Investment and Budgeting**\\\\n\\\\nManaging money wisely involves three key activities: saving, investing, and budgeting. These skills help individuals achieve financial security, reach their goals, and build wealth over time.\\\\n\\\\nIn this lesson, we will explore the principles of saving, different investment options, and how to create and manage a budget." },
      { id: "soc-st-2-s12t2-content-1", type: "info", content: "**The Importance of Saving**\\\\n\\\\nSaving means setting aside money for future use rather than spending it immediately.\\\\n\\\\n**Why Save Money?**\\\\n• **Emergency fund:** For unexpected expenses (medical bills, repairs)\\\\n• **Future goals:** Education, business, buying a house\\\\n• **Retirement:** Financial security in old age\\\\n• **Peace of mind:** Knowing you have money set aside reduces stress\\\\n\\\\n**How to Save:**\\\\n• Pay yourself first — save before spending\\\\n• Open a savings account at a bank\\\\n• Use a susu collector or savings group\\\\n• Set a savings goal and track progress\\\\n• Save regularly, even small amounts\\\\n\\n**The Power of Compound Interest:**\\\\nWhen you save money in an interest-bearing account, your money earns interest. Over time, you also earn interest on the interest you have already earned. This is compound interest — and it can grow your savings significantly over the long term." },
      { id: "soc-st-2-s12t2-content-2", type: "info", content: "**Investment Options**\\\\n\\\\nInvestment is using money to earn more money. Different investments have different levels of risk and return.\\\\n\\\\n**Common Investment Options in Ghana:**\\\\n\\\\n**1. Savings Account:** Low risk, low return. Money is safe and accessible.\\\\n\\\\n**2. Fixed Deposit:** Higher interest than a savings account. Money is locked for a fixed period.\\\\n\\\\n**3. Treasury Bills (T-Bills):** Short-term government securities. Low risk, moderate return.\\\\n\\\\n**4. Stocks and Shares:** Buying ownership in companies. Higher risk, potentially higher return.\\\\n\\\\n**5. Mutual Funds:** Pooled money from many investors, managed by professionals. Moderate risk.\\\\n\\\\n**6. Real Estate:** Investing in land or buildings. Can generate rental income and capital appreciation.\\\\n\\\\n**7. Business:** Starting or investing in a business. High risk but potentially high return.\\\\n\\\\n**8. Pension Fund:** Long-term retirement savings. Often has tax benefits.\\\\n\\\\n**Golden Rule of Investing:** Higher potential returns come with higher risk. Never invest money you cannot afford to lose." },
      { id: "soc-st-2-s12t2-content-3", type: "info", content: "**Budgeting — Planning Your Money**\\\\n\\\\nA budget is a plan for how you will spend and save your money. It helps you control your finances and achieve your goals.\\\\n\\\\n**Steps to Create a Budget:**\\\\n\\\\n1. **Calculate Your Income:** How much money do you receive? (pocket money, allowance, earnings)\\\\n2. **List Your Expenses:** What do you spend money on? (food, transport, airtime, entertainment)\\\\n3. **Categorise Expenses:**\\\\n   • **Needs:** Essential items (food, transport to school)\\\\n   • **Wants:** Non-essential items (snacks, games, movies)\\\\n4. **Set Savings Goals:** Decide how much to save each period\\\\n5. **Track Your Spending:** Record what you actually spend\\\\n6. **Review and Adjust:** Compare actual spending to your budget and make changes\\\\n\\n**The 50/30/20 Rule:**\\\\n• 50% of income for needs\\\\n• 30% of income for wants\\\\n• 20% of income for savings and investments\\\\n\\n**Avoiding Debt Traps:**\\\\n• Only borrow what you can repay\\\\n• Avoid high-interest loans\\\\n• Read terms and conditions before borrowing\\\\n• Use credit responsibly" },
      { id: "soc-st-2-s12t2-activity-1", type: "info", content: "**Activity 12.2 — Creating a Budget**\\\\n\\\\nCreate a personal budget for one month:\\\\n\\\\n1. Estimate your income (pocket money, allowance, etc.)\\\\n2. List your expected expenses (transport, food, airtime, etc.)\\\\n3. Categorise each expense as a need or want\\\\n4. Decide how much you will save\\\\n5. Track your actual spending for one week\\\\n6. Compare actual spending to your budget\\\\n\\\\nDiscuss: What did you learn about your spending habits? What changes can you make?" },
      { id: "soc-st-2-s12t2-exercise", type: "question", content: "Test your understanding:", exercise: { question: "What does the 50/30/20 budgeting rule recommend?", options: ["50% savings, 30% needs, 20% wants", "50% needs, 30% wants, 20% savings", "50% wants, 30% savings, 20% needs", "50% tax, 30% savings, 20% needs"], correctIndex: 1, explanation: "The 50/30/20 rule recommends spending 50% of income on needs, 30% on wants, and saving/investing 20%." } },
      { id: "soc-st-2-s12t2-summary", type: "info", content: "✅ **Key Takeaways: Savings, Investment and Budgeting**\\\\n\\\\nIn this lesson, you learned about:\\\\n• The importance of saving and compound interest\\\\n• Different investment options and their risk levels\\\\n• How to create and manage a budget\\\\n• The 50/30/20 rule for financial management\\\\n\\\\nFinancial discipline is the foundation of financial freedom. Start saving and budgeting early!" },
      { id: "soc-st-2-s12t2-checkpoint", type: "checkpoint", content: "Check your understanding", checkpoint: { title: "Savings and Investment — Quick Check", passThreshold: 60, bonusXp: 20, questions: [ { question: "What is compound interest?", options: ["Interest paid only once", "Interest earned on both the original money and accumulated interest", "A fee for banking services", "Interest paid to the bank"], correctIndex: 1, explanation: "Compound interest is interest earned on both the original amount saved and the interest that has already been earned, allowing savings to grow faster over time." }, { question: "Which investment option generally has the highest risk?", options: ["Savings account", "Treasury bills", "Stocks and shares", "Fixed deposit"], correctIndex: 2, explanation: "Stocks and shares have higher risk than savings accounts, treasury bills, or fixed deposits because their value can go up or down significantly." } ] } }
    ]
  },
];
"""

# Replace placeholder with actual modules
new_content = content.replace(placeholder, modules_5_12)

with open(filepath, "w", encoding="utf-8") as f:
    f.write(new_content)

print(f"File updated successfully! {len(modules_5_12)} characters appended.")
print("All 12 modules are now complete.")
