#!/usr/bin/env python
"""
fix_empty_learningContent.py — Modifies main() in generate_coremaths.py
to create learningContent.ts from scratch when the file is empty.
"""
import re

with open('scripts/generate_coremaths.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Find the main() function and replace it
old_main_start = 'def main():'
old_main_end_match = re.search(r'\nif __name__ == "__main__":', content)
if not old_main_end_match:
    # Couldn't find __main__ guard, look for last function end
    print("ERROR: Could not find __name__ guard")
    exit(1)

old_main_end = old_main_end_match.start()

# Extract the old main function
old_main = content[content.index(old_main_start):old_main_end]

new_main = '''def main():
    filepath = "app/lib/learningContent.ts"
    header = (
        "// learningContent.ts — Auto-generated Core Maths lessons\\n"
        "// Generated by scripts/generate_coremaths.py\\n"
        "\\n"
        "export interface LessonStep {\\n"
        "  id: string;\\n"
        "  type: 'info' | 'question' | 'predict' | 'fill-blank' | 'match' | 'checkpoint';\\n"
        "  content: string;\\n"
        "  exercise?: {\\n"
        "    question: string;\\n"
        "    options: string[];\\n"
        "    correctIndex: number;\\n"
        "    explanation: string;\\n"
        "  };\\n"
        "  predict?: {\\n"
        "    pattern: string;\\n"
        "    question: string;\\n"
        "    options: string[];\\n"
        "    correctIndex: number;\\n"
        "    explanation: string;\\n"
        "  };\\n"
        "  fillBlank?: {\\n"
        "    template: string;\\n"
        "    answers: string[];\\n"
        "    hints: string[];\\n"
        "    explanation: string;\\n"
        "  };\\n"
        "  match?: {\\n"
        "    instruction: string;\\n"
        "    leftItems: string[];\\n"
        "    rightItems: string[];\\n"
        "    correctMatches: Record<string, string>;\\n"
        "    explanation: string;\\n"
        "  };\\n"
        "  checkpoint?: {\\n"
        "    title: string;\\n"
        "    questions: Array<{\\n"
        "      question: string;\\n"
        "      options: string[];\\n"
        "      correctIndex: number;\\n"
        "      explanation: string;\\n"
        "    }>;\\n"
        "    passThreshold: number;\\n"
        "    bonusXp: number;\\n"
        "  };\\n"
        "}\\n"
        "\\n"
        "export interface Lesson {\\n"
        "  id: string;\\n"
        "  title: string;\\n"
        "  subject: string;\\n"
        "  subjectIcon: string;\\n"
        "  programme: string;\\n"
        "  difficulty: number;\\n"
        "  estimatedMinutes: number;\\n"
        "  xpReward: number;\\n"
        "  unitId: string;\\n"
        "  prerequisites: string[];\\n"
        "  shsLevels: string[];\\n"
        "  suggestedLevel: string;\\n"
        "  steps: LessonStep[];\\n"
        "  checkpoints?: string[];\\n"
        "}\\n"
        "\\n"
        "export interface Unit {\\n"
        "  id: string;\\n"
        "  title: string;\\n"
        "  subtitle: string;\\n"
        "  icon: string;\\n"
        "  colour: string;\\n"
        "}\\n"
        "\\n"
        "// ═══════════════════════════════════════════════════════════════════\\n"
        "//  SHARED LESSONS — All 45 Core Mathematics lessons\\n"
        "// ═══════════════════════════════════════════════════════════════════\\n"
        "\\n"
        "export const SHARED_LESSONS: Lesson[] = [\\n"
    )

    footer = (
        "];\\n"
        "\\n"
        "// ═══════════════════════════════════════════════════════════════════\\n"
        "//  SHARED UNITS — Core Mathematics unit definition\\n"
        "// ═══════════════════════════════════════════════════════════════════\\n"
        "\\n"
        "export const SHARED_UNITS: Unit[] = [\\n"
        "  {\\n"
        "    id: 'core-maths',\\n"
        "    title: 'Core Mathematics',\\n"
        "    subtitle: 'WASSCE Core Maths — All 9 modules',\\n"
        "    icon: '\\\\U0001f522',\\n"
        "    colour: 'from-yellow-500/20 to-amber-500/20',\\n"
        "  },\\n"
        "];\\n"
        "\\n"
    )

    # Generate lesson content
    lessons_str = "\\\\n\\\\n".join(make_lesson(l) for l in ALL_LESSONS)

    new_lessons_block = (
        "  //  CORE MATHEMATICS \\u2014 9 Modules \\u00d7 5 Topics = 45 Lessons\\\\n"
        "  //  Generated by scripts/generate_coremaths.py\\\\n"
        f"{{lessons_str}}\\\\n"
    )

    # Check if file exists and has content
    import os
    if os.path.exists(filepath) and os.path.getsize(filepath) > 0:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        cm_start = content.find("//  CORE MATHEMATICS")
        if cm_start < 0:
            print("ERROR: Could not find '//  CORE MATHEMATICS' marker in learningContent.ts")
            print("Looking for alternative markers...")
            alt = content.find("coremath-1")
            if alt >= 0:
                line_start = content.rfind("\\\\n", 0, alt) + 1
                cm_start = line_start
                print(f"Found 'coremath-1' at position {alt}, using line start {line_start}")
            else:
                print("ERROR: No existing Core Maths lessons found. File may be corrupted.")
                return

        search_from = cm_start + 50
        next_subject = content.find("\\\\n  //  ", search_from)
        if next_subject < 0:
            cm_end = content.find("];", search_from)
            if cm_end < 0:
                print("ERROR: Could not find end of Core Maths section")
                return
            cm_end_line = cm_end + 2
        else:
            cm_end_line = next_subject

        new_content = content[:cm_start] + new_lessons_block + "\\\\n" + content[cm_end_line:]

        # Update the SHARED_UNITS entry for core-maths
        unit_idx = content.find("id: 'core-maths'")
        if unit_idx >= 0:
            lessons_arr_start = content.find("lessons:", unit_idx)
            if lessons_arr_start >= 0:
                arr_start = content.find("[", lessons_arr_start)
                arr_end = content.find("]", arr_start)
                if arr_start >= 0 and arr_end >= 0:
                    lesson_ids = [l["id"] for l in ALL_LESSONS]
                    lesson_ids_str = ", ".join(f"'{lid}'" for lid in lesson_ids)
                    new_arr = f"[{{lesson_ids_str}}]"
                    idx_in_new = new_content.find("id: 'core-maths'")
                    if idx_in_new >= 0:
                        arr_s = new_content.find("[", new_content.find("lessons:", idx_in_new))
                        arr_e = new_content.find("]", arr_s)
                        if arr_s >= 0 and arr_e >= 0:
                            new_content = new_content[:arr_s] + new_arr + new_content[arr_e+1:]

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(new_content)

        print(f"\\\\u2705 Generated {len(ALL_LESSONS)} lessons and updated {filepath}")
        print(f"   File size: {len(new_content)} chars")
    else:
        # File is empty or doesn't exist — create from scratch
        print("File is empty or missing. Creating from scratch...")
        lesson_ids = [l["id"] for l in ALL_LESSONS]
        lesson_ids_str = ", ".join(f"'{lid}'" for lid in lesson_ids)

        full_content = (
            header
            + new_lessons_block
            + footer
        )

        # Insert lesson IDs into the SHARED_UNITS entry
        full_content = full_content.replace(
            "  },\\\\n];",
            f"    lessons: [{{lesson_ids_str}}],\\\\n  }},\\\\n];"
        )

        # Remove the duplicate ];/; from footer
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(full_content)

        print(f"\\\\u2705 Created {filepath} from scratch with {len(ALL_LESSONS)} lessons")
        print(f"   File size: {len(full_content)} chars")
'''

content = content.replace(old_main, new_main, 1)

with open('scripts/generate_coremaths.py', 'w', encoding='utf-8') as f:
    f.write(content)

# Verify syntax
import ast
try:
    ast.parse(content)
    print("SUCCESS: generate_coremaths.py updated and syntax valid")
except SyntaxError as e:
    print(f"ERROR: Syntax error at line {e.lineno}: {e.msg}")
