"""
integrate_science.py
Integrates the General Science content into learningContent.ts
"""

FILE = 'smarttrack-frontend/app/lib/learningContent.ts'

with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

changes = 0

# 1. Add import after the header and before types
old_header = """ * Core Mathematics lessons are auto-generated by:
 *   scripts/generate_all_coremaths.py
 */

// -- Types"""

new_header = """ * Core Mathematics lessons are auto-generated by:
 *   scripts/generate_all_coremaths.py
 *
 * General Science content is generated from Ministry of Education
 * SHS Year 1 textbooks by scripts/generate_science_content.py
 */

import { GENERAL_SCIENCE_LESSONS, GENERAL_SCIENCE_UNIT } from './generalScienceContent';

// -- Types"""

if "GENERAL_SCIENCE_LESSONS" not in content:
    content = content.replace(old_header, new_header)
    print("ADDED import")
    changes += 1
else:
    print("SKIP import - already exists")

# 2. Add GENERAL_SCIENCE_LESSONS to ALL_LESSONS array
old_end = "//  Generated by scripts/generate_all_coremaths.py\n];"
new_end = "//  Generated by scripts/generate_all_coremaths.py\n  ...GENERAL_SCIENCE_LESSONS,\n];"

if old_end in content:
    content = content.replace(old_end, new_end)
    print("ADDED GENERAL_SCIENCE_LESSONS to ALL_LESSONS")
    changes += 1
else:
    print("SKIP ALL_LESSONS - pattern not found (maybe already added)")

# 3. Add GENERAL_SCIENCE_UNIT to UNIT_MAP
old_unit_map_end = """  'social-studies': {
    id: 'social-studies',
    title: 'Social Studies',
    subtitle: 'History, Geography & Governance',
    colour: 'from-orange-500/20 via-amber-500/20 to-yellow-500/20',
    icon: '\U0001f30d',
  },
};"""

new_unit_map_end = """  'social-studies': {
    id: 'social-studies',
    title: 'Social Studies',
    subtitle: 'History, Geography & Governance',
    colour: 'from-orange-500/20 via-amber-500/20 to-yellow-500/20',
    icon: '\U0001f30d',
  },
  'general-science': GENERAL_SCIENCE_UNIT,
};"""

if old_unit_map_end in content and "'general-science'" not in content:
    content = content.replace(old_unit_map_end, new_unit_map_end)
    print("ADDED GENERAL_SCIENCE_UNIT to UNIT_MAP")
    changes += 1
else:
    print("SKIP UNIT_MAP - pattern not found or already added")

# Write back if changes were made
if changes > 0:
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"\nDone! {changes} change(s) made to learningContent.ts.")
else:
    print("\nNo changes needed.")
