"""Add image_url field to questions table

Revision ID: 95d6d20853f2
Revises: a43e60ab315f
Create Date: 2026-06-10 16:22:05.085129
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '95d6d20853f2'
down_revision: Union[str, Sequence[str]] = ('a43e60ab315f', 'd1a2onboarding')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'image_url')
    # ### end Alembic commands ###
