"""add_arena_tier_fields_and_psychometric_cards

Revision ID: a43e60ab315f
Revises: d1a2onboarding
Create Date: 2026-06-04 00:52:56.222290
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a43e60ab315f'
down_revision: Union[str, None] = 'd1a2onboarding'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psychometric_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=50), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('trait_mapping', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psychometric_cards_card_id'), 'psychometric_cards', ['card_id'], unique=True)
    op.create_index(op.f('ix_psychometric_cards_id'), 'psychometric_cards', ['id'], unique=False)
    op.create_index(op.f('ix_behavioral_profiles_user_id'), 'behavioral_profiles', ['user_id'], unique=False)
    op.add_column('questions', sa.Column('arena', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('difficulty_tier', sa.String(length=20), nullable=True))
    op.add_column('questions', sa.Column('shs_levels', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('template_id', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.alter_column('questions', 'question',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.create_index(op.f('ix_questions_arena'), 'questions', ['arena'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_arena'), table_name='questions')
    op.alter_column('questions', 'question',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'template_id')
    op.drop_column('questions', 'shs_levels')
    op.drop_column('questions', 'difficulty_tier')
    op.drop_column('questions', 'arena')
    op.drop_index(op.f('ix_behavioral_profiles_user_id'), table_name='behavioral_profiles')
    op.drop_index(op.f('ix_psychometric_cards_id'), table_name='psychometric_cards')
    op.drop_index(op.f('ix_psychometric_cards_card_id'), table_name='psychometric_cards')
    op.drop_table('psychometric_cards')
    # ### end Alembic commands ###
