/**
 * generalScienceContent.ts
 * ──────────────────────────
 * General Science Year 1 — 9 interactive sessions generated from
 * the Ministry of Education SHS curriculum.
 *
 * Auto-generated by scripts/generate_science_content.py
 * Do not edit directly — re-run the generator instead.
 */

import type { Lesson } from './learningContent';

export const GENERAL_SCIENCE_UNIT = {
  id: 'general-science',
  title: 'General Science Year 1',
  subtitle: '🔬 Foundation scientists — explore the world around you',
  colour: 'from-cyan-500/20 to-blue-500/20',
  icon: '🔬',
};

export const GENERAL_SCIENCE_LESSONS: Lesson[] = [
  {
    id: "gen-sci-s1",
    title: "Understanding Science — The Scientific Method",
    subject: "General Science",
    subjectIcon: "🔬",
    programme: "Science" as const,
    difficulty: 1,
    estimatedMinutes: 12,
    xpReward: 30,
    unitId: "general-science",
    prerequisites: [],
    shsLevels: ["SHS 1"],
    suggestedLevel: "SHS 1",
    steps: [
      {
        id: "gen-sci-s1-0",
        type: "info" as const,
        content:
          "What is Science?\n\nScience comes from the Latin word 'scientia', meaning knowledge. It is both:\n\n\u2192 A body of knowledge about the natural world\n\u2192 A process for discovering new knowledge\n\n**Core Characteristics of Science:**\n\n\ud83d\udd2c **Empirical** \u2014 Based on observation and data, not just opinion\n\ud83d\udcca **Systematic** \u2014 Follows an organised approach with clear steps\n\ud83d\udd04 **Reproducible** \u2014 Results can be repeated by other scientists\n\ud83d\udcdd **Tentative** \u2014 Knowledge can change with new evidence\n\ud83c\udfaf **Predictable** \u2014 Can make accurate forecasts\n\nDid you know? The word 'science' wasn't always used. Before the 19th century, it was called 'natural philosophy'!",
      },
      {
        id: "gen-sci-s1-1",
        type: "predict" as const,
        content:
          "What do you call this process that scientists follow?",
        predict: {
          pattern: "Observation \u2192 Question \u2192 Hypothesis \u2192 Experiment \u2192 Analysis \u2192 Conclusion",
          question: "What do you call this process that scientists follow?",
          options: ["The Scientific Method", "The Laboratory Process", "The Theory of Everything", "The Natural Cycle"],
          correctIndex: 0,
          explanation: "This is the **Scientific Method**! It's the systematic approach scientists use to investigate phenomena, acquire new knowledge, and solve problems.",
        },
      },
      {
        id: "gen-sci-s1-2",
        type: "info" as const,
        content:
          "**The Scientific Method \u2014 Step by Step**\n\n1\ufe0f\u20e3 **Observation** \u2014 Notice something interesting (e.g., 'Plants grow towards sunlight')\n\n2\ufe0f\u20e3 **Question** \u2014 Ask why or how it happens ('Why do plants grow towards light?')\n\n3\ufe0f\u20e3 **Hypothesis** \u2014 Make an educated guess ('Plants grow towards light to maximise photosynthesis')\n\n4\ufe0f\u20e3 **Experiment** \u2014 Design and conduct a test (Grow plants with light on one side only)\n\n5\ufe0f\u20e3 **Analysis** \u2014 Examine your results (Measure and compare plant growth)\n\n6\ufe0f\u20e3 **Conclusion** \u2014 Was your hypothesis supported? (Yes \u2014 plants do bend towards light!)\n\n> **SHS 1 Tip:** In WASSCE, you will often be asked to identify which step of the scientific method is being described in a scenario.",
      },
      {
        id: "gen-sci-s1-3",
        type: "question" as const,
        content:
          "A student notices that salt dissolves faster in hot water than cold water. What is the FIRST step of the scientific method they should take?",
        exercise: {
          question: "A student notices that salt dissolves faster in hot water than cold water. What is the FIRST step of the scientific method they should take?",
          options: ["Conduct an experiment", "Make an observation", "Draw a conclusion", "Form a hypothesis"],
          correctIndex: 1,
          explanation: "The first step is always **observation** \u2014 noticing that something is happening. In this case, the student has already observed that salt dissolves faster in hot water.",
        },
      },
      {
        id: "gen-sci-s1-4",
        type: "info" as const,
        content:
          "**Science in Everyday Life**\n\nScience is not just for laboratories \u2014 it's all around us!\n\n\ud83c\udfe0 **At Home:** Cooking is chemistry! When you bake bread, yeast causes fermentation. When you fry an egg, proteins denature.\n\n\ud83c\udfe5 **In Medicine:** Scientists developed COVID-19 vaccines using the scientific method \u2014 testing on thousands of volunteers to ensure safety.\n\n\ud83c\udf3e **In Agriculture:** Farmers test different fertilisers on crops to see which produces the best yield.\n\n\ud83c\udfed **In Industry:** Engineers use scientific principles to design safer cars, cleaner energy, and faster computers.\n\n**Key Terms to Remember:**\n\u2022 **Hypothesis:** A testable prediction\n\u2022 **Variable:** Something that can change in an experiment\n\u2022 **Control:** A standard for comparison\n\u2022 **Theory:** A well-tested explanation for a wide range of observations",
      },
      {
        id: "gen-sci-s1-5",
        type: "question" as const,
        content:
          "Which characteristic of science means that scientific knowledge can change when new evidence emerges?",
        exercise: {
          question: "Which characteristic of science means that scientific knowledge can change when new evidence emerges?",
          options: ["Empirical", "Tentative", "Reproducible", "Systematic"],
          correctIndex: 1,
          explanation: "Science is **tentative** \u2014 meaning it is open to revision. That's why textbooks get updated! When new evidence challenges old ideas, science changes. This is a strength, not a weakness!",
        },
      },
      {
        id: "gen-sci-s1-6",
        type: "checkpoint" as const,
        content:
          "Scientific Method Mastery",
        checkpoint: {
          title: "Scientific Method Mastery",
          passThreshold: 2,
          bonusXp: 15,
          questions: [
            {
              question: "What is a hypothesis?",
              options: ["A proven fact", "A testable prediction", "The final conclusion", "An observation"],
              correctIndex: 1,
              explanation: "A hypothesis is a testable prediction that can be supported or rejected through experimentation.",
            },
            {
              question: "Why is reproducibility important in science?",
              options: ["It makes experiments faster", "It confirms results are reliable", "It saves money on equipment", "It is only needed in chemistry"],
              correctIndex: 1,
              explanation: "Reproducibility ensures that results are reliable and not just a one-time accident. If other scientists can repeat the experiment and get the same results, the findings are trustworthy.",
            },
            {
              question: "Which step comes AFTER forming a hypothesis?",
              options: ["Making observations", "Drawing conclusions", "Conducting an experiment", "Asking a question"],
              correctIndex: 2,
              explanation: "After forming a hypothesis, the next step is to **conduct an experiment** to test whether the hypothesis is supported.",
            },
          ],
        },
      },
    ],
  },
  {
    id: "gen-sci-s2",
    title: "Exploring Materials — Metals, Non-metals and Bonding",
    subject: "General Science",
    subjectIcon: "⚗️",
    programme: "Science" as const,
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 35,
    unitId: "general-science",
    prerequisites: [],
    shsLevels: ["SHS 1"],
    suggestedLevel: "SHS 1",
    steps: [
      {
        id: "gen-sci-s2-0",
        type: "info" as const,
        content:
          "**Classifying Solids**\n\nAll solids can be classified into three main groups:\n\n**\ud83e\udd47 Metals** \u2014 Hard, shiny, good conductors of heat and electricity\n\u2192 Examples: Iron (Fe), Copper (Cu), Gold (Au), Aluminium (Al)\n\n**\ud83d\udc8e Non-metals** \u2014 Usually dull, brittle, poor conductors\n\u2192 Examples: Oxygen (O), Carbon (C), Sulfur (S), Nitrogen (N)\n\n**\ud83d\udd36 Semi-metals (Metalloids)** \u2014 Have properties of both\n\u2192 Examples: Silicon (Si), Germanium (Ge)\n\n**Properties of Metals:**\n\u2022 **Malleable** \u2014 Can be hammered into shape\n\u2022 **Ductile** \u2014 Can be drawn into wires\n\u2022 **Lustrous** \u2014 Shiny when polished\n\u2022 **Good conductors** \u2014 Heat and electricity flow easily\n\nDid you know? Mercury is the only metal that is liquid at room temperature!",
      },
      {
        id: "gen-sci-s2-1",
        type: "predict" as const,
        content:
          "Silicon is used in computer chips. What type of solid is it?",
        predict: {
          pattern: `Gold → Shiny, Malleable, Conducts electricity
Sulfur → Dull, Brittle, Does not conduct
Silicon → Somewhat shiny, Semi-conductor`,
          question: "Silicon is used in computer chips. What type of solid is it?",
          options: ["Metal", "Non-metal", "Semi-metal (Metalloid)", "Alloy"],
          correctIndex: 2,
          explanation: "Silicon is a **semi-metal (metalloid)**. It has some properties of metals (slight shine, can conduct electricity under certain conditions) and some of non-metals. This is why it's perfect for computer chips!",
        },
      },
      {
        id: "gen-sci-s2-2",
        type: "info" as const,
        content:
          "**The Periodic Table**\n\nThe periodic table organises all known elements.\n\n**Key features:**\n\u2022 **Groups** \u2014 Vertical columns (1-18). Elements in the same group have similar properties.\n\u2022 **Periods** \u2014 Horizontal rows (1-7). Elements in the same period have the same number of electron shells.\n\n**First 20 Elements \u2014 You Must Know These!**\n\nH (1) \u2192 Hydrogen    He (2) \u2192 Helium\nLi (3) \u2192 Lithium     Be (4) \u2192 Beryllium\nB (5) \u2192 Boron        C (6) \u2192 Carbon\nN (7) \u2192 Nitrogen     O (8) \u2192 Oxygen\nF (9) \u2192 Fluorine     Ne (10) \u2192 Neon\nNa (11) \u2192 Sodium     Mg (12) \u2192 Magnesium\nAl (13) \u2192 Aluminium  Si (14) \u2192 Silicon\nP (15) \u2192 Phosphorus  S (16) \u2192 Sulfur\nCl (17) \u2192 Chlorine   Ar (18) \u2192 Argon\nK (19) \u2192 Potassium   Ca (20) \u2192 Calcium\n\n> **Valence Electrons:** The electrons in the outermost shell. They determine how an element will react with others.",
      },
      {
        id: "gen-sci-s2-3",
        type: "question" as const,
        content:
          "How many electrons does a neutral atom of Oxygen (O, atomic number 8) have?",
        exercise: {
          question: "How many electrons does a neutral atom of Oxygen (O, atomic number 8) have?",
          options: ["4", "6", "8", "16"],
          correctIndex: 2,
          explanation: "A neutral atom has the same number of electrons as protons. Oxygen has atomic number 8, so it has 8 protons and **8 electrons**. Its electron arrangement is 2,6.",
        },
      },
      {
        id: "gen-sci-s2-4",
        type: "info" as const,
        content:
          "**Chemical Bonding \u2014 How Atoms Combine**\n\n**\ud83d\udd17 Ionic Bonding** (Metal + Non-metal)\n\u2022 Electrons are **transferred** from metal to non-metal\n\u2022 Forms positive and negative ions that attract\n\u2022 Example: NaCl (Sodium Chloride \u2014 table salt!)\n\u2192 Sodium gives 1 electron to Chlorine\n\n**\ud83d\udd17 Covalent Bonding** (Non-metal + Non-metal)\n\u2022 Electrons are **shared** between atoms\n\u2022 Forms molecules\n\u2022 Example: H\u2082O (Water)\n\u2192 Oxygen shares electrons with 2 Hydrogen atoms\n\n**How to Name Binary Compounds:**\n\u2022 Metal + Non-metal \u2192 'ide' ending\n\u2022 NaCl = Sodium Chloride\n\u2022 MgO = Magnesium Oxide\n\u2022 CaCl\u2082 = Calcium Chloride\n\n**WASSCE Tip:** The 'ide' ending tells you the compound has only TWO elements!",
      },
      {
        id: "gen-sci-s2-5",
        type: "question" as const,
        content:
          "What type of bond forms between Sodium (a metal) and Chlorine (a non-metal)?",
        exercise: {
          question: "What type of bond forms between Sodium (a metal) and Chlorine (a non-metal)?",
          options: ["Covalent bond", "Ionic bond", "Metallic bond", "Hydrogen bond"],
          correctIndex: 1,
          explanation: "When a **metal** (Sodium) bonds with a **non-metal** (Chlorine), they form an **ionic bond**. Sodium transfers its valence electron to Chlorine, creating positive Na\u207a and negative Cl\u207b ions that attract each other.",
        },
      },
      {
        id: "gen-sci-s2-6",
        type: "checkpoint" as const,
        content:
          "Materials Mastery",
        checkpoint: {
          title: "Materials Mastery",
          passThreshold: 2,
          bonusXp: 15,
          questions: [
            {
              question: "Which of these is a property of metals?",
              options: ["Brittle", "Malleable", "Dull", "Poor conductor"],
              correctIndex: 1,
              explanation: "Metals are **malleable** (can be hammered into shape), ductile, lustrous, and good conductors of heat and electricity.",
            },
            {
              question: "How many valence electrons does Carbon (C, atomic number 6) have?",
              options: ["2", "4", "6", "8"],
              correctIndex: 1,
              explanation: "Carbon has electron arrangement 2,4. So it has **4 valence electrons** in its outermost shell. This is why carbon can form 4 bonds \u2014 it's the basis of organic chemistry!",
            },
            {
              question: "What is the correct name for the compound MgO?",
              options: ["Magnesium Oxygen", "Magnesium Oxide", "Magnesium Dioxide", "Magnesium(I) Oxide"],
              correctIndex: 1,
              explanation: "Mg is Magnesium, O is Oxygen. Since it has two elements, the name ends in 'ide' \u2014 **Magnesium Oxide**.",
            },
          ],
        },
      },
    ],
  },
  {
    id: "gen-sci-s3",
    title: "Diffusion and Osmosis — Movement of Particles",
    subject: "General Science",
    subjectIcon: "💧",
    programme: "Science" as const,
    difficulty: 2,
    estimatedMinutes: 12,
    xpReward: 30,
    unitId: "general-science",
    prerequisites: [],
    shsLevels: ["SHS 1"],
    suggestedLevel: "SHS 1",
    steps: [
      {
        id: "gen-sci-s3-0",
        type: "info" as const,
        content:
          "**Diffusion \u2014 Particles on the Move**\n\nDiffusion is the movement of particles from an area of **high concentration** to an area of **low concentration**.\n\n\u2192 Particles spread out until they are evenly distributed\n\u2192 It happens in liquids and gases\n\u2192 NO energy is needed (it's passive)\n\n**Real-life Examples:**\n\u2022 \ud83c\udf38 Perfume spreading across a room\n\u2022 \ud83e\uded6 Tea bag colouring water\n\u2022 \ud83c\udf73 Smell of cooking food reaching your nose\n\u2022 \ud83d\udca8 Oxygen moving from lungs into blood\n\n**Factors that affect diffusion rate:**\n\u2022 Temperature \u2191 \u2192 Diffusion faster\n\u2022 Concentration difference \u2191 \u2192 Diffusion faster\n\u2022 Particle size \u2193 \u2192 Diffusion faster\n\u2022 Medium \u2014 Gas diffuses faster than liquid\n\nDid you know? Diffusion in gases is about 10,000 times faster than in liquids!",
      },
      {
        id: "gen-sci-s3-1",
        type: "predict" as const,
        content:
          "What process is causing the ink to spread?",
        predict: {
          pattern: `A drop of blue ink is placed in a glass of water.
After 1 minute: Blue colour near the drop
After 10 minutes: Blue colour spreading
After 1 hour: Water is evenly light blue`,
          question: "What process is causing the ink to spread?",
          options: ["Osmosis", "Active transport", "Diffusion", "Evaporation"],
          correctIndex: 2,
          explanation: "This is **diffusion**! The ink particles move from an area of high concentration (near the drop) to areas of low concentration (the rest of the water) until they are evenly distributed.",
        },
      },
      {
        id: "gen-sci-s3-2",
        type: "info" as const,
        content:
          "**Osmosis \u2014 Water's Special Journey**\n\nOsmosis is a **special type of diffusion** \u2014 it's the movement of **water molecules** across a **selectively permeable membrane**.\n\n\ud83d\udd11 **Key points:**\n\u2022 Only WATER molecules move\n\u2022 Water moves from **dilute** (more water) to **concentrated** (less water)\n\u2022 The membrane lets water through but blocks larger solute particles\n\n**\ud83c\udf31 In Plants:**\n\u2022 Root hairs absorb water from soil by osmosis\n\u2022 Water moves up the plant through xylem vessels\n\u2022 This is how plants stay hydrated and transport nutrients!\n\n**\ud83e\uddc2 In Food Preservation:**\n\u2022 Salt draws water out of bacteria (osmosis!) \u2014 killing them\n\u2022 This is why salted fish and pickled vegetables last longer\n\n**Important Terms:**\n\u2022 **Selectively permeable membrane** \u2014 Only lets some substances through\n\u2022 **Dilute solution** \u2014 Has more water, less solute\n\u2022 **Concentrated solution** \u2014 Has less water, more solute",
      },
      {
        id: "gen-sci-s3-3",
        type: "question" as const,
        content:
          "A potato strip is placed in salt water. After 30 minutes, it becomes soft and shrinks. What happened?",
        exercise: {
          question: "A potato strip is placed in salt water. After 30 minutes, it becomes soft and shrinks. What happened?",
          options: ["Salt entered the potato by diffusion", "Water left the potato by osmosis", "The salt dissolved the potato", "Air entered the potato cells"],
          correctIndex: 1,
          explanation: "Water moved **out** of the potato cells by **osmosis**! The salt water outside is more concentrated (less water), so water from inside the potato moves out through the cell membrane, causing the potato to shrink and become soft.",
        },
      },
      {
        id: "gen-sci-s3-4",
        type: "info" as const,
        content:
          "**Active Transport \u2014 Moving Against the Flow**\n\nSometimes cells need to move substances from **low to high concentration** (the opposite of diffusion). This is called **active transport**.\n\n\u26a1 **Requires ENERGY** (ATP)\n\u26f0\ufe0f **Moves against the concentration gradient**\n\n**Examples in living things:**\n\u2022 \ud83c\udf31 Plant roots absorbing mineral ions from soil (soil has few, roots need many!)\n\u2022 \ud83e\udec1 Kidney cells reabsorbing useful substances from urine back into blood\n\n**Comparison Summary:**\n\n| Process | Direction | Needs Energy? | Membrane? |\n|---------|-----------|--------------|-----------|\n| Diffusion | High \u2192 Low | No | Not needed |\n| Osmosis | High water \u2192 Low water | No | Yes |\n| Active Transport | Low \u2192 High | Yes | Yes |\n\n> **SHS 1 Tip:** WASSCE often asks you to compare these three processes!",
      },
      {
        id: "gen-sci-s3-5",
        type: "question" as const,
        content:
          "What is the MAIN difference between osmosis and active transport?",
        exercise: {
          question: "What is the MAIN difference between osmosis and active transport?",
          options: ["Osmosis needs energy, active transport does not", "Osmosis is only in plants, active transport is only in animals", "Osmosis is passive (no energy), active transport requires energy", "There is no difference \u2014 they are the same process"],
          correctIndex: 2,
          explanation: "**Osmosis** is a passive process (no energy needed) where water moves across a membrane. **Active transport** requires energy (ATP) to move substances against the concentration gradient \u2014 from low to high concentration.",
        },
      },
      {
        id: "gen-sci-s3-6",
        type: "checkpoint" as const,
        content:
          "Diffusion & Osmosis Mastery",
        checkpoint: {
          title: "Diffusion & Osmosis Mastery",
          passThreshold: 2,
          bonusXp: 15,
          questions: [
            {
              question: "Which factor INCREASES the rate of diffusion?",
              options: ["Lower temperature", "Larger particle size", "Higher temperature", "Solid medium"],
              correctIndex: 2,
              explanation: "Higher temperature gives particles more energy, making them move faster \u2014 this **increases** the rate of diffusion!",
            },
            {
              question: "A selectively permeable membrane allows:",
              options: ["Only water to pass through", "All substances to pass through", "Only some substances to pass through", "No substances to pass through"],
              correctIndex: 2,
              explanation: "A **selectively permeable** membrane allows **only some substances** to pass through while blocking others. For example, it lets water through but not large solute molecules.",
            },
            {
              question: "Plant roots absorb water from soil by which process?",
              options: ["Active transport", "Diffusion", "Osmosis", "Transpiration"],
              correctIndex: 2,
              explanation: "Plant roots absorb water from soil by **osmosis**. The soil water is more dilute (has more water) than the root cell sap, so water moves into the roots.",
            },
          ],
        },
      },
    ],
  },
  {
    id: "gen-sci-s4",
    title: "Reproduction in Plants and Humans",
    subject: "General Science",
    subjectIcon: "🌱",
    programme: "Science" as const,
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 35,
    unitId: "general-science",
    prerequisites: [],
    shsLevels: ["SHS 1"],
    suggestedLevel: "SHS 1",
    steps: [
      {
        id: "gen-sci-s4-0",
        type: "info" as const,
        content:
          "**Reproduction in Plants**\n\nPlants can reproduce in TWO ways:\n\n**\ud83c\udf38 Sexual Reproduction** \u2014 Involves flowers\n\u2192 Male part (stamen) produces pollen\n\u2192 Female part (carpel/pistil) contains ovules\n\u2192 Pollination + Fertilisation \u2192 Seed + Fruit\n\n**\ud83c\udf3f Asexual Reproduction (Vegetative Propagation)** \u2014 No flowers needed!\n\u2022 **Runners** \u2014 Strawberry plants send out horizontal stems\n\u2022 **Rhizomes** \u2014 Ginger grows underground stems\n\u2022 **Bulbs** \u2014 Onions and garlic store food in underground leaves\n\u2022 **Tubers** \u2014 Potatoes grow from underground stems\n\n**Artificial Propagation (Humans helping):**\n\u2702\ufe0f **Cuttings** \u2014 Cut a stem, plant it, it grows roots\n\ud83c\udf33 **Grafting** \u2014 Join one plant to another\n\ud83e\uddea **Tissue culture** \u2014 Grow new plants from tiny tissue samples\n\nDid you know? A single potato tuber can produce dozens of new potato plants!",
      },
      {
        id: "gen-sci-s4-1",
        type: "predict" as const,
        content:
          "What is missing from this plant life cycle?",
        predict: {
          pattern: "Flower \u2192 Pollination \u2192 Fertilisation \u2192 Seed \u2192 Germination \u2192 New Plant",
          question: "What is missing from this plant life cycle?",
          options: ["Photosynthesis", "Fruit formation", "Respiration", "Transpiration"],
          correctIndex: 1,
          explanation: "After fertilisation, the ovary develops into a **fruit** that protects the seeds and helps with dispersal. So the cycle is: Flower \u2192 Pollination \u2192 Fertilisation \u2192 **Fruit** \u2192 Seed \u2192 Germination \u2192 New Plant.",
        },
      },
      {
        id: "gen-sci-s4-2",
        type: "info" as const,
        content:
          "**Pollination \u2014 The Journey of Pollen**\n\nPollination is the transfer of pollen from the **stamen** (male) to the **stigma** (female).\n\n**\ud83d\udc1d Insect-pollinated flowers:**\n\u2022 Large, colourful petals\n\u2022 Sweet scent and nectar\n\u2022 Sticky pollen (attaches to insects)\n\u2022 Examples: Rose, Sunflower, Orchid\n\n**\ud83c\udf2c\ufe0f Wind-pollinated flowers:**\n\u2022 Small, dull petals\n\u2022 No scent or nectar\n\u2022 Light, smooth pollen (blown by wind)\n\u2022 Examples: Grass, Maize, Wheat\n\n**After pollination:**\n\u2022 Pollen tube grows down the style\n\u2022 Male nucleus meets female nucleus \u2192 **Fertilisation**\n\u2022 Ovule becomes **seed**, ovary becomes **fruit**\n\n**Seed Dispersal:**\n\ud83c\udf2c\ufe0f Wind \u2014 Dandelion, Maple\n\ud83d\udc26 Animals \u2014 Berries eaten and seeds passed out\n\ud83d\udca5 Explosive \u2014 Touch-me-not plant shoots seeds\n\ud83c\udf0a Water \u2014 Coconut floats to new islands",
      },
      {
        id: "gen-sci-s4-3",
        type: "question" as const,
        content:
          "A flower has large, brightly coloured petals and produces nectar. How is it most likely pollinated?",
        exercise: {
          question: "A flower has large, brightly coloured petals and produces nectar. How is it most likely pollinated?",
          options: ["By wind", "By insects", "By water", "By self-pollination"],
          correctIndex: 1,
          explanation: "Large, brightly coloured petals and nectar are signs of an **insect-pollinated** flower. The bright colours attract insects like bees, and the nectar rewards them for visiting.",
        },
      },
      {
        id: "gen-sci-s4-4",
        type: "info" as const,
        content:
          "**Reproduction in Humans**\n\nHumans reproduce **sexually** \u2014 this means a male sex cell (sperm) must fuse with a female sex cell (egg/ovum).\n\n**\ud83d\udc68 Male Reproductive System:**\n\u2022 **Testes** \u2014 Produce sperm and testosterone\n\u2022 **Sperm duct** \u2014 Carries sperm\n\u2022 **Penis** \u2014 Delivers sperm\n\n**\ud83d\udc69 Female Reproductive System:**\n\u2022 **Ovaries** \u2014 Produce eggs (ova) and hormones\n\u2022 **Fallopian tubes** \u2014 Where fertilisation happens\n\u2022 **Uterus (womb)** \u2014 Where baby grows\n\u2022 **Vagina** \u2014 Birth canal\n\n**The Menstrual Cycle (~28 days):**\n\ud83d\udcc5 Day 1-5: Menstruation (period)\n\ud83d\udcc5 Day 6-13: Uterus lining rebuilds\n\ud83d\udcc5 Day 14: **Ovulation** \u2014 egg released\n\ud83d\udcc5 Day 15-28: Uterus ready for pregnancy\n\n**Fertilisation:**\n\u2022 Sperm meets egg in the fallopian tube\n\u2022 One sperm penetrates the egg\n\u2022 Fertilised egg travels to uterus\n\u2022 Embryo implants in uterus lining\n\u2022 Baby develops over 9 months (40 weeks)",
      },
      {
        id: "gen-sci-s4-5",
        type: "question" as const,
        content:
          "Where does fertilisation typically occur in humans?",
        exercise: {
          question: "Where does fertilisation typically occur in humans?",
          options: ["In the ovary", "In the uterus", "In the fallopian tube", "In the vagina"],
          correctIndex: 2,
          explanation: "Fertilisation typically occurs in the **fallopian tube**. The sperm swim up from the vagina, through the uterus, and meet the egg in the fallopian tube. The fertilised egg then travels to the uterus to implant and grow.",
        },
      },
      {
        id: "gen-sci-s4-6",
        type: "checkpoint" as const,
        content:
          "Reproduction Mastery",
        checkpoint: {
          title: "Reproduction Mastery",
          passThreshold: 2,
          bonusXp: 15,
          questions: [
            {
              question: "What is the male part of a flower called?",
              options: ["Carpel", "Stamen", "Ovary", "Petal"],
              correctIndex: 1,
              explanation: "The **stamen** is the male reproductive part of a flower. It consists of the anther (produces pollen) and filament (supports the anther).",
            },
            {
              question: "Which form of reproduction does NOT require seeds or flowers?",
              options: ["Sexual reproduction", "Pollination", "Vegetative propagation", "Fertilisation"],
              correctIndex: 2,
              explanation: "**Vegetative propagation** (asexual reproduction) does not require seeds or flowers. New plants grow from runners, bulbs, tubers, or cuttings.",
            },
            {
              question: "During the menstrual cycle, ovulation occurs around day:",
              options: ["5", "14", "21", "28"],
              correctIndex: 1,
              explanation: "**Ovulation** typically occurs around **day 14** of a 28-day menstrual cycle. This is when a mature egg is released from the ovary.",
            },
          ],
        },
      },
    ],
  },
  {
    id: "gen-sci-s5",
    title: "Solar Panels — Harnessing the Sun's Energy",
    subject: "General Science",
    subjectIcon: "☀️",
    programme: "Science" as const,
    difficulty: 2,
    estimatedMinutes: 12,
    xpReward: 30,
    unitId: "general-science",
    prerequisites: [],
    shsLevels: ["SHS 1"],
    suggestedLevel: "SHS 1",
    steps: [
      {
        id: "gen-sci-s5-0",
        type: "info" as const,
        content:
          "**What is Solar Energy?**\n\nSolar panels are devices that convert **sunlight directly into electricity** using a process called the **photovoltaic effect**.\n\n**How does a solar panel work?**\n\n\u2600\ufe0f Sunlight hits the panel (made of silicon semiconductors)\n\u26a1 Photons from sunlight knock electrons loose\n\ud83d\udd00 Electrons flow through the material -> ELECTRICITY!\n\ud83d\udd0c Wires carry this electricity to power your home\n\n**Key Components:**\n\u2022 **Solar cells** \u2014 The individual units that generate electricity\n\u2022 **Solar panel** \u2014 A collection of solar cells\n\u2022 **Solar array** \u2014 Multiple panels working together\n\u2022 **Inverter** \u2014 Converts DC to AC (what your home uses)\n\u2022 **Battery** \u2014 Stores excess energy for night-time use\n\nDid you know? The first solar cell was invented in 1954 at Bell Labs and could only power a small radio!",
      },
      {
        id: "gen-sci-s5-1",
        type: "predict" as const,
        content:
          "Why is solar energy a good choice for Ghana?",
        predict: {
          pattern: `Ghana has abundant sunshine (4.5-5.5 kWh/m²/day)
Many rural areas lack grid electricity
Solar panel prices have dropped 80% in 10 years`,
          question: "Why is solar energy a good choice for Ghana?",
          options: ["Ghana has limited sunshine", "Solar panels are very cheap", "Ghana has abundant sunshine and many areas need electricity", "Solar panels work better in cloudy weather"],
          correctIndex: 2,
          explanation: "Ghana has **abundant sunshine** and many rural areas do not have access to the national electricity grid. Solar panels can be installed anywhere the sun shines, making them perfect for bringing electricity to remote communities!",
        },
      },
      {
        id: "gen-sci-s5-2",
        type: "info" as const,
        content:
          "**Solar Energy in Ghana \u2014 Real Projects**\n\n**\ud83c\udfd7\ufe0f Pokuase Community Solar Project**\n\u2022 Brings solar power to under-served communities\n\u2022 Provides reliable electricity for homes and small businesses\n\u2022 Reduces dependence on the national grid\n\n**\ud83c\udfd7\ufe0f Bui Solar Energy Project**\n\u2022 One of the largest solar projects in West Africa\n\u2022 250 MW capacity (enough for thousands of homes!)\n\u2022 Hybrid system \u2014 combines solar with Bui Hydroelectric Dam\n\u2022 Water from the dam can be used when the sun isn't shining\n\n**\ud83d\udca1 Solar vs. Fossil Fuels:**\n\n| Solar Energy | Fossil Fuels |\n|-------------|-------------|\n| \u2600\ufe0f Renewable (never runs out) | \ud83e\udea8 Non-renewable (will run out) |\n| \ud83c\udf31 Clean (no pollution) | \ud83d\udca8 Pollutes the air |\n| \ud83c\udfe0 Can be installed anywhere | \ud83c\udfed Needs big power plants |\n| \ud83d\udcb0 Free after installation | \ud83d\udcb8 Continuous fuel cost |\n\n> **Environmental Impact:** Switching to solar reduces greenhouse gas emissions and helps fight climate change!",
      },
      {
        id: "gen-sci-s5-3",
        type: "question" as const,
        content:
          "What device converts the DC electricity from solar panels into AC electricity for home use?",
        exercise: {
          question: "What device converts the DC electricity from solar panels into AC electricity for home use?",
          options: ["Solar cell", "Battery", "Inverter", "Transformer"],
          correctIndex: 2,
          explanation: "An **inverter** converts the direct current (DC) electricity produced by solar panels into alternating current (AC) electricity that can be used by home appliances and the electrical grid.",
        },
      },
      {
        id: "gen-sci-s5-4",
        type: "info" as const,
        content:
          "**Factors Affecting Solar Panel Performance**\n\n**\u2600\ufe0f Sunlight intensity** \u2014 More sunlight = more electricity\n\u2022 Panels work best in direct sunlight\n\u2022 Cloudy days reduce output by 50-90%\n\n**\ud83c\udf21\ufe0f Temperature** \u2014 Surprisingly, cooler is better!\n\u2022 Solar panels lose efficiency when very hot\n\u2022 Optimal temperature is about 25\u00b0C\n\n**\ud83d\udcd0 Tilt and orientation** \u2014 Panels should face the sun\n\u2022 In Ghana, panels face south (we're in the northern hemisphere!)\n\u2022 Tilt angle should match your latitude\n\n**\ud83e\uddf9 Cleanliness** \u2014 Dust reduces output\n\u2022 Dust can reduce efficiency by up to 25%\n\u2022 Regular cleaning is essential, especially in dry seasons\n\n**Economic Benefits for Ghana:**\n\u2022 \ud83d\udcbc Creates jobs in installation and maintenance\n\u2022 \ud83d\udcb0 Reduces electricity bills for homes and businesses\n\u2022 \ud83c\udf0d Reduces carbon emissions\n\u2022 \ud83d\udd0b Energy independence \u2014 less reliance on imported fuels",
      },
      {
        id: "gen-sci-s5-5",
        type: "question" as const,
        content:
          "What happens to solar panel efficiency when the temperature gets very high?",
        exercise: {
          question: "What happens to solar panel efficiency when the temperature gets very high?",
          options: ["It increases", "It decreases", "It stays the same", "It doubles"],
          correctIndex: 1,
          explanation: "Solar panel efficiency **decreases** at high temperatures! Although sunlight is needed, panels work best at around 25\u00b0C. High temperatures cause the electrons to move more erratically, reducing the voltage output.",
        },
      },
      {
        id: "gen-sci-s5-6",
        type: "checkpoint" as const,
        content:
          "Solar Energy Mastery",
        checkpoint: {
          title: "Solar Energy Mastery",
          passThreshold: 2,
          bonusXp: 15,
          questions: [
            {
              question: "What material is commonly used in solar cells to convert sunlight to electricity?",
              options: ["Copper", "Aluminium", "Silicon", "Iron"],
              correctIndex: 2,
              explanation: "**Silicon** is the most common semiconductor used in solar cells. It's abundant (found in sand!) and has the right properties for the photovoltaic effect.",
            },
            {
              question: "Why is solar energy considered a renewable resource?",
              options: ["It is cheap", "The sun will keep shining for billions of years", "It does not pollute", "It can be stored in batteries"],
              correctIndex: 1,
              explanation: "Solar energy is **renewable** because the sun will continue to produce energy for billions of years. Unlike fossil fuels, we will never 'run out' of sunlight.",
            },
            {
              question: "Which Ghanaian project combines solar power with a hydroelectric dam?",
              options: ["Pokuase Solar Project", "Akosombo Dam", "Bui Solar Energy Project", "Tema Solar Farm"],
              correctIndex: 2,
              explanation: "The **Bui Solar Energy Project** is a hybrid system that combines solar power with the Bui Hydroelectric Dam. This way, electricity can be generated both from the sun and from water.",
            },
          ],
        },
      },
    ],
  },
  {
    id: "gen-sci-s6",
    title: "Force — Pushes and Pulls in the Physical World",
    subject: "General Science",
    subjectIcon: "💪",
    programme: "Science" as const,
    difficulty: 2,
    estimatedMinutes: 12,
    xpReward: 35,
    unitId: "general-science",
    prerequisites: [],
    shsLevels: ["SHS 1"],
    suggestedLevel: "SHS 1",
    steps: [
      {
        id: "gen-sci-s6-0",
        type: "info" as const,
        content:
          "**What is a Force?**\n\nA force is a **push or pull** that can change an object's motion or shape.\n\n\u2192 Forces are measured in **Newtons (N)**\n\u2192 They are **vector quantities** (have magnitude AND direction)\n\n**Types of Forces:**\n\n\ud83d\udcaa **Contact Forces** \u2014 Objects must touch\n\u2022 **Friction** \u2014 Resistance when surfaces rub together\n\u2022 **Tension** \u2014 Pulling force in a rope/string\n\u2022 **Air resistance** \u2014 Friction with air molecules\n\u2022 **Normal reaction** \u2014 Surface pushing up against an object\n\n\ud83c\udf0c **Non-contact Forces** \u2014 Objects don't need to touch\n\u2022 **Gravity** \u2014 Attraction between objects with mass\n\u2022 **Magnetism** \u2014 Attraction/repulsion between magnets\n\u2022 **Electrostatic** \u2014 Force between charged objects\n\nDid you know? You are currently experiencing a force of about 700 N pulling you towards the Earth (gravity)!",
      },
      {
        id: "gen-sci-s6-1",
        type: "predict" as const,
        content:
          "What force causes the ball to slow down on grass?",
        predict: {
          pattern: `A ball is kicked on grass → It slows down and stops
A ball is kicked on ice → It slides much further
A ball is kicked in space → It keeps going forever`,
          question: "What force causes the ball to slow down on grass?",
          options: ["Gravity", "Friction", "Magnetism", "Air resistance"],
          correctIndex: 1,
          explanation: "**Friction** between the ball and the grass causes it to slow down. On ice, there is less friction, so the ball travels further. In space, there is no friction at all \u2014 so the ball would keep moving forever!",
        },
      },
      {
        id: "gen-sci-s6-2",
        type: "info" as const,
        content:
          "**Friction \u2014 Helpful or Harmful?**\n\n**\u2705 Advantages of Friction:**\n\u2022 \ud83d\udeb6 Allows us to walk without slipping\n\u2022 \u270d\ufe0f Lets us write on paper\n\u2022 \ud83d\ude97 Car brakes use friction to stop\n\u2022 \ud83e\udeb5 Matches light due to friction\n\n**\u274c Disadvantages of Friction:**\n\u2022 \ud83d\udd25 Causes wear and tear on machines\n\u2022 \ud83c\udf21\ufe0f Produces heat (engines can overheat)\n\u2022 \u26a1 Wastes energy (need more fuel)\n\n**Reducing Friction:**\n\u2022 \ud83d\udee2\ufe0f Lubricants (oil, grease)\n\u2022 \ud83d\udede Ball bearings (rolling instead of sliding)\n\u2022 \u2708\ufe0f Streamlining (reducing air resistance)\n\n**Gravity \u2014 The Universal Force**\n\n\u2022 Every object with mass attracts every other object\n\u2022 Earth's gravity pulls everything towards its centre\n\u2022 Gravity gives us **weight** (mass \u00d7 gravity = weight)\n\u2022 On the Moon, gravity is 1/6 of Earth's\n\n> **Formula:** Weight (N) = Mass (kg) \u00d7 Gravitational field strength (N/kg)\n> On Earth: g = 9.8 N/kg (or approximately 10 N/kg)",
      },
      {
        id: "gen-sci-s6-3",
        type: "question" as const,
        content:
          "A student has a mass of 50 kg. What is their weight on Earth? (Use g = 10 N/kg)",
        exercise: {
          question: "A student has a mass of 50 kg. What is their weight on Earth? (Use g = 10 N/kg)",
          options: ["5 N", "50 N", "500 N", "5000 N"],
          correctIndex: 2,
          explanation: "Weight = mass \u00d7 gravity = 50 kg \u00d7 10 N/kg = **500 N**.\n\nNotice that weight and mass are DIFFERENT! Mass is how much matter you contain (always 50 kg), while weight is the force of gravity on you (changes with gravity).",
        },
      },
      {
        id: "gen-sci-s6-4",
        type: "info" as const,
        content:
          "**Speed, Velocity and Acceleration**\n\n**Speed** \u2014 How fast something is moving (scalar)\n\u2192 Speed = Distance / Time\n\u2192 Units: m/s or km/h\n\n**Velocity** \u2014 Speed in a given direction (vector)\n\u2192 Same formula as speed, but includes direction\n\u2192 Example: '20 m/s due North'\n\n**Acceleration** \u2014 How quickly velocity changes\n\u2192 Acceleration = Change in velocity / Time taken\n\u2192 Units: m/s\u00b2\n\n**Newton's Second Law:**\n\n> **Force = Mass \u00d7 Acceleration (F = ma)**\n\nThis means:\n\u2022 Heavier objects need MORE force to accelerate\n\u2022 More force = faster acceleration\n\u2022 More mass = slower acceleration (with same force)\n\n**Example:** If you push a shopping cart with 10 N of force and it has a mass of 5 kg:\na = F/m = 10/5 = 2 m/s\u00b2",
      },
      {
        id: "gen-sci-s6-5",
        type: "question" as const,
        content:
          "A car accelerates from rest to 20 m/s in 5 seconds. What is its acceleration?",
        exercise: {
          question: "A car accelerates from rest to 20 m/s in 5 seconds. What is its acceleration?",
          options: ["4 m/s\u00b2", "10 m/s\u00b2", "100 m/s\u00b2", "0.25 m/s\u00b2"],
          correctIndex: 0,
          explanation: "Acceleration = Change in velocity / Time = (20 - 0) / 5 = **4 m/s\u00b2**.\n\nThis means the car's velocity increases by 4 m/s every second!",
        },
      },
      {
        id: "gen-sci-s6-6",
        type: "checkpoint" as const,
        content:
          "Force Mastery",
        checkpoint: {
          title: "Force Mastery",
          passThreshold: 2,
          bonusXp: 15,
          questions: [
            {
              question: "What type of force is gravity?",
              options: ["Contact force", "Non-contact force", "Frictional force", "Elastic force"],
              correctIndex: 1,
              explanation: "Gravity is a **non-contact force** \u2014 objects don't need to be touching to experience it. The Earth's gravity reaches across space to keep the Moon in orbit!",
            },
            {
              question: "What unit is force measured in?",
              options: ["Kilograms", "Newtons", "Metres", "Joules"],
              correctIndex: 1,
              explanation: "Force is measured in **Newtons (N)**, named after Sir Isaac Newton who developed the laws of motion. 1 Newton is approximately the force needed to lift a 100g apple.",
            },
            {
              question: "Which of these is NOT a way to reduce friction?",
              options: ["Using oil", "Using ball bearings", "Making surfaces rougher", "Streamlining"],
              correctIndex: 2,
              explanation: "Making surfaces **rougher** would INCREASE friction, not reduce it! Smooth surfaces reduce friction. That's why ice skates glide easily on ice.",
            },
          ],
        },
      },
    ],
  },
  {
    id: "gen-sci-s7",
    title: "Basic Electronics — Components and Circuits",
    subject: "General Science",
    subjectIcon: "⚡",
    programme: "Science" as const,
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 35,
    unitId: "general-science",
    prerequisites: [],
    shsLevels: ["SHS 1"],
    suggestedLevel: "SHS 1",
    steps: [
      {
        id: "gen-sci-s7-0",
        type: "info" as const,
        content:
          "**What is Electronics?**\n\nElectronics is the branch of physics that deals with controlling the flow of electrons through components to perform useful functions.\n\n**Basic Circuit Components:**\n\n\u26a1 **Battery** \u2014 Provides the electrical energy (voltage source)\n\ud83d\udd0c **Wire** \u2014 Connects components, allows current to flow\n\ud83d\udca1 **Bulb/LED** \u2014 Converts electricity into light\n\ud83d\udccf **Resistor** \u2014 Limits current flow (measured in Ohms \u03a9)\n\ud83d\udd18 **Switch** \u2014 Opens or closes the circuit\n\n**Key Concepts:**\n\n**Voltage (V)** \u2014 The 'push' that makes electrons move\n\u2192 Measured in volts (V)\n\u2192 Like water pressure in a pipe\n\n**Current (I)** \u2014 The flow of electrons\n\u2192 Measured in amperes or amps (A)\n\u2192 Like the flow rate of water\n\n**Resistance (R)** \u2014 Opposition to current flow\n\u2192 Measured in ohms (\u03a9)\n\u2192 Like a narrow section in a pipe\n\n> **Ohm's Law:** V = I \u00d7 R\n> Voltage = Current \u00d7 Resistance",
      },
      {
        id: "gen-sci-s7-1",
        type: "predict" as const,
        content:
          "This is a diagram of a:",
        predict: {
          pattern: `Battery (+) → Wire → LED → Wire → Battery (-)
Current flows: + → LED → -
The LED lights up!`,
          question: "This is a diagram of a:",
          options: ["Parallel circuit", "Complete circuit", "Broken circuit", "Short circuit"],
          correctIndex: 1,
          explanation: "This is a **complete circuit** (also called a closed circuit)! The electrons can flow from the battery's positive terminal, through the LED, and back to the negative terminal. As long as the path is unbroken, the LED will light up.",
        },
      },
      {
        id: "gen-sci-s7-2",
        type: "info" as const,
        content:
          "**Electronic Components \u2014 The Building Blocks**\n\n**\ud83d\udd36 Resistors** \u2014 Control current flow\n\u2022 Colour bands tell you the resistance value\n\u2022 Used to protect other components from too much current\n\n**\ud83d\udd37 Capacitors** \u2014 Store electrical charge\n\u2022 Like a rechargeable battery\n\u2022 Used to smooth voltage fluctuations\n\n**\ud83d\udd36 Diodes** \u2014 One-way valves for electricity\n\u2022 Allow current to flow in only ONE direction\n\u2022 LEDs (Light Emitting Diodes) are special diodes that produce light\n\n**\ud83d\udd37 Transistors** \u2014 Amplify or switch signals\n\u2022 The 'brain' of modern electronics\n\u2022 Billions of transistors in a computer chip!\n\n**\ud83d\udfe2 LEDs (Light Emitting Diodes):**\n\u2022 Convert electricity directly into light\n\u2022 Very efficient (use less energy than bulbs)\n\u2022 Available in many colours\n\u2022 Always need a resistor to limit current!\n\n> **Safety Tip:** Always check the polarity of LEDs! The longer leg (+) goes to the positive side.",
      },
      {
        id: "gen-sci-s7-3",
        type: "question" as const,
        content:
          "Why does an LED always need a resistor connected in series with it?",
        exercise: {
          question: "Why does an LED always need a resistor connected in series with it?",
          options: ["To make it brighter", "To limit the current and prevent damage", "To change the colour of the light", "To store electricity"],
          correctIndex: 1,
          explanation: "An LED needs a **resistor** to **limit the current**. Without a resistor, too much current would flow through the LED and it would burn out immediately. The resistor protects the LED by ensuring only the right amount of current flows.",
        },
      },
      {
        id: "gen-sci-s7-4",
        type: "info" as const,
        content:
          "**Reading Circuit Diagrams**\n\nCircuit diagrams use symbols to represent components:\n\n```\n\u2500\u2500\u2500 ||| \u2500\u2500\u2500  Battery (long = +, short = -)\n\u2500\u2500\u2500 \u23e4\u23e4 \u2500\u2500\u2500  Resistor\n\u2500\u2500\u2500 \u25b6| \u2500\u2500\u2500  Diode/LED (arrow shows flow direction)\n\u2500\u2500\u2500 \u25cb  \u2500\u2500\u2500  Bulb/Lamp\n\u2500\u2500\u2500 \u23e4/ \u23e4\u2500\u2500\u2500  Switch (open/closed)\n```\n\n**Series Circuit:**\n\u2022 Components in a single loop\n\u2022 Current is the same everywhere\n\u2022 If one component fails, ALL stop working\n\u2022 Example: Old Christmas tree lights\n\n**Parallel Circuit:**\n\u2022 Components in separate branches\n\u2022 Voltage is the same across each branch\n\u2022 If one component fails, others keep working\n\u2022 Example: House wiring\n\n**Practical Project \u2014 Light-Activated Switch:**\nYou can build a circuit that turns on an LED when it gets dark using:\n\u2022 An LDR (Light Dependent Resistor)\n\u2022 A transistor (acts as a switch)\n\u2022 A resistor and LED\n\n> **Real-world application:** This is how street lights automatically turn on at night!",
      },
      {
        id: "gen-sci-s7-5",
        type: "question" as const,
        content:
          "In which type of circuit do all components stop working if one component fails?",
        exercise: {
          question: "In which type of circuit do all components stop working if one component fails?",
          options: ["Series circuit", "Parallel circuit", "Both types", "Neither type"],
          correctIndex: 0,
          explanation: "In a **series circuit**, components are connected in a single loop. If one component fails (like a bulb blowing), the circuit is broken and ALL components stop working. This is why parallel circuits are used for home wiring!",
        },
      },
      {
        id: "gen-sci-s7-6",
        type: "checkpoint" as const,
        content:
          "Electronics Mastery",
        checkpoint: {
          title: "Electronics Mastery",
          passThreshold: 2,
          bonusXp: 15,
          questions: [
            {
              question: "What is the function of a diode in a circuit?",
              options: ["Store electrical charge", "Allow current flow in one direction only", "Increase voltage", "Limit current flow"],
              correctIndex: 1,
              explanation: "A **diode** allows current to flow in only **one direction**. This is useful for converting AC to DC and for protecting circuits from reverse voltage.",
            },
            {
              question: "Which component stores electrical charge and can smooth voltage fluctuations?",
              options: ["Resistor", "Capacitor", "Diode", "Transistor"],
              correctIndex: 1,
              explanation: "A **capacitor** stores electrical charge and releases it when needed. This makes capacitors useful for smoothing out voltage fluctuations in power supplies.",
            },
            {
              question: "What does an LDR (Light Dependent Resistor) do?",
              options: ["Produces light when current flows", "Its resistance changes with light intensity", "Stores light energy", "Amplifies light signals"],
              correctIndex: 1,
              explanation: "An **LDR's resistance changes with light intensity**. In bright light, its resistance is low. In darkness, its resistance is high. This makes it perfect for light-sensing circuits like automatic night lights.",
            },
          ],
        },
      },
    ],
  },
  {
    id: "gen-sci-s8",
    title: "Promoting Health and Safety",
    subject: "General Science",
    subjectIcon: "🛡️",
    programme: "Science" as const,
    difficulty: 1,
    estimatedMinutes: 12,
    xpReward: 30,
    unitId: "general-science",
    prerequisites: [],
    shsLevels: ["SHS 1"],
    suggestedLevel: "SHS 1",
    steps: [
      {
        id: "gen-sci-s8-0",
        type: "info" as const,
        content:
          "**Understanding Hazards**\n\nA **hazard** is anything that has the potential to cause harm.\n\n**Types of Hazards:**\n\n\ud83e\uddea **Biological** \u2014 Bacteria, viruses, fungi\n\u2192 Examples: Malaria, COVID-19, food poisoning\n\n\ud83e\uddea **Chemical** \u2014 Toxic substances\n\u2192 Examples: Bleach, pesticides, battery acid\n\n\u26a1 **Physical** \u2014 Environmental dangers\n\u2192 Examples: Wet floors, exposed wires, noise\n\n\ud83d\udd25 **Fire/Electrical** \u2014 Fire and electricity risks\n\u2192 Examples: Faulty wiring, gas leaks\n\n**Managing Hazards \u2014 The Safety Approach:**\n\n1\ufe0f\u20e3 **Identify** \u2014 Spot the hazard\n2\ufe0f\u20e3 **Assess** \u2014 How risky is it?\n3\ufe0f\u20e3 **Control** \u2014 What can we do?\n   \u2022 Remove it completely\n   \u2022 Use protective equipment\n   \u2022 Put safety signs/policies\n4\ufe0f\u20e3 **Review** \u2014 Is the control working?\n\n\ud83d\udee1\ufe0f **PPE (Personal Protective Equipment):**\n\u2022 Safety goggles\n\u2022 Lab coat/apron\n\u2022 Gloves\n\u2022 Closed shoes",
      },
      {
        id: "gen-sci-s8-1",
        type: "predict" as const,
        content:
          "Person B's health problems are most likely caused by:",
        predict: {
          pattern: `Person A: Eats balanced meals, exercises daily, sleeps 8 hours
Person B: Eats junk food, never exercises, sleeps 4 hours, smokes

After 20 years: Person A is healthy. Person B has health problems.`,
          question: "Person B's health problems are most likely caused by:",
          options: ["Bad luck", "Genetics", "Lifestyle choices", "Infectious diseases"],
          correctIndex: 2,
          explanation: "Person B's health problems are due to **lifestyle choices** \u2014 poor diet, lack of exercise, insufficient sleep, and smoking. These are called **lifestyle diseases** because they develop from how we live our lives.",
        },
      },
      {
        id: "gen-sci-s8-2",
        type: "info" as const,
        content:
          "**Lifestyle Diseases \u2014 Preventable!**\n\nLifestyle diseases are **non-communicable** (you can't catch them from someone else).\n\n**Common Lifestyle Diseases:**\n\n\u2764\ufe0f **Heart Disease** \u2014 From poor diet, lack of exercise, smoking\n\u2022 Leading cause of death worldwide\n\u2022 Can be prevented with healthy habits\n\n\ud83e\udec1 **Lung Cancer** \u2014 Mainly from smoking\n\u2022 90% of lung cancer cases are from smoking\n\u2022 Also from air pollution\n\n\ud83e\udde0 **Stroke** \u2014 Blood supply to brain is blocked\n\u2022 Linked to high blood pressure, smoking, obesity\n\n\ud83c\udf54 **Obesity** \u2014 Excessive body fat\n\u2022 BMI over 30 is considered obese\n\u2022 Increases risk of diabetes, heart disease\n\n\ud83d\udc89 **Type 2 Diabetes** \u2014 Body can't control blood sugar\n\u2022 Strongly linked to diet and exercise\n\n**Prevention Tips:**\n\ud83e\udd57 Eat more fruits, vegetables, and whole grains\n\ud83c\udfc3 Exercise at least 30 minutes daily\n\ud83d\ude34 Get 7-9 hours of sleep\n\ud83d\udead Avoid smoking and excessive alcohol\n\ud83d\udca7 Drink plenty of water\n\n> **Did you know?** Regular exercise can reduce your risk of heart disease by 50%!",
      },
      {
        id: "gen-sci-s8-3",
        type: "question" as const,
        content:
          "Which of these is NOT a lifestyle disease?",
        exercise: {
          question: "Which of these is NOT a lifestyle disease?",
          options: ["Type 2 diabetes", "Malaria", "Heart disease", "Obesity"],
          correctIndex: 1,
          explanation: "**Malaria** is an **infectious disease** caused by a parasite transmitted by mosquitoes. You can 'catch' malaria from a mosquito bite. Type 2 diabetes, heart disease, and obesity are lifestyle diseases (non-communicable).",
        },
      },
      {
        id: "gen-sci-s8-4",
        type: "info" as const,
        content:
          "**Drugs and Their Effects**\n\nA drug is any substance that changes how the body works. Some drugs are medicines (like paracetamol), while others are abused.\n\n**Categories of Abused Drugs:**\n\n\ud83d\udeac **Stimulants** (Speed up body systems)\n\u2022 Cocaine, methamphetamine, nicotine\n\u2022 Effects: Increased heart rate, alertness, energy\n\u2022 Risks: Heart attack, seizures, addiction\n\n\ud83c\udf77 **Depressants** (Slow down body systems)\n\u2022 Alcohol, sleeping pills\n\u2022 Effects: Relaxation, drowsiness, slower breathing\n\u2022 Risks: Liver disease, memory loss, addiction\n\n\ud83c\udf00 **Hallucinogens** (Change perception of reality)\n\u2022 LSD, MDMA (Ecstasy)\n\u2022 Effects: Seeing/hearing things that aren't real\n\u2022 Risks: Panic attacks, long-term mental health issues\n\n\ud83c\udf3f **Cannabis (Marijuana)**\n\u2022 Affects memory and concentration\n\u2022 Long-term use linked to mental health problems\n\n\ud83d\udc89 **Heroin** \u2014 Highly addictive opiate\n\u2022 Slows breathing \u2014 can cause death from overdose\n\n**Consequences of Drug Abuse:**\n\u2022 \u2764\ufe0f\u200d\ud83e\ude79 Health damage (heart, lungs, liver, brain)\n\u2022 \ud83d\udc94 Family problems\n\u2022 \u2696\ufe0f Legal trouble\n\u2022 \ud83d\udcc9 Poor academic performance\n\u2022 \ud83d\udcb0 Financial hardship\n\n> **Say NO to drugs!** The best choice is to never start. If you or someone you know needs help, talk to a trusted adult or counsellor.",
      },
      {
        id: "gen-sci-s8-5",
        type: "question" as const,
        content:
          "Which category of drugs speeds up the body's systems and increases heart rate?",
        exercise: {
          question: "Which category of drugs speeds up the body's systems and increases heart rate?",
          options: ["Depressants", "Stimulants", "Hallucinogens", "Opiates"],
          correctIndex: 1,
          explanation: "**Stimulants** speed up the body's systems. They increase heart rate, blood pressure, and alertness. Examples include cocaine, methamphetamine, and nicotine. Long-term use can lead to heart attacks and addiction.",
        },
      },
      {
        id: "gen-sci-s8-6",
        type: "checkpoint" as const,
        content:
          "Health & Safety Mastery",
        checkpoint: {
          title: "Health & Safety Mastery",
          passThreshold: 2,
          bonusXp: 15,
          questions: [
            {
              question: "Which of these is an example of a biological hazard?",
              options: ["Wet floor", "Bleach", "Malaria parasite", "Exposed wire"],
              correctIndex: 2,
              explanation: "The **malaria parasite** is a biological hazard (a living organism that can cause disease). Wet floors are physical hazards, bleach is chemical, and exposed wires are electrical hazards.",
            },
            {
              question: "Which lifestyle choice is most effective for preventing heart disease?",
              options: ["Taking vitamins", "Regular exercise and healthy diet", "Sleeping 4 hours per night", "Drinking coffee"],
              correctIndex: 1,
              explanation: "**Regular exercise and a healthy diet** are the most effective ways to prevent heart disease. Exercise strengthens the heart, and a healthy diet keeps cholesterol and blood pressure in check.",
            },
            {
              question: "What does PPE stand for in safety?",
              options: ["Personal Protection Equipment", "Professional Protective Equipment", "Personal Protective Equipment", "Primary Protection Element"],
              correctIndex: 2,
              explanation: "PPE stands for **Personal Protective Equipment**. This includes safety goggles, lab coats, gloves, and closed shoes that protect you from hazards in the laboratory or workplace.",
            },
          ],
        },
      },
    ],
  },
  {
    id: "gen-sci-s9",
    title: "Local Industry and Food Production — Science in Action",
    subject: "General Science",
    subjectIcon: "🏭",
    programme: "Science" as const,
    difficulty: 2,
    estimatedMinutes: 12,
    xpReward: 30,
    unitId: "general-science",
    prerequisites: [],
    shsLevels: ["SHS 1"],
    suggestedLevel: "SHS 1",
    steps: [
      {
        id: "gen-sci-s9-0",
        type: "info" as const,
        content:
          "**Science in Local Industry**\n\nMany traditional Ghanaian products involve fascinating scientific processes. Let's explore the science behind them!\n\n**\ud83e\uddfc Local Soap Production \u2014 Saponification**\n\nSoap making is a **chemical reaction** called **saponification**:\n\n> Fat/Oil + Alkali (caustic soda) \u2192 Soap + Glycerol\n\n**The Process:**\n1. Heat oil (palm oil, coconut oil)\n2. Add alkali solution carefully\n3. Stir continuously \u2014 chemical reaction happens!\n4. Pour into moulds to set\n5. Cut and cure for several days\n\n**Types of Local Soap:**\n\u2022 \ud83d\udfe4 **African Black Soap** \u2014 Made from plantain skins, cocoa pods, palm leaves\n\u2022 \u26aa **African White Soap** \u2014 Made from coconut oil and palm kernel oil\n\n\u2697\ufe0f **Emulsification** \u2014 Soap works because one end of the soap molecule loves water (hydrophilic) and the other end loves oil (hydrophobic). This allows soap to lift grease and dirt off surfaces!\n\n> **Safety Alert:** Caustic soda is highly corrosive! Always wear gloves and goggles when making soap.",
      },
      {
        id: "gen-sci-s9-1",
        type: "predict" as const,
        content:
          "What type of reaction is saponification?",
        predict: {
          pattern: `Fat/Oil + NaOH (caustic soda) → Soap + Glycerol
This is called saponification.
Heat is released during the reaction.`,
          question: "What type of reaction is saponification?",
          options: ["Physical change", "Exothermic chemical reaction", "Endothermic reaction", "Nuclear reaction"],
          correctIndex: 1,
          explanation: "Saponification is an **exothermic chemical reaction** \u2014 heat is released when the fat reacts with the alkali. The fat molecules (triglycerides) break apart and form soap molecules and glycerol.",
        },
      },
      {
        id: "gen-sci-s9-2",
        type: "info" as const,
        content:
          "**\ud83e\udd63 Gari Production \u2014 Cassava Processing**\n\nGari is made from cassava \u2014 a staple crop in Ghana. The process involves several scientific principles:\n\n**Step 1: Peeling & Washing**\n\u2192 Remove the skin (physical preparation)\n\n**Step 2: Grating**\n\u2192 Break down cell walls to release water and starch\n\n**Step 3: Fermentation (2-3 days)**\n\ud83e\uddea **Biology:** Microorganisms break down cyanogenic glycosides\n\ud83e\uddea **Chemistry:** This removes toxic hydrogen cyanide!\n\n**Step 4: Pressing & Drying**\n\u2192 Remove excess water (dehydration)\n\n**Step 5: Roasting**\n\ud83d\udd25 **Physics:** Heat transfer through conduction\n\ud83d\udd25 **Chemistry:** Starch gelatinises \u2014 becomes partially cooked\n\n**The Science Behind Cassava Processing:**\n\u2022 Raw cassava contains **cyanide compounds** \u2014 TOXIC!\n\u2022 Soaking and fermentation breaks down these compounds\n\u2022 Heat during roasting further removes any remaining toxins\n\u2022 This makes cassava SAFE to eat!\n\n> **Did you know?** Without proper processing, eating raw cassava can make you very sick. The fermentation and heating steps are essential for food safety!",
      },
      {
        id: "gen-sci-s9-3",
        type: "question" as const,
        content:
          "Why is cassava fermented for 2-3 days before making gari?",
        exercise: {
          question: "Why is cassava fermented for 2-3 days before making gari?",
          options: ["To improve the taste only", "To remove toxic cyanide compounds", "To change the colour", "To make it last longer"],
          correctIndex: 1,
          explanation: "Fermentation is essential to **remove toxic cyanide compounds** from cassava. Raw cassava contains cyanogenic glycosides that break down to release hydrogen cyanide. The fermentation process allows microorganisms to break down these toxic compounds, making the cassava safe to eat.",
        },
      },
      {
        id: "gen-sci-s9-4",
        type: "info" as const,
        content:
          "**\ud83c\udf3d Kenkey Production \u2014 Fermentation in Action**\n\nKenkey is a traditional Ghanaian food made from fermented maize dough. The science behind it is fascinating!\n\n**The Process:**\n1. \ud83c\udf3e **Soaking** \u2014 Maize soaked in water for 1-2 days\n2. \u2699\ufe0f **Milling** \u2014 Wet maize ground into dough\n3. \ud83e\uddea **Fermentation** (2-3 days):\n   \u2192 **Lactobacillus bacteria** produce lactic acid\n   \u2192 **Yeast** produces carbon dioxide\n   \u2192 This gives kenkey its sour taste and fluffy texture!\n4. \ud83d\udd25 **Aflata preparation:**\n   \u2192 Part of the dough is cooked with water\n   \u2192 Mixed back with raw dough\n   \u2192 This gelatinises the starch and creates the right consistency\n5. \ud83e\udd5f **Steaming** \u2014 The dough is wrapped in maize husks or leaves and steamed for 2-3 hours\n\n**\ud83e\uddc1 Tubani Production:**\n\u2022 Made from **black-eyed peas** (not maize!)\n\u2022 Soaked, blended with spices (pepper, salt, ginger)\n\u2022 Fermented for 8-12 hours\n\u2022 Steamed in small cakes\n\n> **Key Science Concepts Involved:**\n\ud83d\udd2c **Microbiology** \u2014 Microorganisms drive fermentation\n\ud83e\uddea **Biochemistry** \u2014 Enzymes break down complex molecules\n\ud83d\udd25 **Heat transfer** \u2014 Steaming cooks the food evenly\n\u2697\ufe0f **Starch gelatinisation** \u2014 Heat causes starch to absorb water and thicken",
      },
      {
        id: "gen-sci-s9-5",
        type: "question" as const,
        content:
          "What microorganism is primarily responsible for the sour taste of kenkey?",
        exercise: {
          question: "What microorganism is primarily responsible for the sour taste of kenkey?",
          options: ["Yeast", "Lactobacillus bacteria", "E. coli", "Mould"],
          correctIndex: 1,
          explanation: "**Lactobacillus bacteria** produce lactic acid during fermentation, which gives kenkey its characteristic sour taste. The same type of bacteria is used to make yoghurt! Yeast also plays a role by producing carbon dioxide that makes the kenkey fluffy.",
        },
      },
      {
        id: "gen-sci-s9-6",
        type: "checkpoint" as const,
        content:
          "Local Industry Mastery",
        checkpoint: {
          title: "Local Industry Mastery",
          passThreshold: 2,
          bonusXp: 15,
          questions: [
            {
              question: "What is the chemical reaction called when making soap?",
              options: ["Polymerisation", "Saponification", "Fermentation", "Oxidation"],
              correctIndex: 1,
              explanation: "**Saponification** is the chemical reaction between fat/oil and an alkali (like caustic soda) to produce soap and glycerol.",
            },
            {
              question: "Why is fermentation important in gari production?",
              options: ["To improve the colour", "To increase the weight", "To remove toxic cyanide compounds", "To add vitamins"],
              correctIndex: 2,
              explanation: "Fermentation breaks down **cyanogenic glycosides** in cassava that produce toxic hydrogen cyanide. This makes the cassava safe for consumption.",
            },
            {
              question: "What is the main ingredient in tubani?",
              options: ["Maize", "Cassava", "Black-eyed peas", "Plantain"],
              correctIndex: 2,
              explanation: "**Tubani** is made from **black-eyed peas** (not maize like kenkey). The peas are soaked, blended with spices, fermented, and steamed into small cakes.",
            },
          ],
        },
      },
    ],
  },
];
