/**
 * generalScienceContent.ts
 * ──────────────────────────
 * General Science Year 1 — 9 interactive sessions generated from
 * the Ministry of Education SHS curriculum.
 *
 * Auto-generated by scripts/generate_science_content.py
 * Do not edit directly — re-run the generator instead.
 */

import type { Lesson } from './learningContent';

export const GENERAL_SCIENCE_UNIT = {
  id: 'general-science',
  title: 'General Science Year 1',
  subtitle: '🔬 Foundation scientists — explore the world around you',
  colour: 'from-cyan-500/20 to-blue-500/20',
  icon: '🔬',
};

export const GENERAL_SCIENCE_LESSONS: Lesson[] = [
];
