/**
 * learningContent.ts
 * ──────────────────
 * Curriculum lesson data & helper functions.
 *
 * Core Mathematics lessons are auto-generated by:
 *   scripts/generate_all_coremaths.py
 */

import { GENERAL_SCIENCE_LESSONS, GENERAL_SCIENCE_UNIT } from '.\/generalScienceContent';
import { CORE_MATHS_SHS1_LESSONS } from '.\/generatedCoreMathsLessons';
import { CORE_MATHS2_SHS2_LESSONS } from '.\/generatedCoreMaths2Lessons';
import { INTER_SCIENCE_SHS1_LESSONS } from '.\/generatedInterScienceLessons';
import { INTER_SCIENCE_SHS2_LESSONS } from '.\/generatedInterScienceSHS2Lessons';
import { ENGLISH_SHS1_LESSONS } from '.\/generatedEnglishLessons';
import { ENG_LANG2_SHS2_LESSONS } from '.\/generatedEngLang2Lessons';
import { SOCIAL_STUDIES_SHS1_LESSONS } from '.\/generatedSocialStudiesLessons';
import { SOCIAL_STUDIES_SHS2_LESSONS } from '.\/generatedSocialStudiesSHS2Lessons';
import { BIOLOGY_SHS1_LESSONS } from '.\/generatedBiologyLessons';
import { CHEMISTRY_SHS1_LESSONS } from '.\/generatedChemistryLessons';
import { ADD_MATHS_SHS1_LESSONS } from '.\/generatedAdditionalMathsLessons';
import { PHYSICS_SHS1_LESSONS } from '.\/generatedPhysicsLessons';

// ── Types ──────────────────────────────────────────────────────────────────

export type StepType =
  | 'info'
  | 'question'
  | 'fill-blank'
  | 'match'
  | 'predict'
  | 'checkpoint';

export interface Exercise {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface FillBlank {
  template: string;
  answers: string[];
  hints: string[];
  explanation: string;
}

export interface MatchPair {
  left: string;
  right: string;
}

export interface MatchExercise {
  instruction: string;
  leftItems: string[];
  rightItems: string[];
  correctMatches: number[];
  explanation: string;
}

export interface PredictConfig {
  pattern: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface CheckpointQuestion {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface CheckpointConfig {
  title: string;
  questions: CheckpointQuestion[];
  passThreshold: number;
  bonusXp: number;
}

export interface VisualizeConfig {
  type: 'number-line' | 'venn' | 'bar-chart' | 'coordinate' | 'tree' | 'table';
  data: Record<string, unknown>;
}

export interface LessonStep {
  id: string;
  type: StepType;
  content: string;
  exercise?: Exercise;
  fillBlank?: FillBlank;
  match?: MatchExercise;
  predict?: PredictConfig;
  checkpoint?: CheckpointConfig;
  visualize?: MathVizConfig;
}

export interface Lesson {
  id: string;
  title: string;
  subject: string;
  subjectIcon: string;
  programme: 'Science' | 'Arts' | 'Both';
  difficulty: number; // 1-5
  estimatedMinutes: number;
  xpReward: number;
  unitId: string;
  prerequisites: string[];
  shsLevels: string[];
  suggestedLevel: string;
  steps: LessonStep[];
  checkpoints?: CheckpointConfig[];
}


export interface Unit {
  id: string;
  title: string;
  subtitle: string;
  colour: string;
  icon: string;
}

export type MathVizConfig = {
  type: 'number-line' | 'bar-chart' | 'coordinate-plane' | 'venn-diagram' | 'tree-diagram' | 'punnett-square' | 'fraction-pie';
  data?: number[];
  range?: { min: number; max: number };
  width?: number;
  height?: number;
  labels?: string[];
  [key: string]: unknown;
};



// ── Lesson data ────────────────────────────────────────────────────────────

export const ALL_LESSONS: Lesson[] = [
  // Core Mathematics SHS 1 — auto-generated from curriculum materials
  ...CORE_MATHS_SHS1_LESSONS,

  // Core Mathematics SHS 2 — auto-generated from curriculum materials
  ...CORE_MATHS2_SHS2_LESSONS,

  // Integrated Science SHS 1 — auto-generated from curriculum materials
  ...INTER_SCIENCE_SHS1_LESSONS,

  // English Language SHS 1 — auto-generated from curriculum materials
  ...ENGLISH_SHS1_LESSONS,

  // English Language SHS 2 — auto-generated from curriculum materials
  ...ENG_LANG2_SHS2_LESSONS,

  // Social Studies SHS 1 — auto-generated from curriculum materials
  ...SOCIAL_STUDIES_SHS1_LESSONS,

  // Biology SHS 1 — auto-generated from curriculum materials (Elective)
  ...BIOLOGY_SHS1_LESSONS,

  // Chemistry SHS 1 — auto-generated from curriculum materials (Elective)
  ...CHEMISTRY_SHS1_LESSONS,

  // Additional Mathematics SHS 1 — auto-generated from curriculum materials (Elective)
  ...ADD_MATHS_SHS1_LESSONS,

  // Physics SHS 1 — auto-generated from curriculum materials (Elective)
  ...PHYSICS_SHS1_LESSONS,

  // Integrated Science SHS 2 — auto-generated from curriculum materials
  ...INTER_SCIENCE_SHS2_LESSONS,

  // Social Studies SHS 2 — auto-generated from curriculum materials
  ...SOCIAL_STUDIES_SHS2_LESSONS,

  // General Science Year 1 — auto-generated
  ...GENERAL_SCIENCE_LESSONS,
];

// ── Helper functions ──────────────────────────────────────────────────────

export function getLessonById(id: string): Lesson | undefined {
  return ALL_LESSONS.find((l) => l.id === id);
}

const UNIT_MAP: Record<string, Unit> = {
  'core-maths': {
    id: 'core-maths',
    title: 'Core Mathematics',
    subtitle: 'Number & Algebra, Geometry, Statistics',
    colour: 'from-blue-500/20 via-purple-500/20 to-indigo-500/20',
    icon: '📐',
  },
  'core-english': {
    id: 'core-english',
    title: 'Core English',
    subtitle: 'Comprehension, Grammar & Literature',
    colour: 'from-emerald-500/20 via-teal-500/20 to-cyan-500/20',
    icon: '📖',
  },
  'integrated-science': {
    id: 'integrated-science',
    title: 'Integrated Science',
    subtitle: 'Biology, Chemistry & Physics',
    colour: 'from-green-500/20 via-lime-500/20 to-yellow-500/20',
    icon: '🔬',
  },
  'social-studies': {
    id: 'social-studies',
    title: 'Social Studies',
    subtitle: 'History, Geography & Governance',
    colour: 'from-orange-500/20 via-amber-500/20 to-yellow-500/20',
    icon: '🌍',
  },
  'general-science': GENERAL_SCIENCE_UNIT,
};

export function getLessonsByProgramme(programme: string | 'Science' | 'Arts' | null, shsLevel: string | null): { units: Unit[]; lessons: Lesson[] } {
  if (!programme || !shsLevel) {
    return { units: [], lessons: [] };
  }

  // Filter lessons by programme and shs level
  const filteredLessons = ALL_LESSONS.filter(
    (lesson) =>
      (lesson.programme === programme || lesson.programme === 'Both') &&
      lesson.shsLevels.includes(shsLevel)
  );

  // Get unique units from filtered lessons and map to Unit objects
  const uniqueIds = Array.from(new Set(filteredLessons.map((lesson) => lesson.unitId)));
  const units: Unit[] = uniqueIds
    .map((id) => UNIT_MAP[id])
    .filter((u): u is Unit => u !== undefined);

  return { units, lessons: filteredLessons };
}
