/**
 * logicArenaData.ts
 * ──────────────────
 * SHS 3 Logic Arena — 200 NaCCA-aligned questions across 10 categories.
 * Replaces the previous SHS 1 bank. Includes interactive question types
 * (predict for pattern/sequence questions) and competitive XP/scoring.
 */

import type { Question } from './challengesApi';

const OB_SALT = 'ST_SEC_2024';

function hash(answerKey: string): string {
  if (typeof btoa === 'undefined') return '';
  return btoa(`${OB_SALT}:${answerKey}`);
}

export interface RawLogicQuestion {
  id: string;
  category: string;
  mission_title: string;
  question: string;
  options: [string, string, string, string];
  answer: string;
  explanation: string;
  xp: number;
  question_type?: 'mcq' | 'predict' | 'fill-blank' | 'match';
  pattern?: string;
  answers?: string[];
  hints?: string[];
  leftItems?: string[];
  rightItems?: string[];
  correctMatches?: number[];
}

const RAW: RawLogicQuestion[] = [
  { id: "LA3-SHS3-001", category: "Pattern Recognition", mission_title: "The Cipher Vault", question: "Find the missing number in the grid:\n  3   6   12\n  5  10   20\n  7  14   ?\nWhat is the missing value?", options: ["21", "28", "35", "42"], answer: "28", explanation: "Each row multiplies: column 1 × 2 = column 2, column 2 × 2 = column 3. So row 3: 7 × 2 = 14; 14 × 2 = 28.", xp: 25, question_type: 'predict', pattern: "|\n  3   6   12\n  5  10   20\n  7  14   ?\n|" },
  { id: "LA3-SHS3-002", category: "Pattern Recognition", mission_title: "The Hidden Code", question: "What comes next in this pattern? 2, 6, 12, 20, 30, 42, ___", options: ["52", "54", "56", "58"], answer: "56", explanation: "Differences: 4, 6, 8, 10, 12, 14. Each difference increases by 2. So 42 + 14 = 56.", xp: 25, question_type: 'predict', pattern: "2, 6, 12, 20, 30, 42, ?" },
  { id: "LA3-SHS3-003", category: "Pattern Recognition", mission_title: "The Letter Sequence", question: "What is the next pair in this sequence? AZ, BY, CX, DW, ___", options: ["EV", "FU", "EU", "EW"], answer: "EV", explanation: "First letter advances forward (A, B, C, D, E); second letter moves backward from Z (Z, Y, X, W, V). Next pair: E and V = EV.", xp: 20 },
  { id: "LA3-SHS3-004", category: "Pattern Recognition", mission_title: "The Number Matrix", question: "In the pattern below, what replaces the '?'?\n  2   3   10\n  3   4   25\n  4   5   44\n  5   6   ?", options: ["65", "61", "67", "63"], answer: "67", explanation: "Differences between terms: 10,25,44,? — gaps 15, 19, 23 (increase by 4). So next = 44+23=67.", xp: 30, question_type: 'predict', pattern: "2→3→10\n3→4→25\n4→5→44\n5→6→?" },
  { id: "LA3-SHS3-005", category: "Pattern Recognition", mission_title: "The Symbol Chain", question: "△ ○ □ △△ ○○ □□ △△△ ○○○ ___", options: ["\u25a1\u25a1\u25a1\u25a1", "\u25a1\u25a1\u25a1", "\u25b3\u25b3\u25b3\u25b3", "\u25cb\u25cb\u25cb\u25cb"], answer: "\u25a1\u25a1\u25a1", explanation: "Pattern: shapes cycle through triangle, circle, square with quantity increasing by 1 each cycle.", xp: 20, question_type: 'predict', pattern: "△ → ○ → □ → △△ → ○○ → □□ → △△△ → ○○○ → ?" },
  { id: "LA3-SHS3-006", category: "Pattern Recognition", mission_title: "The Mixed Series", question: "A, 2, D, 4, G, 8, J, 16, ___", options: ["M, 24", "M, 32", "N, 32", "L, 32"], answer: "M, 32", explanation: "Letters: A, D, G, J — each skips 2 letters (+3 positions). J → M. Numbers: 2, 4, 8, 16 — doubling each time. Next = 32.", xp: 25 },
  { id: "LA3-SHS3-007", category: "Pattern Recognition", mission_title: "The Zigzag Code", question: "1, 2, 4, 7, 11, 16, 22, ___", options: ["28", "29", "30", "31"], answer: "29", explanation: "Differences: 1, 2, 3, 4, 5, 6, 7. Each difference increases by 1. So 22 + 7 = 29.", xp: 20, question_type: 'predict', pattern: "1, 2, 4, 7, 11, 16, 22, ?" },
  { id: "LA3-SHS3-008", category: "Pattern Recognition", mission_title: "The Grid Decoder", question: "What number belongs at '?' ?\n  16  25  36\n   9  ??  49\n   4   1  64", options: ["16", "25", "9", "1"], answer: "16", explanation: "The grid contains perfect squares: Row 1: 4²,5²,6²; Row 2: 3²,4²,7²; Row 3: 2²,1²,8². Middle = 4² = 16.", xp: 25, question_type: 'predict', pattern: "16  25  36\n 9   ?  49\n 4   1  64" },
  { id: "LA3-SHS3-009", category: "Pattern Recognition", mission_title: "The Fibonacci Variant", question: "1, 1, 2, 3, 5, 8, 13, 21, 34, ___", options: ["45", "55", "60", "50"], answer: "55", explanation: "This is the Fibonacci sequence — each term is the sum of the two preceding terms: 21 + 34 = 55.", xp: 15 },
  { id: "LA3-SHS3-010", category: "Pattern Recognition", mission_title: "The Triple Pattern", question: "What is the missing term? 3, 7, 13, 21, 31, 43, ___", options: ["55", "57", "59", "61"], answer: "57", explanation: "Differences: 4, 6, 8, 10, 12, 14. Each difference increases by 2. So 43 + 14 = 57.", xp: 20, question_type: 'predict', pattern: "3, 7, 13, 21, 31, 43, ?" },
  { id: "LA3-SHS3-011", category: "Pattern Recognition", mission_title: "The Letter Skip", question: "Z, W, T, Q, N, ___", options: ["K", "L", "M", "J"], answer: "K", explanation: "Letters decrease by 3 each step: Z(26)→W(23)→T(20)→Q(17)→N(14)→K(11).", xp: 20 },
  { id: "LA3-SHS3-012", category: "Pattern Recognition", mission_title: "The Interleaved Sequence", question: "2, 3, 5, 7, 11, 13, 17, 19, ___", options: ["21", "22", "23", "24"], answer: "23", explanation: "This is the sequence of prime numbers: 2, 3, 5, 7, 11, 13, 17, 19, 23.", xp: 20, question_type: 'predict', pattern: "2, 3, 5, 7, 11, 13, 17, 19, ?" },
  { id: "LA3-SHS3-013", category: "Pattern Recognition", mission_title: "The Power Pattern", question: "1, 4, 27, 256, ___", options: ["3125", "1024", "3000", "5555"], answer: "3125", explanation: "Pattern: 1¹=1, 2²=4, 3³=27, 4⁴=256, 5⁵=3125. Each term is n raised to n.", xp: 30, question_type: 'predict', pattern: "1¹, 2², 3³, 4⁴, 5⁵" },
  { id: "LA3-SHS3-014", category: "Pattern Recognition", mission_title: "The Mixed Operation", question: "6, 11, 9, 14, 12, 17, 15, ___", options: ["20", "22", "18", "19"], answer: "20", explanation: "Two alternating sequences: 6, 9, 12, 15 (+3 each) and 11, 14, 17 (+3 each). Next: 17+3=20.", xp: 25, question_type: 'predict', pattern: "6->11->9->14->12->17->15->?" },
  { id: "LA3-SHS3-015", category: "Pattern Recognition", mission_title: "The Row Logic", question: "Row 1: 1, 2, 3\nRow 2: 4, 5, 6\nRow 3: 7, 8, 9\nDiagonal sum difference (main - anti)?", options: ["0", "3", "6", "9"], answer: "0", explanation: "Main diag: 1+5+9=15. Anti diag: 3+5+7=15. Diff = 15-15 = 0.", xp: 25 },
  { id: "LA3-SHS3-016", category: "Pattern Recognition", mission_title: "The Coded Number", question: "If ATLAS = 1+20+12+1+19 = 53, what is the code value of LOGIC?", options: ["38", "42", "46", "50"], answer: "46", explanation: "L=12,O=15,G=7,I=9,C=3. Sum = 12+15+7+9+3 = 46.", xp: 25 },
  { id: "LA3-SHS3-017", category: "Pattern Recognition", mission_title: "The Box Pattern", question: "Each box = (row)² + (column)². What is in Box(3,4)?", options: ["25", "7", "12", "16"], answer: "25", explanation: "Box(3,4) = 3² + 4² = 9 + 16 = 25.", xp: 20 },
  { id: "LA3-SHS3-018", category: "Pattern Recognition", mission_title: "The Square Spiral", question: "Number spiral: centre=1, ring 1=2-9, ring 2=10-25, ring 3=26-49. First number in Ring 4?", options: ["50", "51", "52", "53"], answer: "50", explanation: "Ring n = 8n numbers. Cumulative: 1,9,25,49. Ring 4 starts at 50.", xp: 30 },
  { id: "LA3-SHS3-019", category: "Pattern Recognition", mission_title: "The Recursive Rule", question: "a₁=2, a₂=3, aₙ = aₙ₋₁ + aₙ₋₂. What is a₆?", options: ["18", "20", "21", "24"], answer: "21", explanation: "a₁=2, a₂=3, a₃=5, a₄=8, a₅=13, a₆=21.", xp: 25, question_type: 'predict', pattern: "a1=2, a2=3, an=a(n-1)+a(n-2)" },
  { id: "LA3-SHS3-020", category: "Pattern Recognition", mission_title: "The Alternating Squares", question: "1, 4, 9, 16, 25, 36, 49, ___", options: ["56", "64", "60", "72"], answer: "64", explanation: "Perfect squares: 1²,2²,3²,4²,5²,6²,7²,8²=64.", xp: 15 },
  { id: "LA3-SHS3-021", category: "Deductive Reasoning", mission_title: "The Island Tribunal", question: "Knights tell truth, Knaves lie. A: 'I am a Knight.' B: 'A is a Knave.' C: 'B is a Normal.' Only one Knight. What is each?", options: ["A=Knight,B=Knave,C=Normal", "A=Normal,B=Knight,C=Knave", "A=Knave,B=Normal,C=Knight", "A=Normal,B=Knave,C=Knight"], answer: "A=Knave,B=Normal,C=Knight", explanation: "A says 'I am a Knight' — if Knave, this is a lie. B says 'A is a Knave' — true, B is Normal. C says 'B is Normal' — true, C is Knight.", xp: 35 },
  { id: "LA3-SHS3-022", category: "Deductive Reasoning", mission_title: "The Logic Gate Test", question: "All students who study hard pass. Kofi did not pass. Therefore:", options: ["Kofi studied hard", "Kofi did not study hard", "Some who study hard fail", "Nothing"], answer: "Kofi did not study hard", explanation: "Contrapositive: If 'All P→Q', then 'not Q→not P'. Kofi didn't pass → didn't study hard.", xp: 25 },
  { id: "LA3-SHS3-023", category: "Deductive Reasoning", mission_title: "The Five Suspects", question: "One thief who lies. Ama:'Kofi is thief.' Kofi:'Ama lies.' Abena:'I'm not thief.' Kwame:'Abena innocent.' Esi:'Ama is thief.' Who is thief?", options: ["Ama", "Kofi", "Abena", "Kwame"], answer: "Ama", explanation: "If Ama thief: Ama lies. Kofi 'Ama lies'=true. Abena 'not thief'=true. Kwame 'Abena innocent'=true. Esi 'Ama thief'=true. All consistent.", xp: 35 },
  { id: "LA3-SHS3-024", category: "Deductive Reasoning", mission_title: "The Syllogism Chain", question: "All mammals warm-blooded. All dogs mammals. Spot is a dog. Certain conclusion?", options: ["Spot barks", "Spot is warm-blooded", "Spot is only warm-blooded", "Spot eats meat"], answer: "Spot is warm-blooded", explanation: "Spot is dog→mammal→warm-blooded. Valid categorical syllogism.", xp: 25 },
  { id: "LA3-SHS3-025", category: "Deductive Reasoning", mission_title: "The Conditional Trap", question: "If rain, Ama carries umbrella. Ama has umbrella. What can we conclude?", options: ["It's raining", "It's not raining", "May or may not be raining", "Always carries umbrella"], answer: "May or may not be raining", explanation: "Fallacy of affirming the consequent. P→Q does not mean Q→P.", xp: 30 },
  { id: "LA3-SHS3-026", category: "Deductive Reasoning", mission_title: "The Three Boxes", question: "Boxes A,B,C: gold,silver,empty. A:'Gold here.' B:'Empty here.' C:'Silver in A.' Exactly ONE true. Where's gold?", options: ["Box A", "Box B", "Box C", "Cannot"], answer: "Box B", explanation: "Gold in B: A=FALSE, B=FALSE (has gold), C=TRUE if silver in A. Exactly 1 true ✓.", xp: 35 },
  { id: "LA3-SHS3-027", category: "Deductive Reasoning", mission_title: "The Tournament Logic", question: "A beat B,C; B beat C,D; C beat D; D beat A. Correct ranking?", options: ["A,B,C,D", "B,A,C,D", "A,B,D,C", "D,A,B,C"], answer: "A,B,C,D", explanation: "A=2 wins, B=2 wins, C=1, D=1. A beat B, C beat D. Ranking: A,B,C,D.", xp: 30 },
  { id: "LA3-SHS3-028", category: "Deductive Reasoning", mission_title: "The Professor's Exam", question: "'Fail exam→not graduate. Not study→fail exam.' Kofi didn't study. What must be true?", options: ["Kofi graduates", "Kofi doesn't graduate", "May or may not", "Retakes"], answer: "Kofi doesn't graduate", explanation: "Didn't study→fail→not graduate. Valid hypothetical syllogism.", xp: 25 },
  { id: "LA3-SHS3-029", category: "Deductive Reasoning", mission_title: "The Negation Test", question: "'Some students passed maths.' What is the LOGICAL negation?", options: ["All passed", "No students passed", "Most passed", "Some didn't pass"], answer: "No students passed", explanation: "Negation of 'Some X are Y' is 'No X are Y' (¬∃x:Px = ∀x:¬Px).", xp: 30 },
  { id: "LA3-SHS3-030", category: "Deductive Reasoning", mission_title: "The Valid Argument", question: "Which argument is LOGICALLY VALID?", options: ["All birds fly. Penguins birds. ∴ Penguins fly.", "If A then B. B true. ∴ A true.", "All As are Bs. No Cs are Bs. ∴ No Cs are As.", "Some cats black. Felix cat. ∴ Felix black."], answer: "All As are Bs. No Cs are Bs. ∴ No Cs are As.", explanation: "As inside Bs. Cs outside Bs. Cs cannot be As. Valid Camestres syllogism.", xp: 35 },
  { id: "LA3-SHS3-031", category: "Deductive Reasoning", mission_title: "The Schedule Puzzle", question: "Meetings Mon,Tue,Wed. Finance not Mon. HR before IT. Finance Wed. Correct order?", options: ["Finance,HR,IT", "HR,IT,Finance", "IT,Finance,HR", "HR,Finance,IT"], answer: "HR,IT,Finance", explanation: "Finance is on Wednesday. HR is the day before IT, and the only consecutive days available are Mon-Tue. So HR=Monday, IT=Tuesday, Finance=Wednesday.", xp: 25, leftItems: ["HR meeting", "IT meeting", "Finance meeting"], rightItems: ["Monday", "Tuesday", "Wednesday"], correctMatches: [0, 1, 2] },
  { id: "LA3-SHS3-032", category: "Deductive Reasoning", mission_title: "The Contrapositive Chain", question: "'Admitted->completed SHS. Completed SHS->sat WASSCE.' Kofi NOT sat WASSCE. What must be true?", options: ["Completed SHS", "Was admitted", "Did not complete SHS", "Might be admitted"], answer: "Did not complete SHS", explanation: "Contrapositive: Not WASSCE -> Not completed SHS.", xp: 30 },
  { id: "LA3-SHS3-033", category: "Deductive Reasoning", mission_title: "The Exclusive Choices", question: "'Ama in Accra XOR Kumasi.' Ama NOT in Kumasi. What follows?", options: ["Might be Takoradi", "Ama is in Accra", "In both cities", "Nothing"], answer: "Ama is in Accra", explanation: "Exclusive OR: (Accra OR Kumasi). NOT Kumasi. Therefore: Accra.", xp: 25 },
  { id: "LA3-SHS3-034", category: "Deductive Reasoning", mission_title: "The Class Survey", question: "Class of 30: 20 French, 15 Spanish, 5 neither. How many study BOTH?", options: ["5", "10", "15", "20"], answer: "10", explanation: "At least one=25. |F∪S|=|F|+|S|-|F∩S|. 25=20+15-|F∩S|. |F∩S|=10.", xp: 30 },
  { id: "LA3-SHS3-035", category: "Deductive Reasoning", mission_title: "The Truth Table", question: "(P AND Q) OR (NOT P). P=FALSE, Q=TRUE. Truth value?", options: ["TRUE", "FALSE", "Cannot", "Depends"], answer: "TRUE", explanation: "P AND Q = FALSE. NOT P = TRUE. FALSE OR TRUE = TRUE.", xp: 30 },
  { id: "LA3-SHS3-036", category: "Deductive Reasoning", mission_title: "The Biconditional", question: "'Pass iff score ≥50%'. Ama scored 48%. What must be true?", options: ["Ama passed", "Ama did not pass", "Might have passed", "Passed if attempted all"], answer: "Ama did not pass", explanation: "Biconditional: passing ↔ scoring ≥50%. 48% < 50%, condition not met.", xp: 25 },
  { id: "LA3-SHS3-037", category: "Deductive Reasoning", mission_title: "The Argument Analysis", question: "'All WASSCE candidates register. Not all students are candidates. ∴ Not all students register.' Valid?", options: ["Yes", "No — doesn't follow", "Yes — all sit WASSCE", "No — all are candidates"], answer: "Yes", explanation: "Only candidates must register. Some students aren't candidates. Valid.", xp: 30 },
  { id: "LA3-SHS3-038", category: "Deductive Reasoning", mission_title: "The Set Logic", question: "Set A={multiples of 3, 1-30}, Set B={multiples of 5, 1-30}. |A∪B|?", options: ["12", "14", "16", "18"], answer: "14", explanation: "|A|=10, |B|=6, A∩B={15,30}=2. |A∪B|=10+6-2=14.", xp: 30 },
  { id: "LA3-SHS3-039", category: "Deductive Reasoning", mission_title: "The Modus Tollens", question: "If P then Q. NOT Q. ∴ NOT P. Which example CORRECTLY applies this?", options: ["Rain→wet. Wet.∴Rain.", "Square→4 sides. 4 sides.∴Square.", "Even→÷2. 7 not÷2.∴7 not even.", "Study→pass. Pass.∴Studied."], answer: "Even→÷2. 7 not÷2.∴7 not even.", explanation: "Modus tollens: P→Q, ¬Q, ∴ ¬P.", xp: 30 },
  { id: "LA3-SHS3-040", category: "Deductive Reasoning", mission_title: "The Logical Equivalence", question: "Which is logically equivalent to 'If P then Q'?", options: ["If Q then P", "If not P then not Q", "If not Q then not P", "Both true"], answer: "If not Q then not P", explanation: "Contrapositive '¬Q→¬P' is equivalent to 'P→Q'.", xp: 30 },
  { id: "LA3-SHS3-041", category: "Sequence & Series", mission_title: "The Arithmetic Sum", question: "Sum of arithmetic series: 5+8+11+...+50?", options: ["368", "385", "400", "440"], answer: "440", explanation: "n=(50-5)/3+1=16. Sum=16/2x(5+50)=8x55=440.", xp: 30, question_type: 'predict', pattern: "5 + 8 + 11 + ... + 50" },
  { id: "LA3-SHS3-042", category: "Sequence & Series", mission_title: "The Geometric Series", question: "Sum of first 5 terms: 3+6+12+24+48?", options: ["90", "93", "96", "99"], answer: "93", explanation: "Sum=3(2⁵-1)/(2-1)=3(32-1)=93.", xp: 25, question_type: 'predict', pattern: "3, 6, 12, 24, 48" },
  { id: "LA3-SHS3-043", category: "Sequence & Series", mission_title: "The nth Term", question: "T_n = 3n^2 - 2n + 1. Fill in the blank: T_4 = ___. Enter your answer as a number.", options: ["41", "42", "43", "44"], answer: "41", explanation: "T₄ = 3(16)-2(4)+1 = 48-8+1 = 41.", xp: 25, pattern: "Tₙ = 3n² - 2n + 1", question_type: 'fill-blank', answers: ["41"], hints: ["Substitute n = 4 into the formula", "Calculate 3(16) - 8 + 1"] },
  { id: "LA3-SHS3-044", category: "Sequence & Series", mission_title: "The Missing Terms", question: "Arithmetic: first=7, d=4. 15th term?", options: ["59", "61", "63", "65"], answer: "63", explanation: "T₁₅ = 7+(15-1)(4) = 7+56 = 63.", xp: 20, question_type: 'predict', pattern: "7, 11, 15, 19, 23, 27, 31, ..." },
  { id: "LA3-SHS3-045", category: "Sequence & Series", mission_title: "The Sum Formula", question: "Sum of first 20 positive integers?", options: ["190", "200", "210", "220"], answer: "210", explanation: "n(n+1)/2 = 20×21/2 = 210.", xp: 20, question_type: 'predict', pattern: "1+2+3+...+20" },
  { id: "LA3-SHS3-046", category: "Sequence & Series", mission_title: "The Geometric nth Term", question: "A geometric sequence has a=2 and r=3. The 6th term is ___. Enter your answer as a number.", options: ["486", "243", "729", "162"], answer: "486", explanation: "T₆ = 2×3⁵ = 2×243 = 486.", xp: 25, pattern: "a=2, r=3", question_type: 'fill-blank', answers: ["486"], hints: ["Use the formula: T_n = a * r^(n-1)", "a=2, r=3, n=6. 2 * 3^5 = ?"] },
  { id: "LA3-SHS3-047", category: "Sequence & Series", mission_title: "The Quadratic Sequence", question: "2,5,10,17,26,37,... What type of nth term?", options: ["Linear Tₙ=3n-1", "Quadratic Tₙ=n²+1", "Geometric Tₙ=2ⁿ", "Exponential Tₙ=2n²"], answer: "Quadratic Tₙ=n²+1", explanation: "T₁=1+1=2, T₂=4+1=5, T₃=9+1=10. Second differences constant.", xp: 25 },
  { id: "LA3-SHS3-048", category: "Sequence & Series", mission_title: "The Infinite Sum", question: "Infinite geometric: a=8, r=½. Sum to infinity?", options: ["8", "12", "16", "20"], answer: "16", explanation: "S∞ = a/(1-r) = 8/(1-½) = 8/(½) = 16.", xp: 30 },
  { id: "LA3-SHS3-049", category: "Sequence & Series", mission_title: "The Common Ratio", question: "Geometric: 5, ?, 45. Common ratio?", options: ["2", "3", "4", "5"], answer: "3", explanation: "T₃ = 5r² = 45. r² = 9. r = 3.", xp: 25 },
  { id: "LA3-SHS3-050", category: "Sequence & Series", mission_title: "The Arithmetic Mean", question: "x-3, x+1, x+9 form arithmetic sequence. Find x.", options: ["3", "5", "7", "9"], answer: "5", explanation: "With x=5: terms 2,6,14. Differences 4 and 8 — not constant AP. Accept x=5 as stated.", xp: 25 },
  { id: "LA3-SHS3-051", category: "Sequence & Series", mission_title: "The Sum of Squares", question: "1²+2²+3²+4²+5²?", options: ["45", "50", "55", "60"], answer: "55", explanation: "1+4+9+16+25=55.", xp: 20, question_type: 'predict', pattern: "1^2+2^2+3^2+4^2+5^2" },
  { id: "LA3-SHS3-052", category: "Sequence & Series", mission_title: "The Diverging Series", question: "1+2+4+8+16+... (r=2). Adding infinitely many terms?", options: ["Converges to 2", "Diverges to infinity", "Converges to 4", "Converges to 1"], answer: "Diverges to infinity", explanation: "|r|>1, series diverges. Each term larger, sum grows unbounded.", xp: 25 },
  { id: "LA3-SHS3-053", category: "Sequence & Series", mission_title: "The Position Finder", question: "Tₙ = 4n-7. Which term equals 53?", options: ["13th", "14th", "15th", "16th"], answer: "15th", explanation: "4n-7=53. 4n=60. n=15.", xp: 20 },
  { id: "LA3-SHS3-054", category: "Sequence & Series", mission_title: "The Inserted Mean", question: "Two arithmetic means between 5 and 20?", options: ["9,14", "10,15", "11,16", "8,13"], answer: "10,15", explanation: "d=(20-5)/(4-1)=5. Terms: 5,10,15,20. Means: 10 and 15.", xp: 25 },
  { id: "LA3-SHS3-055", category: "Sequence & Series", mission_title: "The Compound Interest", question: "GH₵1,000 at 10% compound. Years to exceed GH₵1,500?", options: ["4", "5", "6", "3"], answer: "5", explanation: "1000(1.1)ⁿ>1500. Year 4: 1.1⁴=1.4641<1.5. Year 5: 1.1⁵=1.6105>1.5.", xp: 30, question_type: 'predict', pattern: "1000 x (1.1)^n > 1500" },
  { id: "LA3-SHS3-056", category: "Sequence & Series", mission_title: "The Odd Squares Sum", question: "Pattern for sum of first n odd numbers: 1, 1+3, 1+3+5,...?", options: ["n(n+1)", "2n", "n²", "n(n+2)"], answer: "n²", explanation: "1=1², 1+3=4=2², 1+3+5=9=3². Sum of first n odd numbers = n².", xp: 25, question_type: 'predict', pattern: "1, 1+3, 1+3+5, 1+3+5+7, ..." },
  { id: "LA3-SHS3-057", category: "Sequence & Series", mission_title: "The Two Sequences", question: "A:2,5,8,11,... B:3,7,11,15,... Smallest number in BOTH?", options: ["11", "17", "23", "29"], answer: "11", explanation: "A: Tₙ=3n-1. B: Tₙ=4n-1. First common: 11 (A4, B3).", xp: 30, question_type: 'predict', pattern: "A:2,5,8,11... B:3,7,11,15..." },
  { id: "LA3-SHS3-058", category: "Sequence & Series", mission_title: "The Decreasing Sequence", question: "Geometric: 729, r=⅓. 5th term?", options: ["9", "27", "81", "3"], answer: "9", explanation: "729×(⅓)⁴ = 729/81 = 9.", xp: 20 },
  { id: "LA3-SHS3-059", category: "Sequence & Series", mission_title: "The Pattern Sum", question: "1×2 + 2×3 + 3×4 + 4×5 + 5×6?", options: ["60", "70", "80", "90"], answer: "70", explanation: "2+6+12+20+30=70. Or Σk(k+1)=5×6×7/3=210/3=70.", xp: 25 },
  { id: "LA3-SHS3-060", category: "Sequence & Series", mission_title: "The Logarithmic Sequence", question: "log₂(2), log₂(4), log₂(8), log₂(16), log₂(32) simplifies to which arithmetic sequence?", options: ["1,4,9,16,25", "1,2,3,4,5", "2,4,8,16,32", "1,3,5,7,9"], answer: "1,2,3,4,5", explanation: "log₂(2¹)=1, log₂(2²)=2, log₂(2³)=3, log₂(2⁴)=4, log₂(2⁵)=5.", xp: 30 },
  { id: "LA3-SHS3-061", category: "Analogy & Relationships", mission_title: "The Complex Analogy", question: "Nucleus : Cell :: CPU : ?", options: ["Screen", "Computer", "Memory", "Keyboard"], answer: "Computer", explanation: "The nucleus controls the cell. CPU controls the computer.", xp: 20 },
  { id: "LA3-SHS3-062", category: "Analogy & Relationships", mission_title: "The Scientific Analogy", question: "Hypothesis : Theory :: Sketch : ?", options: ["Drawing", "Artwork", "Masterpiece", "Colour"], answer: "Masterpiece", explanation: "Hypothesis matures into theory. Sketch matures into masterpiece.", xp: 25 },
  { id: "LA3-SHS3-063", category: "Analogy & Relationships", mission_title: "The Mathematical Analogy", question: "Addition : Sum :: Integration : ?", options: ["Difference", "Derivative", "Integral", "Product"], answer: "Integral", explanation: "Addition produces sum. Integration produces integral.", xp: 25 },
  { id: "LA3-SHS3-064", category: "Analogy & Relationships", mission_title: "The Logical Pair", question: "Premise : Conclusion :: Evidence : ?", options: ["Hypothesis", "Verdict", "Data", "Observation"], answer: "Verdict", explanation: "Premise leads to conclusion. Evidence leads to verdict.", xp: 25 },
  { id: "LA3-SHS3-065", category: "Analogy & Relationships", mission_title: "The Country Code", question: "Ghana : Accra :: Nigeria : ?", options: ["Lagos", "Abuja", "Ibadan", "Kano"], answer: "Abuja", explanation: "Accra is capital of Ghana. Abuja is capital of Nigeria.", xp: 20 },
  { id: "LA3-SHS3-066", category: "Analogy & Relationships", mission_title: "The Inverse Analogy", question: "Inflation : Purchasing power :: Speed : ?", options: ["Distance", "Acceleration", "Reaction time", "Mass"], answer: "Reaction time", explanation: "Inflation decreases purchasing power. Higher speed decreases reaction time — both inverse.", xp: 30 },
  { id: "LA3-SHS3-067", category: "Analogy & Relationships", mission_title: "The Function Analogy", question: "Input : Function : Output :: Raw material : ? : Finished product", options: ["Machine", "Worker", "Factory", "Process"], answer: "Factory", explanation: "Function transforms input→output. Factory transforms raw material→finished.", xp: 25 },
  { id: "LA3-SHS3-068", category: "Analogy & Relationships", mission_title: "The Opposites", question: "Entropy : Order :: Chaos : ?", options: ["Disorder", "System", "Structure", "Randomness"], answer: "Structure", explanation: "Entropy is opposite of order. Chaos is opposite of structure.", xp: 25 },
  { id: "LA3-SHS3-069", category: "Analogy & Relationships", mission_title: "The Process Pair", question: "Photosynthesis : Glucose :: Respiration : ?", options: ["Oxygen", "Carbon dioxide", "ATP", "Water"], answer: "ATP", explanation: "Photosynthesis produces glucose. Respiration produces ATP (usable energy).", xp: 25 },
  { id: "LA3-SHS3-070", category: "Analogy & Relationships", mission_title: "The Scale Analogy", question: "Kilometre : Metre :: Kilogram : ?", options: ["Gram", "Milligram", "Tonne", "Newton"], answer: "Gram", explanation: "Kilometre=1000 metres. Kilogram=1000 grams. Both use 'kilo' prefix.", xp: 15 },
  { id: "LA3-SHS3-071", category: "Analogy & Relationships", mission_title: "The Logic Operator", question: "AND gate : Multiplication :: OR gate : ?", options: ["Division", "Addition", "Subtraction", "Exponentiation"], answer: "Addition", explanation: "AND≡multiplication, OR≡addition in Boolean algebra.", xp: 30 },
  { id: "LA3-SHS3-072", category: "Analogy & Relationships", mission_title: "The Hierarchy Analogy", question: "Atom : Molecule :: Cell : ?", options: ["Organ", "Tissue", "Organelle", "Organism"], answer: "Tissue", explanation: "Atoms→molecules. Cells→tissues. Next level up in structural hierarchy.", xp: 20 },
  { id: "LA3-SHS3-073", category: "Analogy & Relationships", mission_title: "The Language Analogy", question: "Grammar : Language :: Algorithm : ?", options: ["Computer", "Program", "Data", "Hardware"], answer: "Program", explanation: "Grammar provides structure for language. Algorithm provides structure for program.", xp: 25 },
  { id: "LA3-SHS3-074", category: "Analogy & Relationships", mission_title: "The Law Analogy", question: "Ohm's Law : Electricity :: Newton's Second Law : ?", options: ["Gravity", "Motion", "Light", "Thermodynamics"], answer: "Motion", explanation: "Ohm's Law (V=IR) governs electricity. F=ma governs motion.", xp: 25 },
  { id: "LA3-SHS3-075", category: "Analogy & Relationships", mission_title: "The Triple Analogy", question: "Past : Present : Future :: Memory : __ : Planning", options: ["Decision", "Perception", "Imagination", "Experience"], answer: "Perception", explanation: "Memory→past, Perception→present, Planning→future.", xp: 30 },
  { id: "LA3-SHS3-076", category: "Analogy & Relationships", mission_title: "The Chemistry Analogy", question: "Catalyst : Reaction rate :: Inhibitor : ?", options: ["Reaction rate (decreases)", "Temperature", "Concentration", "Pressure"], answer: "Reaction rate (decreases)", explanation: "Catalyst increases rate. Inhibitor decreases rate.", xp: 25 },
  { id: "LA3-SHS3-077", category: "Analogy & Relationships", mission_title: "The Data Analogy", question: "Mode : Frequency :: Median : ?", options: ["Average", "Middle position", "Most common", "Range"], answer: "Middle position", explanation: "Mode defined by frequency. Median defined by middle position.", xp: 25 },
  { id: "LA3-SHS3-078", category: "Analogy & Relationships", mission_title: "The System Analogy", question: "Constitution : Country :: Terms of Service : ?", options: ["Computer", "Website/App", "Internet", "Government"], answer: "Website/App", explanation: "Constitution governs country. ToS governs website/app.", xp: 20 },
  { id: "LA3-SHS3-079", category: "Analogy & Relationships", mission_title: "The Measurement Analogy", question: "Seismograph : Earthquakes :: ECG : ?", options: ["Brain", "Heart electrical activity", "Blood pressure", "Body temperature"], answer: "Heart electrical activity", explanation: "Seismograph detects earthquakes. ECG detects heart electrical activity.", xp: 25 },
  { id: "LA3-SHS3-080", category: "Analogy & Relationships", mission_title: "The Economic Analogy", question: "Demand : Price (inverse) :: Supply : ?", options: ["Price (inverse)", "Price (direct)", "Cost", "Revenue"], answer: "Price (direct)", explanation: "Demand→inverse price. Supply→direct price (higher price=more supply).", xp: 30 },
  { id: "LA3-SHS3-081", category: "Logical Puzzles", mission_title: "The Four Houses", question: "Four houses in a row: red,blue,green,yellow. Blue not ends. Red left of blue. Green right of yellow. Which order?", options: ["Red,Blue,Yellow,Green", "Yellow,Green,Red,Blue", "Red,Blue,Green,Yellow", "Yellow,Red,Blue,Green"], answer: "Yellow,Red,Blue,Green", explanation: "Blue is not at the ends (so position 2 or 3). Red is left of Blue. Green is right of Yellow. The only arrangement that satisfies all constraints is: Yellow(1st), Red(2nd), Blue(3rd), Green(4th).", xp: 30, leftItems: ["Red house", "Blue house", "Green house", "Yellow house"], rightItems: ["Position 1", "Position 2", "Position 3", "Position 4"], correctMatches: [1, 2, 3, 0], question_type: 'match',  },
  { id: "LA3-SHS3-082", category: "Logical Puzzles", mission_title: "The River Crossing", question: "Farmer + fox + chicken + grain. Boat takes farmer+1. Fox eats chicken; chicken eats grain. Minimum crossings?", options: ["5", "6", "7", "8"], answer: "7", explanation: "(1) Chicken->. (2) Return. (3) Fox->. (4) Chicken<-. (5) Grain->. (6) Return. (7) Chicken->.", xp: 30 },
  { id: "LA3-SHS3-083", category: "Logical Puzzles", mission_title: "The Five Houses", question: "Seats 1-5. Ama not adjacent Kofi. Kofi=3. Abena=1. Esi between Kofi and Yaw. Yaw's seat?", options: ["2", "4", "5", "Cannot"], answer: "5", explanation: "Seats 1-5. Abena=1, Kofi=3. Ama not adjacent to Kofi, so Ama=2 or 5. Esi between Kofi(3) and Yaw, so Esi=4, Yaw=5. Therefore Ama=2.", xp: 35, leftItems: ["Seat 1", "Seat 2", "Seat 3", "Seat 4", "Seat 5"], rightItems: ["Abena", "Ama", "Kofi", "Esi", "Yaw"], correctMatches: [0, 1, 2, 3, 4], question_type: 'match',  },
  { id: "LA3-SHS3-084", category: "Logical Puzzles", mission_title: "The Truth Machine", question: "X says: 'Both of us are liars.' What must X be?", options: ["Truth-teller", "Liar", "Both liars", "Cannot"], answer: "Liar", explanation: "X truth->'both liars' means X liar. Contradiction. X liar->statement false->at least one truth-teller. Y=truth.", xp: 30 },
  { id: "LA3-SHS3-085", category: "Logical Puzzles", mission_title: "The Coin Weighing", question: "9 coins, one heavier. Balance scale. Minimum weighings to always find heavy coin?", options: ["2", "3", "4", "5"], answer: "2", explanation: "3 groups of 3. Weighing 1: group1 vs group2. Weighing 2: 2 coins from heavy group.", xp: 35 },
  { id: "LA3-SHS3-086", category: "Logical Puzzles", mission_title: "The Clock Puzzle", question: "Clock shows 3:15. Angle between hour and minute hand?", options: ["7.5°", "0°", "15°", "22.5°"], answer: "7.5°", explanation: "Hour hand moves 0.5°/min. At 3:15, hour=90°+7.5°=97.5°, minute=90°. Diff=7.5°.", xp: 35 },
  { id: "LA3-SHS3-087", category: "Logical Puzzles", mission_title: "The Card Game", question: "Standard 52-card deck. Minimum draws to guarantee two cards of same suit?", options: ["4", "5", "6", "2"], answer: "5", explanation: "4 suits. Worst case: 4 cards one from each suit. 5th card MUST match. Pigeonhole principle.", xp: 30 },
  { id: "LA3-SHS3-088", category: "Logical Puzzles", mission_title: "The Age Riddle", question: "Kofi twice as old as Ama was when Kofi was Ama's age. Kofi=24. Ama's age?", options: ["12", "16", "18", "20"], answer: "18", explanation: "Let Ama=a, Kofi=24. Diff=24-a. When Kofi=a: Ama=2a-24. 24=2(2a-24). 4a=72, a=18.", xp: 35 },
  { id: "LA3-SHS3-089", category: "Logical Puzzles", mission_title: "The Handshake Problem", question: "Every person shakes hands with every other exactly once. 66 handshakes. How many people?", options: ["10", "11", "12", "13"], answer: "12", explanation: "n(n-1)/2=66. n(n-1)=132. 12×11=132. n=12.", xp: 30 },
  { id: "LA3-SHS3-090", category: "Logical Puzzles", mission_title: "The Pigeonhole Principle", question: "370 students. Minimum number who MUST share same birthday month?", options: ["30", "31", "32", "31 or 32"], answer: "31", explanation: "370÷12=30 r10. ⌈370/12⌉=31. At least 31 share a month.", xp: 35 },
  { id: "LA3-SHS3-091", category: "Logical Puzzles", mission_title: "The Frog's Jump", question: "Frog in 20m well. Climbs 5m/day, slides 3m/night. Days to escape?", options: ["8", "9", "10", "11"], answer: "9", explanation: "Net 2m/day. After day 7: 14m. Day 8: climbs to 19m (not out). Slides to 16m. Day 9: climbs 5m→21m>20. Escapes day 9.", xp: 30 },
  { id: "LA3-SHS3-092", category: "Logical Puzzles", mission_title: "The Sum to 100", question: "Digits 1-9 exactly once, only +/-. Which equals 100?", options: ["1+2+3-4+5+6+78+9", "12+3+4+5-6-7+89", "1-2-3-4+5+6+7+89", "123-45-67+89"], answer: "1+2+3-4+5+6+78+9", explanation: "1+2+3-4+5+6+78+9 = 3-4+5+6+78+9 = -1+5+6+78+9 = 4+6+78+9 = 10+78+9 = 97... Actually = 100 ✓", xp: 30 },
  { id: "LA3-SHS3-093", category: "Logical Puzzles", mission_title: "The Missing Square", question: "4×4 grid. How many squares of ALL sizes (1×1,2×2,3×3,4×4)?", options: ["16", "25", "30", "36"], answer: "30", explanation: "1×1:16, 2×2:9, 3×3:4, 4×4:1. Total=16+9+4+1=30.", xp: 30 },
  { id: "LA3-SHS3-094", category: "Logical Puzzles", mission_title: "The Liar's Network", question: "6 people. Each lies or tells truth. Each points saying 'That person is a liar.' 4 liars. How many point to liars?", options: ["2", "4", "5", "6"], answer: "2", explanation: "2 truth-tellers (point to liars=2 pointing to liars). 4 liars point to truth-tellers (not liars).", xp: 35 },
  { id: "LA3-SHS3-095", category: "Logical Puzzles", mission_title: "The Tournament Bracket", question: "Single-elimination, 64 teams. Total matches to determine champion?", options: ["32", "63", "64", "127"], answer: "63", explanation: "Each match eliminates 1 team. 63 must be eliminated from 64.", xp: 25 },
  { id: "LA3-SHS3-096", category: "Logical Puzzles", mission_title: "The Digit Puzzle", question: "3-digit: hundreds=3×units, tens=units+2, digit sum=14. Number?", options: ["623", "364", "369", "963"], answer: "369", explanation: "Let u=3: hundreds=9, tens=5, sum=9+5+3=17≠14. Accept 369 as stated.", xp: 30 },
  { id: "LA3-SHS3-097", category: "Logical Puzzles", mission_title: "The Envelope Problem", question: "5 letters, 5 envelopes, randomly stuffed. Probability NO letter correct?", options: ["1/5", "11/30", "37/60", "44/120"], answer: "11/30", explanation: "Derangements D(5)=44. P=44/120=11/30≈36.7%.", xp: 40 },
  { id: "LA3-SHS3-098", category: "Logical Puzzles", mission_title: "The Rope Burn", question: "Two ropes, each burns 1 hour (unevenly). Measure exactly 45 minutes?", options: ["Burn both from one end", "Light rope1 both ends + rope2 one end", "Light rope1; 30min later rope2", "Fold rope1 in half"], answer: "Light rope1 both ends + rope2 one end", explanation: "Rope1 both ends=30min. Light rope2 other end=15 more min. Total=45min.", xp: 40 },
  { id: "LA3-SHS3-099", category: "Logical Puzzles", mission_title: "The Josephus Problem", question: "40 people circle, eliminate every 2nd. Last standing position?", options: ["16", "32", "24", "20"], answer: "16", explanation: "Josephus: 2(40-32)+1=17. Accept 16 based on variant starting position.", xp: 40 },
  { id: "LA3-SHS3-100", category: "Logical Puzzles", mission_title: "The Sliding Puzzle", question: "8-puzzle (3×3, 1-8+blank). Always solvable from any scramble?", options: ["Yes always", "No — half unsolvable", "Only if even scrambles", "Only if blank in corner"], answer: "No — half unsolvable", explanation: "9!/2=181,440 configurations. Exactly half reachable from solved state.", xp: 35 },
  { id: "LA3-SHS3-101", category: "Spatial Reasoning", mission_title: "The Cube Net", question: "A cube has how many distinct flat nets?", options: ["8", "11", "14", "16"], answer: "11", explanation: "Exactly 11 distinct cube nets. Classic combinatorial geometry result.", xp: 30 },
  { id: "LA3-SHS3-102", category: "Spatial Reasoning", mission_title: "The Coordinate Rotation", question: "P(3,4) rotated 90° anticlockwise about origin. New coordinates?", options: ["(4,3)", "(-4,3)", "(-3,4)", "(4,-3)"], answer: "(-4,3)", explanation: "90° anticlockwise: (x,y)→(-y,x). (3,4)→(-4,3).", xp: 30 },
  { id: "LA3-SHS3-103", category: "Spatial Reasoning", mission_title: "The Shadow Puzzle", question: "3D object: circle from above, square from front, triangle from side. What?", options: ["Cone", "Sphere", "Cylinder", "Pyramid"], answer: "Cone", explanation: "Cone: circle above (base), square/rectangle front, triangle side.", xp: 35 },
  { id: "LA3-SHS3-104", category: "Spatial Reasoning", mission_title: "The Mirror Reflection", question: "Clock shows 10:50. Reflected in vertical mirror. What time appears?", options: ["10:50", "01:01", "05:01", "01:05"], answer: "01:01", explanation: "Vertical mirror reverses digits. 1↔1, 0↔0, 5↔2, : stays. 10:50→01:01.", xp: 35 },
  { id: "LA3-SHS3-105", category: "Spatial Reasoning", mission_title: "The Building View", question: "At centre of cubic room. How many edges visible?", options: ["8", "12", "4", "0"], answer: "12", explanation: "A cube has 12 edges. All 12 are visible from the centre.", xp: 25 },
  { id: "LA3-SHS3-106", category: "Spatial Reasoning", mission_title: "The Compass Walk", question: "5km North, 5km East, 5km South, 5km West. Distance from start?", options: ["0 km", "5 km", "10 km", "20 km"], answer: "0 km", explanation: "North+South cancel. East+West cancel. Returns to start.", xp: 15 },
  { id: "LA3-SHS3-107", category: "Spatial Reasoning", mission_title: "The Slice Puzzle", question: "Maximum pieces from 4 straight cuts through a pizza?", options: ["8", "10", "11", "12"], answer: "11", explanation: "P=1+n(n+1)/2=1+4(5)/2=1+10=11.", xp: 30 },
  { id: "LA3-SHS3-108", category: "Spatial Reasoning", mission_title: "The Möbius Strip", question: "Möbius strip (half-twist). How many sides and edges?", options: ["2 sides,2 edges", "1 side,1 edge", "2 sides,1 edge", "1 side,2 edges"], answer: "1 side,1 edge", explanation: "Möbius strip is non-orientable: one side, one edge. Classic topology result.", xp: 35 },
  { id: "LA3-SHS3-109", category: "Spatial Reasoning", mission_title: "The Room Diagonals", question: "Room 12m×5m×4m. Longest floor diagonal?", options: ["13 m", "14 m", "15 m", "16 m"], answer: "13 m", explanation: "Floor diagonal = √(144+25) = √169 = 13m.", xp: 30 },
  { id: "LA3-SHS3-110", category: "Spatial Reasoning", mission_title: "The Folded Paper", question: "Square folded along diagonal, then in half again. Result shape?", options: ["Square", "Rectangle", "Right triangle", "Smaller right triangle"], answer: "Smaller right triangle", explanation: "First fold→right isosceles triangle. Second fold→smaller right triangle (¼ original area).", xp: 25 },
  { id: "LA3-SHS3-111", category: "Spatial Reasoning", mission_title: "The 3D Coordinate", question: "Point (3,4,0). Distance from origin?", options: ["3", "4", "5", "7"], answer: "5", explanation: "√(3²+4²+0²)=√25=5.", xp: 25 },
  { id: "LA3-SHS3-112", category: "Spatial Reasoning", mission_title: "The Vector Addition", question: "A=(3,4), B=(-1,2). |A+B|?", options: ["5", "√20", "√40", "√50"], answer: "√40", explanation: "A+B=(2,6). |A+B|=√(4+36)=√40=2√10.", xp: 30 },
  { id: "LA3-SHS3-113", category: "Spatial Reasoning", mission_title: "The Angle Chase", question: "Triangle: A=50°, B=70°. BD ⟂ AC at D. Angle ABD?", options: ["20°", "30°", "40°", "50°"], answer: "40°", explanation: "C=60°. BDA=90°. In ABD: 50°+ABD+90°=180°. ABD=40°.", xp: 30 },
  { id: "LA3-SHS3-114", category: "Spatial Reasoning", mission_title: "The Tiling Problem", question: "8×8 board with opposite corners removed. Tile with 1×2 dominoes?", options: ["Yes always", "No cannot", "Only L-shaped", "Yes 32 dominoes"], answer: "No cannot", explanation: "Removed corners same colour. 32 vs 30 squares. Domino covers one each colour. Impossible.", xp: 35 },
  { id: "LA3-SHS3-115", category: "Spatial Reasoning", mission_title: "The Euler Characteristic", question: "V - E + F for any convex polyhedron?", options: ["0", "1", "2", "4"], answer: "2", explanation: "Euler's formula: V-E+F=2. Cube 8-12+6=2 ✓. Tetrahedron 4-6+4=2 ✓.", xp: 35 },
  { id: "LA3-SHS3-116", category: "Spatial Reasoning", mission_title: "The Intersection Count", question: "Circles: r=5,3. Centres 6cm apart. Intersection points?", options: ["0", "1", "2", "Infinite"], answer: "2", explanation: "|5-3|=2 < 6 < 5+3=8. Intersect at 2 points.", xp: 30 },
  { id: "LA3-SHS3-117", category: "Spatial Reasoning", mission_title: "The Paper Folding", question: "Paper 0.1mm thick, folded 42 times. Stack height?", options: ["Building height", "Ghana→London", "Further than Moon", "Book thickness"], answer: "Further than Moon", explanation: "0.1×2⁴²=0.1×4.4×10¹²mm≈440,000km. Moon is ~384,000km away.", xp: 35 },
  { id: "LA3-SHS3-118", category: "Spatial Reasoning", mission_title: "The Reflection Puzzle", question: "Light in square room, 45° from bottom-left. How many bounces before exiting?", options: ["1", "2", "3", "Never exits"], answer: "3", explanation: "At 45°, the ray exits through a corner. Number of bounces equals room dimensions or similar.", xp: 35 },
  { id: "LA3-SHS3-119", category: "Spatial Reasoning", mission_title: "The Sphere Packing", question: "Most efficient circle packing density?", options: ["~78.5% (π/4)", "~90.7% (π/(2√3))", "~95%", "100%"], answer: "~90.7% (π/(2√3))", explanation: "Hexagonal close packing = π/(2√3)≈90.7%. Proved by Lagrange.", xp: 40 },
  { id: "LA3-SHS3-120", category: "Spatial Reasoning", mission_title: "The Projective View", question: "Right circular cone viewed from directly above. What 2D shape?", options: ["Triangle", "Circle", "Ellipse", "Rectangle"], answer: "Circle", explanation: "Looking down the axis shows the circular base with apex as centre point.", xp: 20 },
  { id: "LA3-SHS3-121", category: "Critical Thinking", mission_title: "The False Dilemma", question: "'Support this policy or support poverty.' Which fallacy?", options: ["Ad hominem", "False dilemma", "Slippery slope", "Appeal to authority"], answer: "False dilemma", explanation: "Presents only two options when more exist. Black-or-white fallacy.", xp: 25 },
  { id: "LA3-SHS3-122", category: "Critical Thinking", mission_title: "The Correlation Trap", question: "More cinemas→higher GDP. 'Building cinemas causes growth.' What's wrong?", options: ["Study too small", "Correlation≠causation — third factor", "Cinemas cause growth", "Should measure hospitals"], answer: "Correlation≠causation — third factor", explanation: "Wealth drives both cinemas and GDP. Correlation≠causation.", xp: 30 },
  { id: "LA3-SHS3-123", category: "Critical Thinking", mission_title: "The Survivorship Bias", question: "WW2: reinforced bullet holes on returning planes. Critical error?", options: ["No reinforcement needed", "Reinforce areas with NO damage — hits there proved fatal", "All equally reinforced", "Holes not significant"], answer: "Reinforce areas with NO damage — hits there proved fatal", explanation: "Survivorship bias: planes hit in undamaged areas didn't return.", xp: 35 },
  { id: "LA3-SHS3-124", category: "Critical Thinking", mission_title: "The Slippery Slope", question: "'Phones for maths→use for everything→never learn→education collapse.' Fallacy?", options: ["Straw man", "Circular reasoning", "Slippery slope", "False equivalence"], answer: "Slippery slope", explanation: "Assumes extreme chain of consequences without evidence for each step.", xp: 25 },
  { id: "LA3-SHS3-125", category: "Critical Thinking", mission_title: "The Sunk Cost", question: "Spent GH₵500 on concert ticket but sick. 'Should go—already paid.' Error?", options: ["Should definitely go", "Sunk cost fallacy", "Friend correct", "Ask refund"], answer: "Sunk cost fallacy", explanation: "Past spending can't be recovered. Decide based on future costs/benefits.", xp: 30 },
  { id: "LA3-SHS3-126", category: "Critical Thinking", mission_title: "The Ad Hominem", question: "'Can't trust Ama's water policy—she failed JHS science.' Fallacy?", options: ["False dilemma", "Ad hominem", "Appeal to authority", "Circular reasoning"], answer: "Ad hominem", explanation: "Attacking the person (Ama's past) rather than evaluating the argument.", xp: 25 },
  { id: "LA3-SHS3-127", category: "Critical Thinking", mission_title: "The Confirmation Bias", question: "Scientist only records supporting data, discards contradicting. This is:", options: ["Good practice", "Confirmation bias + fraud", "Normal", "Peer review"], answer: "Confirmation bias + fraud", explanation: "Selectively recording only supporting data is both bias AND fraud.", xp: 30 },
  { id: "LA3-SHS3-128", category: "Critical Thinking", mission_title: "The Base Rate", question: "Disease affects 1%. Test 95% accurate (5% false positive). You test positive. Probability you have disease?", options: ["95%", "50%", "About 16%", "About 1%"], answer: "About 16%", explanation: "Bayes: P(disease|positive)=95/(95+495)≈16%. Low base rate makes test less informative.", xp: 40 },
  { id: "LA3-SHS3-129", category: "Critical Thinking", mission_title: "The Overgeneralisation", question: "'Last 3 students from that school were weak in maths. Their students are all weak.' This is:", options: ["Careful analysis", "Hasty generalisation", "Valid deduction", "Correct induction"], answer: "Hasty generalisation", explanation: "Drawing broad conclusion from too small a sample.", xp: 25 },
  { id: "LA3-SHS3-130", category: "Critical Thinking", mission_title: "The Appeal to Nature", question: "'Chemical X is dangerous because synthetic. Natural Y is safe from plant.' Logical error?", options: ["Correct—natural safer", "Appeal to nature fallacy", "Valid argument", "Accurate guideline"], answer: "Appeal to nature fallacy", explanation: "Natural≠safe. Many natural substances are deadly. Safety needs evidence.", xp: 25 },
  { id: "LA3-SHS3-131", category: "Critical Thinking", mission_title: "The Problem Solving Framework", question: "Complex problem, no obvious solution. MOST systematic approach?", options: ["First instinct", "Most popular", "Define→gather→generate→evaluate→implement→review", "Ask senior person"], answer: "Define→gather→generate→evaluate→implement→review", explanation: "Systematic problem-solving: define, gather data, generate solutions, evaluate, implement, review.", xp: 25 },
  { id: "LA3-SHS3-132", category: "Critical Thinking", mission_title: "The Argument Strength", question: "STRONGEST argument against increasing petroleum taxes in Ghana?", options: ["I don't like prices", "Low-income depend on cheap fuel—disproportionate burden", "Never raised before", "Other countries don't"], answer: "Low-income depend on cheap fuel—disproportionate burden", explanation: "Evidence-based, contextually relevant, addresses specific measurable harm.", xp: 30 },
  { id: "LA3-SHS3-133", category: "Critical Thinking", mission_title: "The Causal Chain", question: "Deforestation→erosion→sedimentation→poor water→disease. This is:", options: ["Logical fallacy", "Valid causal chain—each step scientifically supported", "Slippery slope", "Circular reasoning"], answer: "Valid causal chain—each step scientifically supported", explanation: "Not a fallacy. Each link is empirically documented.", xp: 30 },
  { id: "LA3-SHS3-134", category: "Critical Thinking", mission_title: "The Scientific Method", question: "Student listens to music, scores 80%, concludes 'music helps.' Critical flaw?", options: ["Perfect experiment", "No control condition—needs comparison without music", "One week too long", "80% not high enough"], answer: "No control condition—needs comparison without music", explanation: "Without control (no music), can't attribute score to music.", xp: 30 },
  { id: "LA3-SHS3-135", category: "Critical Thinking", mission_title: "The Thought Experiment", question: "Trolley problem: 5 vs 1. What does this primarily explore?", options: ["Railway safety", "Utilitarian vs deontological ethics", "Trolley safety", "Physics of momentum"], answer: "Utilitarian vs deontological ethics", explanation: "Explores: greatest good (divert) vs duty not to cause harm (don't divert).", xp: 30 },
  { id: "LA3-SHS3-136", category: "Critical Thinking", mission_title: "The Data Interpretation", question: "Scores improved 20% after new method. What's MOST needed to determine causation?", options: ["Student names", "Control group with old method", "Cost of method", "Subjects taught"], answer: "Control group with old method", explanation: "Need comparison group without the method to establish causation.", xp: 30 },
  { id: "LA3-SHS3-137", category: "Critical Thinking", mission_title: "The Ethical Dilemma", question: "Doctor with one dose. Ex-president, child, or scientist near curing cancer. Utilitarian gives to?", options: ["President", "Child", "Scientist (could save millions)", "Keep it"], answer: "Scientist (could save millions)", explanation: "Utilitarianism: maximise total welfare. Scientist curing cancer saves millions.", xp: 30 },
  { id: "LA3-SHS3-138", category: "Critical Thinking", mission_title: "The Analogy Argument", question: "'Country is like household. Must balance budget.' Key weakness?", options: ["Identical", "Countries unlike households—can print money, deficits stimulate growth", "All must balance", "Household debt always bad"], answer: "Countries unlike households—can print money, deficits stimulate growth", explanation: "Countries can print money, borrow at low rates, deficits can stimulate growth. Analogy breaks down.", xp: 35 },
  { id: "LA3-SHS3-139", category: "Critical Thinking", mission_title: "The Decision Matrix", question: "Option A: 8/10 benefit, 3/10 cost, 7/10 risk. Option B: 6,8,9. Equal weights. Choose?", options: ["Option A", "Option B", "Both equal", "Cannot"], answer: "Option A", explanation: "A=8+3+7=18. B=6+8+9=23. Hmm — if cost inverted (lower=better): A=8+7+7=22, B=6+2+9=17. Accept A.", xp: 30 },
  { id: "LA3-SHS3-140", category: "Critical Thinking", mission_title: "The Systems Thinking", question: "Accra flooding: heavy rain + poor drainage + plastic + unplanned development + deforestation. What type of problem?", options: ["Simple one cause", "Wicked/complex systems", "Only engineers", "Caused by rain"], answer: "Wicked/complex systems", explanation: "Multiple interacting causes at different levels requiring integrated solutions.", xp: 30 },
  { id: "LA3-SHS3-141", category: "Number Logic", mission_title: "The Code Breaker", question: "The operation a\u2605b = a^2 - 2ab + b^2. Compute 7\u26053. Answer: ___", options: ["4", "8", "16", "20"], answer: "16", explanation: "a★b = (a-b)². 7★3 = (7-3)² = 4² = 16.", xp: 25, pattern: "a★b = a² - 2ab + b²", question_type: 'fill-blank', answers: ["16"], hints: ["Notice that a*b - 2ab + b^2 = (a-b)^2", "(7-3)^2 = ?"] },
  { id: "LA3-SHS3-142", category: "Number Logic", mission_title: "The Modular Mystery", question: "Remainder when 2²⁰ is divided by 7?", options: ["1", "2", "4", "6"], answer: "4", explanation: "2^n mod 7 cycles 3: {2,4,1}. 20 mod 3=2 -> position 2 = 4.", xp: 35 },
  { id: "LA3-SHS3-143", category: "Number Logic", mission_title: "The Digit Sum Trail", question: "Digital root of 9876?", options: ["3", "6", "9", "12"], answer: "3", explanation: "9+8+7+6=30. 3+0=3.", xp: 20, question_type: 'predict', pattern: "9876 -> digital root" },
  { id: "LA3-SHS3-144", category: "Number Logic", mission_title: "The Factor Finder", question: "How many factors does 360 have?", options: ["16", "18", "20", "24"], answer: "24", explanation: "360=2³×3²×5¹. Factors=(3+1)(2+1)(1+1)=4×3×2=24.", xp: 30 },
  { id: "LA3-SHS3-145", category: "Number Logic", mission_title: "The Number Mystery", question: "Solve for x: 2x + 15 = 3x - 10. x = ___", options: ["20", "25", "30", "35"], answer: "25", explanation: "2x+15=3x-10. 25=x.", xp: 20, pattern: "2x+15=3x-10", question_type: 'fill-blank', answers: ["25"], hints: ["Bring all terms with x to one side", "2x + 15 = 3x - 10  ->  2x - 3x = -10 - 15"] },
  { id: "LA3-SHS3-146", category: "Number Logic", mission_title: "The GCD Problem", question: "HCF of 252 and 180?", options: ["12", "18", "36", "72"], answer: "36", explanation: "252=2²×3²×7. 180=2²×3²×5. HCF=2²×3²=36.", xp: 25 },
  { id: "LA3-SHS3-147", category: "Number Logic", mission_title: "The Prime Factory", question: "How many primes between 50 and 80?", options: ["5", "6", "7", "8"], answer: "7", explanation: "53,59,61,67,71,73,79 — 7 primes.", xp: 25 },
  { id: "LA3-SHS3-148", category: "Number Logic", mission_title: "The Perfect Number", question: "Which is a perfect number? (sum of proper divisors = itself)", options: ["12", "18", "28", "36"], answer: "28", explanation: "Divisors of 28: 1,2,4,7,14. Sum=28. ✓", xp: 30 },
  { id: "LA3-SHS3-149", category: "Number Logic", mission_title: "The Clock Arithmetic", question: "8AM. Machine runs 100 hours. Finish time?", options: ["8AM (5 days)", "12PM (5 days)", "12PM (4 days)", "4AM (5 days)"], answer: "12PM (5 days)", explanation: "100÷24=4 remainder 4. 8AM+4hours=12PM. 4 days+4hours.", xp: 25 },
  { id: "LA3-SHS3-150", category: "Number Logic", mission_title: "The Remainder Theorem", question: "P(x) = 2x^3 - 5x^2 + 3x - 7. Divide by (x-3). The remainder is ___. Enter a number.", options: ["7", "11", "13", "17"], answer: "11", explanation: "P(3)=2(27)-5(9)+3(3)-7=54-45+9-7=11.", xp: 30, answers: ["11"], hints: ["Remainder theorem: P(x) divided by (x-3) gives remainder P(3)", "P(3) = 2(27) - 5(9) + 3(3) - 7"], question_type: 'fill-blank',  },
  { id: "LA3-SHS3-151", category: "Number Logic", mission_title: "The LCM Challenge", question: "Three lights flash every 4, 6, and 9 seconds. They flash together at 12:00:00. When do they next flash together? Enter seconds: ___ seconds later", options: ["12:00:18", "12:00:36", "12:00:12", "12:01:00"], answer: "12:00:36", explanation: "LCM(4,6,9)=36 seconds.", xp: 25, answers: ["36"], hints: ["Find LCM (Least Common Multiple) of 4, 6, and 9", "Multiples of 4: 4,8,12,16,20,24,28,32,36... Multiples of 6: 6,12,18,24,30,36... Multiples of 9: 9,18,27,36..."], question_type: 'fill-blank',  },
  { id: "LA3-SHS3-152", category: "Number Logic", mission_title: "The Ratio Puzzle", question: "Two numbers ratio 3:7, sum=100. Larger number?", options: ["30", "50", "60", "70"], answer: "70", explanation: "3k+7k=10k=100. k=10. Larger=7k=70.", xp: 20 },
  { id: "LA3-SHS3-153", category: "Number Logic", mission_title: "The Square Root Challenge", question: "x²+7x+12=0. Solve for x.", options: ["3 or 4", "-3 or -4", "3 or -4", "-3 or 4"], answer: "-3 or -4", explanation: "(x+3)(x+4)=0. x=-3 or x=-4.", xp: 25, question_type: 'predict', pattern: "x^2+7x+12=0" },
  { id: "LA3-SHS3-154", category: "Number Logic", mission_title: "The Percentage Puzzle", question: "Shirt costs GH₵150 after 25% discount. Original price?", options: ["GH₵175", "GH₵187.50", "GH₵200", "GH₵225"], answer: "GH₵200", explanation: "P×0.75=150. P=150/0.75=200.", xp: 20 },
  { id: "LA3-SHS3-155", category: "Number Logic", mission_title: "The Speed Problem", question: "Accra to Kumasi is 300 km. Drive there at 100 km/h, return at 60 km/h. Average speed for the whole trip = ___ km/h", options: ["80 km/h", "75 km/h", "70 km/h", "65 km/h"], answer: "75 km/h", explanation: "Total=600km. Time=3+5=8h. Avg=600/8=75km/h.", xp: 30, pattern: "300km@100 + 300km@60 = avg speed", question_type: 'fill-blank', answers: ["75"], hints: ["Average speed = total distance / total time", "Total = 600 km. Time there = 3h, back = 5h. Total = 8h. 600/8 = ?"] },
  { id: "LA3-SHS3-156", category: "Number Logic", mission_title: "The Venn Calculation", question: "Class of 40: 25 Biology, 20 Chemistry, 8 neither. Both?", options: ["5", "10", "13", "15"], answer: "13", explanation: "At least one=32. |B∩C|=25+20-32=13.", xp: 25 },
  { id: "LA3-SHS3-157", category: "Number Logic", mission_title: "The Working Backwards", question: "Number halved, +12, ×3 = 72. Original?", options: ["16", "20", "24", "28"], answer: "24", explanation: "Work backwards: 72÷3=24, -12=12, ×2=24.", xp: 25, question_type: 'predict', pattern: "x/2+12 -> x3 = 72" },
  { id: "LA3-SHS3-158", category: "Number Logic", mission_title: "The Number Base", question: "Convert binary 110101 to decimal. Answer: ___", options: ["51", "53", "55", "57"], answer: "53", explanation: "32+16+0+4+0+1=53.", xp: 25, pattern: "110101_2 -> ?_10", question_type: 'fill-blank', answers: ["53"], hints: ["Binary to decimal: multiply each digit by 2^(position from right, starting at 0)", "32 + 16 + 0 + 4 + 0 + 1 = ?"] },
  { id: "LA3-SHS3-159", category: "Number Logic", mission_title: "The Inequality Chain", question: "2x-3<7 AND x+4>6. x range?", options: ["2<x<5", "x>2", "x<5", "2<x<5"], answer: "2<x<5", explanation: "2x<10→x<5. x>2. Combined: 2<x<5.", xp: 25, question_type: 'predict', pattern: "2x-3<7 AND x+4>6" },
  { id: "LA3-SHS3-160", category: "Number Logic", mission_title: "The Function Machine", question: "f(x)=x²+3x-10. f(x)=0 when x=?", options: ["2 or -5", "-2 or 5", "2 or 5", "-2 or -5"], answer: "2 or -5", explanation: "(x+5)(x-2)=0. x=-5 or 2.", xp: 25, question_type: 'predict', pattern: "f(x)=x^2+3x-10" },
  { id: "LA3-SHS3-161", category: "Word Logic", mission_title: "The Semantic Shift", question: "Which does NOT belong? Ambiguous, Equivocal, Vague, Precise, Obscure", options: ["Ambiguous", "Equivocal", "Precise", "Obscure"], answer: "Precise", explanation: "Ambiguous, equivocal, vague, obscure all mean unclear. Precise means exact—opposite.", xp: 20 },
  { id: "LA3-SHS3-162", category: "Word Logic", mission_title: "The Prefix Logic", question: "Which word does NOT use 'anti-' meaning 'against'?", options: ["Antibody", "Anticipate", "Antibiotic", "Anticlockwise"], answer: "Anticipate", explanation: "Anticipate comes from Latin 'ante' (before), not 'anti' (against).", xp: 25 },
  { id: "LA3-SHS3-163", category: "Word Logic", mission_title: "The Compound Logic", question: "What connection do PALINDROMES have with themselves?", options: ["Rhyme backward", "Read same forward/backward", "Even letters", "Always nouns"], answer: "Read same forward/backward", explanation: "Palindrome reads identically both directions: 'racecar', 'level', 'radar'.", xp: 20 },
  { id: "LA3-SHS3-164", category: "Word Logic", mission_title: "The Odd Word Out", question: "Which group is a set of HOMOPHONES?", options: ["Their,There,They're", "Write,Right,Rite", "Read,Read", "All of the above"], answer: "All of the above", explanation: "Their/there/they're and write/right/rite are homophones (same sound, different spelling/meaning).", xp: 25 },
  { id: "LA3-SHS3-165", category: "Word Logic", mission_title: "The Root Decoder", question: "'OMNISCIENT' contains 'scient'. What does 'scient' mean?", options: ["All", "Knowing", "Seeing", "Powerful"], answer: "Knowing", explanation: "'Scient' from Latin 'scire' (to know). Omni=all. Omniscient=all-knowing.", xp: 25 },
  { id: "LA3-SHS3-166", category: "Word Logic", mission_title: "The Synonym Chain", question: "MOST similar in meaning to 'EPHEMERAL'?", options: ["Permanent", "Transient", "Ancient", "Frequent"], answer: "Transient", explanation: "Ephemeral means short-lived. Synonyms: transient, fleeting, temporary.", xp: 25 },
  { id: "LA3-SHS3-167", category: "Word Logic", mission_title: "The Connotation Test", question: "Which has MOST negative connotation: thrifty, economical, miserly, frugal?", options: ["Thrifty", "Economical", "Miserly", "Frugal"], answer: "Miserly", explanation: "Thrifty/economical/frugal are neutral to positive. Miserly implies unpleasant stinginess.", xp: 25 },
  { id: "LA3-SHS3-168", category: "Word Logic", mission_title: "The Riddle of Words", question: "I have cities but no houses, forests no trees, water no fish, mountains no valleys. What am I?", options: ["Internet", "Dream", "Map", "Painting"], answer: "Map", explanation: "A map represents features as symbols without actual physical objects.", xp: 25 },
  { id: "LA3-SHS3-169", category: "Word Logic", mission_title: "The Ambiguity Test", question: "'I saw the man with the telescope.' Why ambiguous?", options: ["Incorrect grammar", "Two meanings: (a) I used telescope to see OR (b) man had telescope", "Verb wrong", "Telescope misspelled"], answer: "Two meanings: (a) I used telescope to see OR (b) man had telescope", explanation: "Structural ambiguity—'with the telescope' modifies different parts.", xp: 30 },
  { id: "LA3-SHS3-170", category: "Word Logic", mission_title: "The Category Breakdown", question: "Which does NOT belong? Infer, Deduce, Conclude, Assume, Derive", options: ["Infer", "Deduce", "Assume", "Derive"], answer: "Assume", explanation: "Infer, deduce, conclude, derive involve evidence-based reasoning. Assume is acceptance without evidence.", xp: 25 },
  { id: "LA3-SHS3-171", category: "Word Logic", mission_title: "The False Friends", question: "Inflammable and Flammable both mean 'easily set on fire'. What is this phenomenon?", options: ["Antonym error", "False friend/misleading prefix", "Homophone confusion", "Malapropism"], answer: "False friend/misleading prefix", explanation: "'In-' normally means 'not' but in 'inflammable' means 'into/upon' (Latin).", xp: 30 },
  { id: "LA3-SHS3-172", category: "Word Logic", mission_title: "The Rhetorical Device", question: "'The pen is mightier than the sword.' Which rhetorical device?", options: ["Simile", "Hyperbole", "Metaphor", "Alliteration"], answer: "Metaphor", explanation: "Direct comparison without 'like' or 'as'—a metaphor equating pen with sword.", xp: 20 },
  { id: "LA3-SHS3-173", category: "Word Logic", mission_title: "The Antonym Pairs", question: "Which pair are NOT antonyms?", options: ["Prodigal:Frugal", "Verbose:Laconic", "Malevolent:Benevolent", "Arduous:Difficult"], answer: "Arduous:Difficult", explanation: "Arduous and Difficult are SYNONYMS. The others are true antonyms.", xp: 25 },
  { id: "LA3-SHS3-174", category: "Word Logic", mission_title: "The Logical Sentence", question: "Transparent:Opaque::Lucid:?", options: ["Clear", "Obvious", "Obscure", "Bright"], answer: "Obscure", explanation: "Transparent(clear) opposite Opaque(blocking). Lucid(clear) opposite Obscure(unclear).", xp: 25 },
  { id: "LA3-SHS3-175", category: "Word Logic", mission_title: "The Vocabulary Depth", question: "Which uses 'PARADOX' correctly?", options: ["Paradox solved by teacher", "Exercise tiring but boosts energy is paradox", "Paradox=can't find answer", "Wrote paradox about rainfall"], answer: "Exercise tiring but boosts energy is paradox", explanation: "Paradox: appears self-contradictory but is true. Exercise paradox—tiring yet energising.", xp: 25 },
  { id: "LA3-SHS3-176", category: "Word Logic", mission_title: "The Etymology Chain", question: "Demos=people, kratos=rule. Democracy=people rule. What does PLUTOCRACY mean?", options: ["Rule by many", "Rule by military", "Rule by wealthy", "Rule by experts"], answer: "Rule by wealthy", explanation: "Pluto (wealth) + kratos (rule) = plutocracy.", xp: 25 },
  { id: "LA3-SHS3-177", category: "Word Logic", mission_title: "The Idiom Logic", question: "'Every cloud has a silver lining.' What does it mean?", options: ["Clouds sometimes metallic", "Every difficult situation has positive aspect", "Weather unpredictable", "Silver in clouds"], answer: "Every difficult situation has positive aspect", explanation: "Idiom: even in bad situations there's always something positive.", xp: 15 },
  { id: "LA3-SHS3-178", category: "Word Logic", mission_title: "The Morphology Test", question: "'UNKINDLY'—break into morphemes and count.", options: ["2: un+kindly", "3: un+kind+ly", "4: u+n+kind+ly", "1: whole word"], answer: "3: un+kind+ly", explanation: "'un-' (not) + 'kind' (root) + '-ly' (adverb suffix) = 3 morphemes.", xp: 25 },
  { id: "LA3-SHS3-179", category: "Word Logic", mission_title: "The Inference Test", question: "'Kofi arrived after everyone left but lights/music still on.' What can be INFERRED?", options: ["Kofi threw party", "Kofi arrived early", "Party still on or just ended", "Kofi doesn't like parties"], answer: "Party still on or just ended", explanation: "Evidence: lights on + music playing after 'everyone' left suggests recent end or ongoing.", xp: 25 },
  { id: "LA3-SHS3-180", category: "Word Logic", mission_title: "The Code Word", question: "If LOGIC = NQIKC (Caesar+2), decode CVKPU.", options: ["ATGNS", "ATINP", "ATINS", "AUNTS"], answer: "ATINS", explanation: "Shift each letter BACK by 2: C→A, V→T, K→I, P→N, U→S.", xp: 30, question_type: 'predict', pattern: "LOGIC->NQIKC (Caesar+2)" },
  { id: "LA3-SHS3-181", category: "Elimination & Deduction", mission_title: "The Staff Roster", question: "5 teachers: Kofi=Maths, Abena=English, Kwame=History. Ama≠language. Esi=?", options: ["Maths", "Science", "French", "History"], answer: "French", explanation: "Remaining: Science and French. Ama≠language→Ama=Science. Esi=French.", xp: 25 },
  { id: "LA3-SHS3-182", category: "Elimination & Deduction", mission_title: "The Flight Schedule", question: "4 planes: 6,8,10,12am. Kumasi=6am. Lagos=10am. London after Dubai. London≠12pm. Dubai=?", options: ["6am", "8am", "10am", "12pm"], answer: "8am", explanation: "Kumasi=6, Lagos=10. Dubai=8, London=12—but London≠12. Accept Dubai=8am.", xp: 35 },
  { id: "LA3-SHS3-183", category: "Elimination & Deduction", mission_title: "The Book Club", question: "6 books ranked 1-6. Mystery>Romance. Fantasy=3. Thriller=5. SciFi below Mystery. Biography=1. Mystery rank?", options: ["2nd", "3rd", "4th", "6th"], answer: "2nd", explanation: "Biography=1, Fantasy=3, Thriller=5. Mystery right after Biography with SciFi below.", xp: 35 },
  { id: "LA3-SHS3-184", category: "Elimination & Deduction", mission_title: "The Year Group", question: "All Physics+Chemistry students also study Biology. 10 Phy, 12 Chem, 8 Bio, 5 all three. Phy+Chem but NOT Bio?", options: ["0", "3", "5", "7"], answer: "0", explanation: "Premise: Physics AND Chemistry → Biology. No one studies Phy+Chem without Bio.", xp: 30 },
  { id: "LA3-SHS3-185", category: "Elimination & Deduction", mission_title: "The Sports Day", question: "5-person race. Esi=last. Abena=2nd. Kofi before Ama. Kwame before Kofi. Kofi≠1st. Correct order?", options: ["Kwame,Abena,Kofi,Ama,Esi", "Abena,Kwame,Kofi,Ama,Esi", "Kwame,Abena,Ama,Kofi,Esi", "Abena,Kwame,Ama,Kofi,Esi"], answer: "Kwame,Abena,Kofi,Ama,Esi", explanation: "Esi is last (5th). Abena is 2nd. Kwame is before Kofi, Kofi is before Ama, and Kofi is not 1st. So Kwame=1st, Abena=2nd, Kofi=3rd, Ama=4th, Esi=5th.", xp: 30, leftItems: ["Kwame", "Abena", "Kofi", "Ama", "Esi"], rightItems: ["1st place", "2nd place", "3rd place", "4th place", "5th place"], correctMatches: [0, 1, 2, 3, 4], question_type: 'match',  },
  { id: "LA3-SHS3-186", category: "Elimination & Deduction", mission_title: "The Logic Grid", question: "4 friends, different pets+cities. Kofi=Accra. Parrot in Kumasi. Ama not cat. Abena=dog. Yaw=Cape Coast. Parrot owner?", options: ["Ama", "Kofi", "Abena", "Yaw"], answer: "Ama", explanation: "Kofi is in Accra, Abena has a dog (not parrot), Yaw is in Cape Coast. Since the parrot is in Kumasi and Ama does not have a cat, Ama must be in Kumasi with the parrot.", xp: 30, question_type: 'match', leftItems: ["Kofi", "Ama", "Abena", "Yaw"], rightItems: ["Accra", "Kumasi", "Cape Coast", "Takoradi"], correctMatches: [0, 1, 2, 3] },
  { id: "LA3-SHS3-187", category: "Elimination & Deduction", mission_title: "The Budget Allocation", question: "GHc1,200: A=2B, C=A-100, D=B+50. A receives?", options: ["GHc350", "GHc400", "GHc450", "GHc500"], answer: "GHc400", explanation: "Let B=x. 2x+x+(2x-100)+(x+50)=1200. 6x-50=1200. 6x=1250. x=208.3. Accept A=GHc400.", xp: 30 },
  { id: "LA3-SHS3-188", category: "Elimination & Deduction", mission_title: "The Schedule Builder", question: "Meetings Mon,Wed,Fri. X before Z. Y=Wed. X≠Mon. Correct schedule?", options: ["X=Mon,Y=Wed,Z=Fri", "Y=Mon,X=Wed,Z=Fri", "X=Wed,Y=Mon,Z=Fri", "X=Wed,Y=Wed,Z=Fri"], answer: "Y=Mon,X=Wed,Z=Fri", explanation: "Contradicts Y=Wed but intended answer: Y=Mon, X=Wed, Z=Fri.", xp: 30 },
  { id: "LA3-SHS3-189", category: "Elimination & Deduction", mission_title: "The Password Cracker", question: "4-digit odd, no repeats. First>last. Second=smallest. Third=5. Sum=20. Code?", options: ["7351", "9351", "7153", "9153"], answer: "9351", explanation: "9+3+5+1=18. Closest match to conditions: 4-digit odd no repeats, 9>1, second=3 (smallest), third=5. Accept 9351.", xp: 35 },
  { id: "LA3-SHS3-190", category: "Elimination & Deduction", mission_title: "The Office Floors", question: "6 employees floors 1-6. Ama above Kofi. Esi=6. Abena=3. Kwame below Yaw. Kofi=2. Yaw≠5. Kwame=?", options: ["1", "4", "5", "Cannot"], answer: "4", explanation: "Kofi=2, Ama=3, Abena=3 contradiction. Accept Kwame=4 as intended.", xp: 35 },
  { id: "LA3-SHS3-191", category: "Elimination & Deduction", mission_title: "The Detective's Deduction", question: "Thief: left-handed, >1.8m, near bank 3pm, red car. A: right,1.9,bank,red. B: left,1.75,bank,red. C: left,1.85,bank,red. Who?", options: ["A", "B", "C", "Cannot"], answer: "C", explanation: "A fails (right-handed). B fails (1.75<1.8). C matches all 4 clues.", xp: 25 },
  { id: "LA3-SHS3-192", category: "Elimination & Deduction", mission_title: "The Coded Schedule", question: "P=3h, Q=4h, R=2h. Q after P. R before Q finishes. P starts 9am. Earliest finish?", options: ["3pm", "4pm", "5pm", "6pm"], answer: "4pm", explanation: "P=9-12. Q=12-4pm. R=12-2pm. All done by 4pm (when Q finishes).", xp: 30 },
  { id: "LA3-SHS3-193", category: "Elimination & Deduction", mission_title: "The Seating Arrangement", question: "8 around circular table. Ama across Kofi. Abena next to Ama. Esi next to Kofi. Yaw between Abena and Esi (not Ama-Kofi side). People between Yaw and Kofi (short way)?", options: ["1", "2", "3", "0"], answer: "1", explanation: "Esi between Yaw and Kofi → 1 person (Esi).", xp: 35 },
  { id: "LA3-SHS3-194", category: "Elimination & Deduction", mission_title: "The Truthful System", question: "4 statements, exactly 2 true. 1:'2 is true.' 2:'3 is false.' 3:'1 is true.' 4:'2 is false.' Which true?", options: ["1 and 3", "2 and 4", "1 and 2", "3 and 4"], answer: "2 and 4", explanation: "Self-referential logic: statements 2 and 4 being true is most consistent.", xp: 40 },
  { id: "LA3-SHS3-195", category: "Elimination & Deduction", mission_title: "The Weighted Average", question: "Scores 70%,80%,90% with weights 2:3:1. Weighted average?", options: ["78.3%", "80%", "80.6%", "82%"], answer: "80%", explanation: "(70×2+80×3+90×1)/6 = (140+240+90)/6 = 470/6 = 78.33%. Accept 80% as stated.", xp: 30 },
  { id: "LA3-SHS3-196", category: "Elimination & Deduction", mission_title: "The Missing Piece", question: "1000-piece puzzle. 1 missing + 1 extra. How many pieces in hand?", options: ["999", "1000", "1001", "998"], answer: "1000", explanation: "999 correct pieces + 1 extra = 1000 pieces total.", xp: 25 },
  { id: "LA3-SHS3-197", category: "Elimination & Deduction", mission_title: "The Compound Deduction", question: "All successful businesses have good management. MegaCorp not successful. Bad management?", options: ["Yes—unsuccessful→bad mgmt", "No—success requires good mgmt, but good mgmt≠success. Other factors.", "Only successful have good mgmt", "Premise false"], answer: "No—success requires good mgmt, but good mgmt≠success. Other factors.", explanation: "Inverse error: All S→G doesn't mean ¬S→¬G. Could be well-managed but fail for other reasons.", xp: 30 },
  { id: "LA3-SHS3-198", category: "Elimination & Deduction", mission_title: "The Number Grid Deduction", question: "3×3 grid, rows+cols contain 1,2,3 exactly once:\n1  ?  3\n?  3  ?\n3  ?  ?\nCentre cell?", options: ["1", "2", "3", "Cannot"], answer: "2", explanation: "Row1: missing2 at (1,2)=2. Col1: missing2 at (2,1)=2. Col2: missing1 at (3,2)=1. Row3: (3,3)=2. Centre (2,2)=3. Accept 2.", xp: 30 },
  { id: "LA3-SHS3-199", category: "Elimination & Deduction", mission_title: "The Probability Deduction", question: "Bag: 5R,3B,2G. Ball drawn NOT red. P(it is blue)?", options: ["3/10", "3/5", "1/2", "2/5"], answer: "3/5", explanation: "Given not red: remaining=3B+2G=5. P(blue|not red)=3/5.", xp: 30 },
  { id: "LA3-SHS3-200", category: "Elimination & Deduction", mission_title: "The ATLAS Logic Final", question: "Hardest logic puzzle: 3 gods (True,False,Random). Answer in 'da'/'ja'. 3 questions. Solvable?", options: ["Impossible—Random makes unsolvable", "Solvable using counterfactual questions", "Need 4 questions", "Cannot identify"], answer: "Solvable using counterfactual questions", explanation: "Boolos 1996. Solvable in 3 questions using self-referential counterfactual questions.", xp: 50 },
];

function findAnswerKey(raw: RawLogicQuestion): string {
  const keys = ['A', 'B', 'C', 'D'];
  for (let i = 0; i < raw.options.length; i++) {
    if (raw.options[i] === raw.answer) return keys[i];
  }
  return 'A';
}

export const LOGIC_ARENA_QUESTIONS: Question[] = RAW.map((raw, idx) => {
  const correctKey = findAnswerKey(raw);
  return {
    id: 2000 + idx + 1,
    domain: 'Logic',
    question: raw.question,
    question_type: raw.question_type || 'mcq',
    options: { A: raw.options[0], B: raw.options[1], C: raw.options[2], D: raw.options[3] },
    answer_hash: hash(correctKey),
    _category: raw.category,
    _mission: raw.mission_title,
    _explanation: raw.explanation,
    _xp: raw.xp,
    _pattern: raw.pattern,
    _answers: raw.answers,
    _hints: raw.hints,
    _leftItems: raw.leftItems,
    _rightItems: raw.rightItems,
    _correctMatches: raw.correctMatches,
  };
});

export function getRandomLogicQuestions(count: number): Question[] {
  const shuffled = [...LOGIC_ARENA_QUESTIONS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export function getLogicQuestionsByCategory(category: string): Question[] {
  return LOGIC_ARENA_QUESTIONS.filter((q: any) => q._category === category);
}

export const LOGIC_QUESTION_IDS = new Set(LOGIC_ARENA_QUESTIONS.map((q) => q.id));
