/**
 * quantArenaData.ts
 * ───────────────────
 * SHS 1 Quantitative Sprint — 200 curriculum-aligned questions across 10 categories.
 * Used directly by the frontend arena without requiring backend connectivity.
 *
 * Covers: Fractions & Percentages, Profit/Loss/Interest, Algebra & Expressions,
 * Linear Equations, Geometry & Pythagoras, Perimeter/Area/Volume,
 * Statistics & Averages, Probability, Vectors & Trigonometry, Word Problems.
 * Aligned to Ghana GES SHS 1 Core Mathematics (Sections 2–9).
 */

import type { Question } from './challengesApi';

/** Obfuscation secret must match the backend's OBFUSCATION_SALT */
const OB_SALT = 'ST_SEC_2024';

function hash(answerKey: string): string {
  if (typeof btoa === 'undefined') return '';
  return btoa(`${OB_SALT}:${answerKey}`);
}

export interface RawQuantQuestion {
  id: string;
  category: string;
  mission_title: string;
  question: string;
  options: [string, string, string, string];
  answer: string;
  explanation: string;
  xp: number;
}

const RAW: RawQuantQuestion[] = [
  { id: "QS-SHS1-001", category: "Fractions & Percentages", mission_title: "The Market Split", question: "Ama has ¾ of a loaf of bread. She gives ⅓ of what she has to her friend. What fraction of the original loaf does she give away?", options: ["¼", "⅓", "½", "⅙"], answer: "¼", explanation: "She gives away ⅓ of ¾. ⅓ × ¾ = 3/12 = ¼.", xp: 20 },
  { id: "QS-SHS1-002", category: "Profit, Loss & Interest", mission_title: "The Shop Keeper", question: "A trader buys a bag for GH₵120 and sells it for GH₵150. What is the percentage profit?", options: ["20%", "25%", "30%", "15%"], answer: "25%", explanation: "Profit = 150 − 120 = GH₵30. % Profit = (30/120) × 100 = 25%.", xp: 20 },
  { id: "QS-SHS1-003", category: "Fractions & Percentages", mission_title: "The Price Tag", question: "A shirt originally costs GH₵80. It is on sale at a 15% discount. What is the sale price?", options: ["GH₵68", "GH₵65", "GH₵72", "GH₵70"], answer: "GH₵68", explanation: "Discount = 15% × 80 = GH₵12. Sale price = 80 − 12 = GH₵68.", xp: 20 },
  { id: "QS-SHS1-004", category: "Profit, Loss & Interest", mission_title: "The Investment", question: "Kofi invests GH₵800 at a simple interest rate of 12% per year. How much interest does he earn after 2 years?", options: ["GH₵192", "GH₵96", "GH₵160", "GH₵200"], answer: "GH₵192", explanation: "Simple Interest = PRT/100 = (800 × 12 × 2)/100 = GH₵192.", xp: 20 },
  { id: "QS-SHS1-005", category: "Fractions & Percentages", mission_title: "The Fraction Race", question: "Simplify: ⅝ + ¾", options: ["11/8", "8/12", "1⅜", "1½"], answer: "1⅜", explanation: "⅝ + ¾ = 5/8 + 6/8 = 11/8 = 1⅜.", xp: 15 },
  { id: "QS-SHS1-006", category: "Algebra & Expressions", mission_title: "The Expression Decoder", question: "Expand and simplify: 3(2x + 4) − 2(x − 1)", options: ["4x + 14", "4x + 10", "6x + 14", "8x + 10"], answer: "4x + 14", explanation: "3(2x+4) = 6x+12. −2(x−1) = −2x+2. Combined: 6x+12−2x+2 = 4x+14.", xp: 20 },
  { id: "QS-SHS1-007", category: "Linear Equations & Inequalities", mission_title: "The Unknown Agent", question: "Solve for x: 3x + 7 = 22", options: ["x = 5", "x = 4", "x = 6", "x = 3"], answer: "x = 5", explanation: "3x = 22 − 7 = 15. x = 15/3 = 5.", xp: 15 },
  { id: "QS-SHS1-008", category: "Perimeter, Area & Volume", mission_title: "The Field Measure", question: "A rectangular field is 45 m long and 30 m wide. What is its area?", options: ["1200 m²", "1350 m²", "1500 m²", "900 m²"], answer: "1350 m²", explanation: "Area = length × width = 45 × 30 = 1350 m².", xp: 15 },
  { id: "QS-SHS1-009", category: "Statistics & Averages", mission_title: "The Score Sheet", question: "Five students scored: 72, 85, 60, 91, 77. What is their mean score?", options: ["77", "78", "79", "80"], answer: "77", explanation: "Mean = (72+85+60+91+77)/5 = 385/5 = 77.", xp: 15 },
  { id: "QS-SHS1-010", category: "Probability", mission_title: "The Lucky Draw", question: "A bag contains 4 red balls, 3 blue balls, and 5 green balls. What is the probability of picking a blue ball at random?", options: ["3/12", "1/4", "3/11", "1/3"], answer: "1/4", explanation: "Total = 4+3+5 = 12. P(blue) = 3/12 = 1/4.", xp: 15 },
  { id: "QS-SHS1-011", category: "Geometry & Pythagoras", mission_title: "The Ladder Problem", question: "A ladder 13 m long leans against a wall. Its foot is 5 m from the base of the wall. How high up the wall does the ladder reach?", options: ["10 m", "11 m", "12 m", "8 m"], answer: "12 m", explanation: "h² + 5² = 13². h² = 169 − 25 = 144. h = 12 m.", xp: 20 },
  { id: "QS-SHS1-012", category: "Fractions & Percentages", mission_title: "The Decimal Switch", question: "Convert 0.375 to a fraction in its simplest form.", options: ["3/8", "3/10", "375/1000", "37/100"], answer: "3/8", explanation: "0.375 = 375/1000. Simplify: divide by 125 → 3/8.", xp: 20 },
  { id: "QS-SHS1-013", category: "Algebra & Expressions", mission_title: "The Factorisation Mission", question: "Factorise completely: x² − 9", options: ["(x−3)(x−3)", "(x+3)(x−3)", "(x+9)(x−1)", "(x−9)(x+1)"], answer: "(x+3)(x−3)", explanation: "x² − 9 is a difference of two squares: a²−b² = (a+b)(a−b). So x²−3² = (x+3)(x−3).", xp: 25 },
  { id: "QS-SHS1-014", category: "Linear Equations & Inequalities", mission_title: "The Two Variable Puzzle", question: "Solve simultaneously: x + y = 10 and x − y = 4. What is x?", options: ["5", "6", "7", "8"], answer: "7", explanation: "Add both equations: 2x = 14. x = 7. Then y = 10−7 = 3.", xp: 25 },
  { id: "QS-SHS1-015", category: "Perimeter, Area & Volume", mission_title: "The Paint Job", question: "A circular floor has a radius of 7 m. What is its area? (Use π = 22/7)", options: ["154 m²", "144 m²", "140 m²", "176 m²"], answer: "154 m²", explanation: "Area = πr² = (22/7) × 7² = (22/7) × 49 = 22 × 7 = 154 m².", xp: 20 },
  { id: "QS-SHS1-016", category: "Statistics & Averages", mission_title: "The Middle Man", question: "Find the median of the following data: 12, 7, 19, 4, 15, 8, 11", options: ["11", "12", "8", "15"], answer: "11", explanation: "Arrange in order: 4, 7, 8, 11, 12, 15, 19. The middle value (4th of 7) is 11.", xp: 20 },
  { id: "QS-SHS1-017", category: "Probability", mission_title: "The Double Flip", question: "A fair coin is flipped twice. What is the probability of getting two Heads?", options: ["1/4", "1/2", "1/3", "3/4"], answer: "1/4", explanation: "P(H) = 1/2. P(H and H) = 1/2 × 1/2 = 1/4. The events are independent.", xp: 20 },
  { id: "QS-SHS1-018", category: "Profit, Loss & Interest", mission_title: "The Loss Report", question: "A phone bought for GH₵600 is sold for GH₵510. What is the percentage loss?", options: ["10%", "12%", "15%", "8%"], answer: "15%", explanation: "Loss = 600−510 = GH₵90. % Loss = (90/600) × 100 = 15%.", xp: 20 },
  { id: "QS-SHS1-019", category: "Algebra & Expressions", mission_title: "The Simplify Station", question: "Simplify: (3x²y)(4xy³)", options: ["12x³y⁴", "7x³y⁴", "12x²y³", "12x³y³"], answer: "12x³y⁴", explanation: "Multiply coefficients: 3×4=12. Add powers: x²×x=x³, y×y³=y⁴. Answer: 12x³y⁴.", xp: 25 },
  { id: "QS-SHS1-020", category: "Geometry & Pythagoras", mission_title: "The Triangle Check", question: "The angles of a triangle are in the ratio 2:3:4. What is the size of the largest angle?", options: ["60°", "80°", "90°", "40°"], answer: "80°", explanation: "Total parts = 2+3+4 = 9. Each part = 180°/9 = 20°. Largest = 4×20° = 80°.", xp: 20 },
  { id: "QS-SHS1-021", category: "Fractions & Percentages", mission_title: "The Percentage Rise", question: "The price of rice increased from GH₵50 to GH₵65. What is the percentage increase?", options: ["25%", "30%", "15%", "20%"], answer: "30%", explanation: "Increase = 65−50 = 15. % increase = (15/50) × 100 = 30%.", xp: 20 },
  { id: "QS-SHS1-022", category: "Perimeter, Area & Volume", mission_title: "The Box Builder", question: "A rectangular box is 8 cm long, 5 cm wide, and 4 cm high. What is its volume?", options: ["140 cm³", "160 cm³", "200 cm³", "120 cm³"], answer: "160 cm³", explanation: "Volume = l × w × h = 8 × 5 × 4 = 160 cm³.", xp: 15 },
  { id: "QS-SHS1-023", category: "Statistics & Averages", mission_title: "The Most Common", question: "Find the mode of: 5, 8, 3, 8, 7, 5, 8, 2, 5, 8", options: ["5", "8", "7", "3"], answer: "8", explanation: "Count: 5 appears 3 times, 8 appears 4 times. The mode is 8.", xp: 15 },
  { id: "QS-SHS1-024", category: "Linear Equations & Inequalities", mission_title: "The Formula Flip", question: "Make r the subject of the formula: A = πr²", options: ["r = A/π", "r = √(A/π)", "r = √(Aπ)", "r = A²/π"], answer: "r = √(A/π)", explanation: "A = πr². Divide both sides by π: A/π = r². Take square root: r = √(A/π).", xp: 25 },
  { id: "QS-SHS1-025", category: "Probability", mission_title: "The Dice Roll", question: "A fair die is rolled once. What is the probability of getting a number greater than 4?", options: ["1/6", "2/6", "3/6", "4/6"], answer: "2/6", explanation: "Numbers greater than 4 are: 5 and 6. That is 2 outcomes out of 6. P = 2/6 = 1/3.", xp: 15 },
  { id: "QS-SHS1-026", category: "Algebra & Expressions", mission_title: "The Perfect Square", question: "Expand: (x + 5)²", options: ["x² + 25", "x² + 10x + 25", "x² + 5x + 25", "x² + 10x + 10"], answer: "x² + 10x + 25", explanation: "(x+5)² = x² + 2(x)(5) + 5² = x² + 10x + 25.", xp: 20 },
  { id: "QS-SHS1-027", category: "Geometry & Pythagoras", mission_title: "The Angle Hunt", question: "Two angles of a triangle are 47° and 68°. What is the third angle?", options: ["55°", "65°", "75°", "85°"], answer: "65°", explanation: "Sum of angles in a triangle = 180°. Third angle = 180°−47°−68° = 65°.", xp: 15 },
  { id: "QS-SHS1-028", category: "Fractions & Percentages", mission_title: "The Fraction Divide", question: "Calculate: 2½ ÷ ¾", options: ["3⅓", "1⅔", "2", "3"], answer: "3⅓", explanation: "2½ = 5/2. Dividing: 5/2 ÷ 3/4 = 5/2 × 4/3 = 20/6 = 10/3 = 3⅓.", xp: 25 },
  { id: "QS-SHS1-029", category: "Profit, Loss & Interest", mission_title: "The Compound Plan", question: "GH₵1000 is invested at 10% compound interest for 2 years. What is the total amount at the end?", options: ["GH₵1200", "GH₵1210", "GH₵1100", "GH₵1220"], answer: "GH₵1210", explanation: "Year 1: 1000 × 1.10 = GH₵1100. Year 2: 1100 × 1.10 = GH₵1210.", xp: 30 },
  { id: "QS-SHS1-030", category: "Perimeter, Area & Volume", mission_title: "The Fence Builder", question: "A square garden has a perimeter of 52 m. What is the area of the garden?", options: ["144 m²", "156 m²", "169 m²", "196 m²"], answer: "169 m²", explanation: "Side = 52/4 = 13 m. Area = 13² = 169 m².", xp: 20 },
  { id: "QS-SHS1-031", category: "Statistics & Averages", mission_title: "The Data Gap", question: "The mean of 6 numbers is 15. Five of the numbers are 12, 18, 10, 20, and 14. What is the sixth number?", options: ["14", "16", "18", "20"], answer: "16", explanation: "Total sum = 6×15 = 90. Sum of five = 12+18+10+20+14 = 74. Sixth = 90−74 = 16.", xp: 25 },
  { id: "QS-SHS1-032", category: "Linear Equations & Inequalities", mission_title: "The Inequality Line", question: "Solve the inequality: 2x − 3 > 7", options: ["x > 2", "x > 5", "x > 4", "x > 6"], answer: "x > 5", explanation: "2x − 3 > 7 → 2x > 10 → x > 5.", xp: 20 },
  { id: "QS-SHS1-033", category: "Vectors & Trigonometry", mission_title: "The Right Triangle", question: "In a right-angled triangle, the opposite side is 3 cm and the hypotenuse is 5 cm. What is sin θ?", options: ["3/5", "4/5", "3/4", "5/3"], answer: "3/5", explanation: "sin θ = opposite/hypotenuse = 3/5.", xp: 20 },
  { id: "QS-SHS1-034", category: "Algebra & Expressions", mission_title: "The Factorisation Lab", question: "Factorise: 6x² + 9x", options: ["3x(2x + 3)", "6x(x + 3)", "3(2x² + 3x)", "9x(x + 1)"], answer: "3x(2x + 3)", explanation: "HCF of 6x² and 9x is 3x. So 6x² + 9x = 3x(2x + 3).", xp: 20 },
  { id: "QS-SHS1-035", category: "Word Problems", mission_title: "The Age Equation", question: "Ama is 3 times as old as her daughter. The sum of their ages is 48. How old is Ama?", options: ["32", "36", "30", "40"], answer: "36", explanation: "Let daughter = x. Ama = 3x. x + 3x = 48 → 4x = 48 → x = 12. Ama = 3×12 = 36.", xp: 25 },
  { id: "QS-SHS1-036", category: "Perimeter, Area & Volume", mission_title: "The Triangle Area", question: "A triangle has a base of 14 cm and a height of 9 cm. What is its area?", options: ["63 cm²", "126 cm²", "72 cm²", "56 cm²"], answer: "63 cm²", explanation: "Area = ½ × base × height = ½ × 14 × 9 = 63 cm².", xp: 15 },
  { id: "QS-SHS1-037", category: "Probability", mission_title: "The Card Pull", question: "A card is drawn from a standard deck of 52 cards. What is the probability of drawing a King?", options: ["1/13", "4/52", "1/12", "4/13"], answer: "1/13", explanation: "There are 4 Kings in 52 cards. P = 4/52 = 1/13.", xp: 20 },
  { id: "QS-SHS1-038", category: "Fractions & Percentages", mission_title: "The Commission Agent", question: "A salesman earns a 5% commission on sales. He sold goods worth GH₵3,400. How much commission did he earn?", options: ["GH₵160", "GH₵170", "GH₵175", "GH₵180"], answer: "GH₵170", explanation: "Commission = 5% × 3400 = (5/100) × 3400 = GH₵170.", xp: 20 },
  { id: "QS-SHS1-039", category: "Algebra & Expressions", mission_title: "The Algebraic Fraction", question: "Simplify: (x² − 4) / (x − 2)", options: ["x + 2", "x − 2", "x² + 2", "2x"], answer: "x + 2", explanation: "x²−4 = (x+2)(x−2). Divide by (x−2): result is (x+2), where x ≠ 2.", xp: 25 },
  { id: "QS-SHS1-040", category: "Geometry & Pythagoras", mission_title: "The Parallel Lines", question: "Two parallel lines are cut by a transversal. One co-interior angle is 65°. What is the other co-interior angle?", options: ["65°", "115°", "125°", "75°"], answer: "115°", explanation: "Co-interior (same-side interior) angles are supplementary: they add up to 180°. 180°−65° = 115°.", xp: 20 },
  { id: "QS-SHS1-041", category: "Word Problems", mission_title: "The Speed Mission", question: "A car travels at 90 km/h. How far will it travel in 2 hours 30 minutes?", options: ["200 km", "215 km", "225 km", "180 km"], answer: "225 km", explanation: "2 hours 30 min = 2.5 hours. Distance = Speed × Time = 90 × 2.5 = 225 km.", xp: 20 },
  { id: "QS-SHS1-042", category: "Statistics & Averages", mission_title: "The Frequency Table", question: "A frequency table shows scores: 50 (frequency 3), 60 (frequency 5), 70 (frequency 2). What is the mean score?", options: ["58", "59", "60", "61"], answer: "59", explanation: "Sum = (50×3)+(60×5)+(70×2) = 150+300+140 = 590. Total frequency = 10. Mean = 590/10 = 59.", xp: 25 },
  { id: "QS-SHS1-043", category: "Vectors & Trigonometry", mission_title: "The Cosine Quest", question: "In a right-angled triangle, the adjacent side is 4 cm and the hypotenuse is 5 cm. What is cos θ?", options: ["4/5", "3/5", "3/4", "5/4"], answer: "4/5", explanation: "cos θ = adjacent/hypotenuse = 4/5.", xp: 20 },
  { id: "QS-SHS1-044", category: "Linear Equations & Inequalities", mission_title: "The Gradient Finder", question: "Find the gradient of the line passing through points (2, 3) and (6, 11).", options: ["1", "2", "3", "4"], answer: "2", explanation: "Gradient = (y₂−y₁)/(x₂−x₁) = (11−3)/(6−2) = 8/4 = 2.", xp: 25 },
  { id: "QS-SHS1-045", category: "Perimeter, Area & Volume", mission_title: "The Cylinder Storage", question: "A cylindrical tank has a radius of 3 m and a height of 5 m. What is its volume? (Use π = 3.14)", options: ["127.17 m³", "141.3 m³", "113.04 m³", "150 m³"], answer: "141.3 m³", explanation: "Volume = πr²h = 3.14 × 9 × 5 = 3.14 × 45 = 141.3 m³.", xp: 25 },
  { id: "QS-SHS1-046", category: "Fractions & Percentages", mission_title: "The VAT Calculation", question: "An item costs GH₵200 before tax. A 15% VAT is added. What is the final price?", options: ["GH₵215", "GH₵225", "GH₵230", "GH₵240"], answer: "GH₵230", explanation: "VAT = 15% × 200 = GH₵30. Final price = 200 + 30 = GH₵230.", xp: 20 },
  { id: "QS-SHS1-047", category: "Algebra & Expressions", mission_title: "The Expression Match", question: "If a = 3 and b = −2, find the value of: 2a² − 3b", options: ["12", "18", "24", "22"], answer: "24", explanation: "2(3)² − 3(−2) = 2×9 + 6 = 18 + 6 = 24.", xp: 20 },
  { id: "QS-SHS1-048", category: "Probability", mission_title: "The Two Dice", question: "Two fair dice are rolled. What is the probability that both show a 6?", options: ["1/36", "1/12", "1/6", "2/36"], answer: "1/36", explanation: "P(6 on first) × P(6 on second) = 1/6 × 1/6 = 1/36.", xp: 25 },
  { id: "QS-SHS1-049", category: "Geometry & Pythagoras", mission_title: "The Polygon Interior", question: "What is the sum of the interior angles of a hexagon?", options: ["540°", "600°", "720°", "900°"], answer: "720°", explanation: "Sum of interior angles = (n−2) × 180° = (6−2) × 180° = 4 × 180° = 720°.", xp: 20 },
  { id: "QS-SHS1-050", category: "Word Problems", mission_title: "The Work Rate", question: "Ama can complete a task in 6 hours. Kofi takes 3 hours. How long will they take working together?", options: ["2 hours", "2.5 hours", "3 hours", "4 hours"], answer: "2 hours", explanation: "Ama: 1/6 per hr. Kofi: 1/3 per hr. Combined: 1/6+2/6 = 3/6 = 1/2 per hr. Time = 2 hours.", xp: 25 },
  { id: "QS-SHS1-051", category: "Profit, Loss & Interest", mission_title: "The Utility Bill", question: "A family's electricity bill is GH₵120. A 10% discount is applied for early payment. How much do they pay?", options: ["GH₵108", "GH₵110", "GH₵112", "GH₵105"], answer: "GH₵108", explanation: "Discount = 10% × 120 = GH₵12. Amount paid = 120−12 = GH₵108.", xp: 15 },
  { id: "QS-SHS1-052", category: "Fractions & Percentages", mission_title: "The Mixed Number", question: "Calculate: 3¾ − 1⅔", options: ["1 11/12", "2 1/12", "2⅓", "1¾"], answer: "2 1/12", explanation: "3¾ = 45/12. 1⅔ = 20/12. Difference = 25/12 = 2 1/12.", xp: 25 },
  { id: "QS-SHS1-053", category: "Algebra & Expressions", mission_title: "The Pattern Formula", question: "The nth term of a sequence is given by 3n + 2. What is the 8th term?", options: ["24", "26", "28", "30"], answer: "26", explanation: "nth term = 3n+2. When n=8: 3(8)+2 = 24+2 = 26.", xp: 20 },
  { id: "QS-SHS1-054", category: "Statistics & Averages", mission_title: "The Range Finder", question: "Find the range of the data: 14, 27, 9, 35, 22, 18", options: ["24", "26", "27", "16"], answer: "26", explanation: "Range = highest − lowest = 35 − 9 = 26.", xp: 15 },
  { id: "QS-SHS1-055", category: "Linear Equations & Inequalities", mission_title: "The Equation With Fractions", question: "Solve: x/3 + x/4 = 14", options: ["x = 24", "x = 28", "x = 32", "x = 36"], answer: "x = 24", explanation: "LCM of 3 and 4 is 12. Multiply through: 4x + 3x = 168. 7x = 168. x = 24.", xp: 25 },
  { id: "QS-SHS1-056", category: "Vectors & Trigonometry", mission_title: "The Tangent Trap", question: "In a right-angled triangle, the opposite side is 5 cm and the adjacent side is 5 cm. What is tan θ?", options: ["1", "√2", "0.5", "2"], answer: "1", explanation: "tan θ = opposite/adjacent = 5/5 = 1. This means θ = 45°.", xp: 20 },
  { id: "QS-SHS1-057", category: "Geometry & Pythagoras", mission_title: "The Exterior Angle", question: "An exterior angle of a triangle is 110°. One of the non-adjacent interior angles is 65°. What is the other non-adjacent interior angle?", options: ["35°", "40°", "45°", "55°"], answer: "45°", explanation: "Exterior angle = sum of the two non-adjacent interior angles. 110° = 65° + x. x = 45°.", xp: 25 },
  { id: "QS-SHS1-058", category: "Probability", mission_title: "The Sample Space", question: "A coin is tossed and a die is rolled. How many outcomes are in the sample space?", options: ["6", "8", "12", "10"], answer: "12", explanation: "Coin has 2 outcomes (H, T). Die has 6 outcomes. Total = 2 × 6 = 12.", xp: 20 },
  { id: "QS-SHS1-059", category: "Perimeter, Area & Volume", mission_title: "The Trapezium Area", question: "A trapezium has parallel sides of 8 cm and 12 cm, and a height of 5 cm. What is its area?", options: ["40 cm²", "50 cm²", "60 cm²", "45 cm²"], answer: "50 cm²", explanation: "Area = ½(a+b)×h = ½(8+12)×5 = ½×20×5 = 50 cm².", xp: 25 },
  { id: "QS-SHS1-060", category: "Word Problems", mission_title: "The Sharing Formula", question: "GH₵360 is shared among Ama, Kofi, and Abena in the ratio 2:3:4. How much does Kofi receive?", options: ["GH₵80", "GH₵90", "GH₵100", "GH₵120"], answer: "GH₵120", explanation: "Total parts = 2+3+4 = 9. Each part = 360/9 = 40. Kofi = 3×40 = GH₵120.", xp: 20 },
  { id: "QS-SHS1-061", category: "Fractions & Percentages", mission_title: "The Exchange Rate", question: "The exchange rate is $1 = GH₵14.50. How much is $35 in cedis?", options: ["GH₵480", "GH₵490", "GH₵507.50", "GH₵510"], answer: "GH₵507.50", explanation: "Amount = 35 × 14.50 = GH₵507.50.", xp: 20 },
  { id: "QS-SHS1-062", category: "Algebra & Expressions", mission_title: "The Difference of Squares", question: "Evaluate using the difference of two squares: 47² − 43²", options: ["360", "380", "400", "420"], answer: "360", explanation: "a²−b² = (a+b)(a−b) = (47+43)(47−43) = 90 × 4 = 360.", xp: 30 },
  { id: "QS-SHS1-063", category: "Linear Equations & Inequalities", mission_title: "The Line Equation", question: "A straight line has gradient 3 and passes through the point (0, −2). What is its equation?", options: ["y = 3x − 2", "y = −2x + 3", "y = 3x + 2", "y = 2x − 3"], answer: "y = 3x − 2", explanation: "Using y = mx + c: gradient m = 3, y-intercept c = −2. Equation: y = 3x − 2.", xp: 25 },
  { id: "QS-SHS1-064", category: "Geometry & Pythagoras", mission_title: "The Pythagoras Check", question: "A triangle has sides 7 cm, 24 cm, and 25 cm. Is it a right-angled triangle?", options: ["Yes, because 7²+24² = 25²", "No, the sides do not satisfy Pythagoras", "Yes, because all three sides are different", "Cannot be determined"], answer: "Yes, because 7²+24² = 25²", explanation: "7²+24² = 49+576 = 625 = 25². Pythagoras theorem is satisfied, so it is right-angled.", xp: 25 },
  { id: "QS-SHS1-065", category: "Statistics & Averages", mission_title: "The Pie Chart", question: "In a class of 40 students, 10 prefer Mathematics. What angle would represent Mathematics in a pie chart?", options: ["45°", "72°", "90°", "36°"], answer: "90°", explanation: "Angle = (frequency/total) × 360° = (10/40) × 360° = ¼ × 360° = 90°.", xp: 20 },
  { id: "QS-SHS1-066", category: "Profit, Loss & Interest", mission_title: "The Loan Repayment", question: "Esi takes a loan of GH₵2000 at 8% simple interest per year. She repays after 3 years. What is the total amount she pays back?", options: ["GH₵2380", "GH₵2440", "GH₵2480", "GH₵2500"], answer: "GH₵2480", explanation: "Interest = (2000×8×3)/100 = GH₵480. Total = 2000+480 = GH₵2480.", xp: 25 },
  { id: "QS-SHS1-067", category: "Algebra & Expressions", mission_title: "The Substitution Switch", question: "If p = 2 and q = −3, find the value of: p³ − 2q", options: ["14", "12", "16", "10"], answer: "14", explanation: "p³ − 2q = 2³ − 2(−3) = 8 + 6 = 14.", xp: 20 },
  { id: "QS-SHS1-068", category: "Vectors & Trigonometry", mission_title: "The Bearing Mission", question: "A ship travels on a bearing of 090°. In what direction is it heading?", options: ["North", "South", "East", "West"], answer: "East", explanation: "Bearings are measured clockwise from North. 090° = due East.", xp: 20 },
  { id: "QS-SHS1-069", category: "Perimeter, Area & Volume", mission_title: "The Composite Shape", question: "A shape consists of a rectangle (6 cm × 4 cm) with a semicircle on one end (diameter 4 cm). What is the total area? (Use π = 3.14)", options: ["30.28 cm²", "32.28 cm²", "28 cm²", "30 cm²"], answer: "30.28 cm²", explanation: "Rectangle area = 6×4 = 24 cm². Semicircle area = ½×π×r² = ½×3.14×4 = 6.28 cm². Total = 24+6.28 = 30.28 cm².", xp: 30 },
  { id: "QS-SHS1-070", category: "Word Problems", mission_title: "The Pipe Problem", question: "Pipe A fills a tank in 4 hours. Pipe B fills it in 6 hours. Both pipes are opened together. How long does the tank take to fill?", options: ["2 hours", "2.2 hours", "2.4 hours", "3 hours"], answer: "2.4 hours", explanation: "Rate A = 1/4, Rate B = 1/6. Combined = 1/4+1/6 = 3/12+2/12 = 5/12 per hr. Time = 12/5 = 2.4 hours.", xp: 30 },
  { id: "QS-SHS1-071", category: "Fractions & Percentages", mission_title: "The Fraction Wall", question: "Which of the following is the greatest? ⅔, ¾, ⁵⁄₈, ⁷⁄₁₀", options: ["⅔", "¾", "⁵⁄₈", "⁷⁄₁₀"], answer: "¾", explanation: "Convert to decimals: ⅔≈0.667, ¾=0.75, ⁵⁄₈=0.625, ⁷⁄₁₀=0.7. Greatest is ¾ = 0.75.", xp: 20 },
  { id: "QS-SHS1-072", category: "Statistics & Averages", mission_title: "The Bar Chart Read", question: "A bar chart shows sales for Monday=50, Tuesday=70, Wednesday=40, Thursday=80, Friday=60. What is the mean daily sales?", options: ["55", "58", "60", "62"], answer: "60", explanation: "Mean = (50+70+40+80+60)/5 = 300/5 = 60.", xp: 20 },
  { id: "QS-SHS1-073", category: "Geometry & Pythagoras", mission_title: "The Alternate Angles", question: "Two parallel lines are cut by a transversal. One alternate interior angle is 55°. What is the other alternate interior angle?", options: ["35°", "55°", "125°", "145°"], answer: "55°", explanation: "Alternate interior angles are equal when lines are parallel. So the other angle is also 55°.", xp: 15 },
  { id: "QS-SHS1-074", category: "Algebra & Expressions", mission_title: "The Complete Factorisation", question: "Factorise completely: 2x² − 8", options: ["2(x²−4)", "2(x+2)(x−2)", "(2x+4)(x−2)", "(x+2)(2x−4)"], answer: "2(x+2)(x−2)", explanation: "First take out 2: 2(x²−4). Then factorise x²−4 as (x+2)(x−2). Final: 2(x+2)(x−2).", xp: 25 },
  { id: "QS-SHS1-075", category: "Linear Equations & Inequalities", mission_title: "The Distance Formula", question: "Find the distance between points (1, 2) and (4, 6).", options: ["3", "4", "5", "6"], answer: "5", explanation: "d = √((4−1)²+(6−2)²) = √(9+16) = √25 = 5.", xp: 25 },
  { id: "QS-SHS1-076", category: "Probability", mission_title: "The Complementary Event", question: "The probability that it rains on a given day is 0.35. What is the probability that it does NOT rain?", options: ["0.35", "0.55", "0.65", "0.70"], answer: "0.65", explanation: "P(not rain) = 1 − P(rain) = 1 − 0.35 = 0.65.", xp: 15 },
  { id: "QS-SHS1-077", category: "Word Problems", mission_title: "The Cement Mix", question: "Cement and sand are mixed in the ratio 1:4 to make mortar. How many kg of sand is needed to mix with 15 kg of cement?", options: ["45 kg", "50 kg", "55 kg", "60 kg"], answer: "60 kg", explanation: "Ratio cement:sand = 1:4. For 15 kg cement: sand = 4 × 15 = 60 kg.", xp: 20 },
  { id: "QS-SHS1-078", category: "Fractions & Percentages", mission_title: "The Recurring Decimal", question: "Convert the recurring decimal 0.333... to a fraction.", options: ["3/10", "1/3", "33/100", "3/9"], answer: "1/3", explanation: "Let x = 0.333... Then 10x = 3.333... Subtract: 9x = 3. x = 3/9 = 1/3.", xp: 25 },
  { id: "QS-SHS1-079", category: "Perimeter, Area & Volume", mission_title: "The Volume of a Prism", question: "A triangular prism has a triangular cross-section with base 6 cm, height 4 cm, and a length of 10 cm. What is its volume?", options: ["100 cm³", "120 cm³", "140 cm³", "160 cm³"], answer: "120 cm³", explanation: "Area of triangle = ½×6×4 = 12 cm². Volume = cross-section × length = 12×10 = 120 cm³.", xp: 25 },
  { id: "QS-SHS1-080", category: "Vectors & Trigonometry", mission_title: "The Special Angle", question: "What is the exact value of sin 30°?", options: ["√3/2", "1/2", "1/√2", "√3"], answer: "1/2", explanation: "sin 30° = 1/2. This is one of the standard special angle values.", xp: 20 },
  { id: "QS-SHS1-081", category: "Algebra & Expressions", mission_title: "The Expression Builder", question: "Simplify: (2x + 3)(x − 4)", options: ["2x² − 5x − 12", "2x² + 5x − 12", "2x² − 8x + 12", "2x² − 5x + 12"], answer: "2x² − 5x − 12", explanation: "Expand: 2x·x + 2x·(−4) + 3·x + 3·(−4) = 2x²−8x+3x−12 = 2x²−5x−12.", xp: 25 },
  { id: "QS-SHS1-082", category: "Statistics & Averages", mission_title: "The Average Update", question: "The average of 4 numbers is 18. A fifth number, 22, is added. What is the new average?", options: ["18.4", "19", "19.2", "20"], answer: "18.8", explanation: "Old total = 4×18 = 72. New total = 72+22 = 94. New average = 94/5 = 18.8.", xp: 25 },
  { id: "QS-SHS1-083", category: "Geometry & Pythagoras", mission_title: "The Regular Polygon", question: "What is each interior angle of a regular pentagon?", options: ["100°", "108°", "112°", "120°"], answer: "108°", explanation: "Sum of interior angles = (5−2)×180° = 540°. Each angle = 540°/5 = 108°.", xp: 20 },
  { id: "QS-SHS1-084", category: "Probability", mission_title: "The Coloured Counters", question: "A box has 5 red, 3 yellow and 2 green counters. Two counters are picked one after the other WITHOUT replacement. What is the probability both are red?", options: ["1/4", "2/9", "1/5", "5/18"], answer: "2/9", explanation: "P(first red) = 5/10 = 1/2. P(second red | first red) = 4/9. P(both) = 1/2 × 4/9 = 4/18 = 2/9.", xp: 30 },
  { id: "QS-SHS1-085", category: "Word Problems", mission_title: "The Salary Split", question: "Kwame earns GH₵1,800 per month. He spends 40% on food, 25% on rent, and saves the rest. How much does he save each month?", options: ["GH₵540", "GH₵600", "GH₵630", "GH₵650"], answer: "GH₵630", explanation: "Spent = 40%+25% = 65%. Saved = 35%. 35% × 1800 = GH₵630.", xp: 25 },
  { id: "QS-SHS1-086", category: "Linear Equations & Inequalities", mission_title: "The Number Line", question: "Solve and represent: −3 ≤ 2x + 1 < 7. What is the range of x?", options: ["−2 ≤ x < 3", "−1 ≤ x < 3", "−2 < x ≤ 3", "−2 ≤ x ≤ 3"], answer: "−2 ≤ x < 3", explanation: "Subtract 1: −4 ≤ 2x < 6. Divide by 2: −2 ≤ x < 3.", xp: 30 },
  { id: "QS-SHS1-087", category: "Fractions & Percentages", mission_title: "The Irrational Classifier", question: "Which of the following is an IRRATIONAL number?", options: ["0.75", "√9", "√7", "22/7"], answer: "√7", explanation: "√7 ≈ 2.6457... is non-terminating and non-recurring. It cannot be expressed as a/b. It is irrational.", xp: 20 },
  { id: "QS-SHS1-088", category: "Algebra & Expressions", mission_title: "The Algebraic Manipulation", question: "Make y the subject of the formula: 3x + 2y = 12", options: ["y = (12−3x)/2", "y = 12−3x", "y = 3x/2 − 6", "y = (12+3x)/2"], answer: "y = (12−3x)/2", explanation: "2y = 12−3x. Divide by 2: y = (12−3x)/2.", xp: 20 },
  { id: "QS-SHS1-089", category: "Perimeter, Area & Volume", mission_title: "The Circumference", question: "A wheel has a diameter of 70 cm. How far does it travel in one complete revolution? (Use π = 22/7)", options: ["220 cm", "440 cm", "110 cm", "154 cm"], answer: "220 cm", explanation: "Circumference = πd = (22/7)×70 = 22×10 = 220 cm.", xp: 20 },
  { id: "QS-SHS1-090", category: "Statistics & Averages", mission_title: "The Data Interpretation", question: "A pie chart shows that 25% of a class of 120 students prefer Science. How many students prefer Science?", options: ["25", "28", "30", "35"], answer: "30", explanation: "25% of 120 = (25/100) × 120 = 30 students.", xp: 15 },
  { id: "QS-SHS1-091", category: "Vectors & Trigonometry", mission_title: "The Exact Cosine", question: "What is the exact value of cos 60°?", options: ["√3/2", "1/√2", "1/2", "√3"], answer: "1/2", explanation: "cos 60° = 1/2. This is one of the standard special angle values.", xp: 20 },
  { id: "QS-SHS1-092", category: "Word Problems", mission_title: "The Tap and Tank", question: "A tank holds 600 litres. A tap fills it at 25 litres per minute. How long does it take to fill the tank from empty?", options: ["20 min", "24 min", "25 min", "30 min"], answer: "24 min", explanation: "Time = Volume / Rate = 600 / 25 = 24 minutes.", xp: 15 },
  { id: "QS-SHS1-093", category: "Geometry & Pythagoras", mission_title: "The Diagonal Cut", question: "A rectangle is 8 cm wide and 15 cm long. What is the length of its diagonal?", options: ["16 cm", "17 cm", "18 cm", "19 cm"], answer: "17 cm", explanation: "Diagonal² = 8²+15² = 64+225 = 289. Diagonal = √289 = 17 cm.", xp: 20 },
  { id: "QS-SHS1-094", category: "Probability", mission_title: "The Letter Bag", question: "The letters of the word MATHEMATICS are put in a bag. A letter is picked at random. What is the probability of picking the letter M?", options: ["1/11", "2/11", "2/10", "3/11"], answer: "2/11", explanation: "MATHEMATICS has 11 letters. M appears 2 times. P(M) = 2/11.", xp: 25 },
  { id: "QS-SHS1-095", category: "Algebra & Expressions", mission_title: "The Undefined Fraction", question: "For what value of x is the expression (3x+1)/(x−4) undefined?", options: ["x = 3", "x = 4", "x = −4", "x = 1/3"], answer: "x = 4", explanation: "A fraction is undefined when the denominator = 0. x−4 = 0 → x = 4.", xp: 20 },
  { id: "QS-SHS1-096", category: "Linear Equations & Inequalities", mission_title: "The Two-Variable System", question: "Solve: 2x + y = 11 and x − y = 1. What is y?", options: ["2", "3", "4", "5"], answer: "3", explanation: "Add equations: 3x = 12, x = 4. Substitute: 4−y = 1, y = 3.", xp: 25 },
  { id: "QS-SHS1-097", category: "Fractions & Percentages", mission_title: "The Percentage Back", question: "After a 20% increase, a price is GH₵96. What was the original price?", options: ["GH₵75", "GH₵76", "GH₵78", "GH₵80"], answer: "GH₵80", explanation: "Let original = x. x × 1.20 = 96. x = 96/1.20 = 80.", xp: 25 },
  { id: "QS-SHS1-098", category: "Perimeter, Area & Volume", mission_title: "The Imperial Measure", question: "Convert 5 feet to centimetres. (1 foot = 30 cm)", options: ["100 cm", "130 cm", "150 cm", "160 cm"], answer: "150 cm", explanation: "5 feet × 30 cm/foot = 150 cm.", xp: 15 },
  { id: "QS-SHS1-099", category: "Statistics & Averages", mission_title: "The Grouped Data", question: "Ages are grouped: 10-14 (8 students), 15-19 (12 students), 20-24 (5 students). What is the modal class?", options: ["10-14", "15-19", "20-24", "Cannot be determined"], answer: "15-19", explanation: "The modal class is the group with the highest frequency. 15-19 has 12 students — the highest.", xp: 20 },
  { id: "QS-SHS1-100", category: "Word Problems", mission_title: "The Profit Split", question: "Two business partners invest GH₵4,000 and GH₵6,000 respectively. They share a profit of GH₵2,500 in proportion to their investments. How much does the first partner receive?", options: ["GH₵900", "GH₵1,000", "GH₵1,100", "GH₵1,200"], answer: "GH₵1,000", explanation: "Total invested = 10,000. First partner's share = (4000/10000)×2500 = 0.4×2500 = GH₵1,000.", xp: 25 },
  { id: "QS-SHS1-101", category: "Vectors & Trigonometry", mission_title: "The tan 45", question: "What is the exact value of tan 45°?", options: ["√3", "1/√3", "1", "√2"], answer: "1", explanation: "tan 45° = sin45°/cos45° = (1/√2)/(1/√2) = 1.", xp: 20 },
  { id: "QS-SHS1-102", category: "Algebra & Expressions", mission_title: "The nth Term", question: "A sequence is: 5, 9, 13, 17, 21... What is the nth term formula?", options: ["4n + 1", "4n − 1", "n + 4", "5n − 1"], answer: "4n + 1", explanation: "The common difference is 4. Formula = a + (n−1)d = 5+(n−1)4 = 5+4n−4 = 4n+1.", xp: 25 },
  { id: "QS-SHS1-103", category: "Geometry & Pythagoras", mission_title: "The Isosceles Triangle", question: "An isosceles triangle has two equal angles of 65° each. What is the third angle?", options: ["40°", "45°", "50°", "55°"], answer: "50°", explanation: "Sum of angles = 180°. Third angle = 180°−65°−65° = 50°.", xp: 15 },
  { id: "QS-SHS1-104", category: "Probability", mission_title: "The Traffic Light", question: "A traffic light is red for 40 seconds, green for 35 seconds, and amber for 5 seconds out of every 80 seconds. What is the probability a car arrives at a green light?", options: ["7/16", "7/18", "35/80", "1/2"], answer: "7/16", explanation: "P(green) = 35/80 = 7/16.", xp: 20 },
  { id: "QS-SHS1-105", category: "Fractions & Percentages", mission_title: "The Rational Check", question: "Which of the following is a rational number?", options: ["√2", "π", "√5", "0.6666..."], answer: "0.6666...", explanation: "0.6666... = 0.6̄ = 2/3. It is a recurring decimal, which means it is rational.", xp: 20 },
  { id: "QS-SHS1-106", category: "Linear Equations & Inequalities", mission_title: "The Subject Change", question: "Make u the subject: s = ut + ½at²", options: ["u = (s − ½at²)/t", "u = s/t + ½at", "u = s − ½at²", "u = st − ½at"], answer: "u = (s − ½at²)/t", explanation: "s = ut + ½at². Subtract ½at²: s − ½at² = ut. Divide by t: u = (s − ½at²)/t.", xp: 30 },
  { id: "QS-SHS1-107", category: "Statistics & Averages", mission_title: "The Cumulative Frequency", question: "Marks scored: below 40 (5 students), 40-59 (12 students), 60-79 (18 students), 80+ (5 students). How many students scored below 80?", options: ["30", "35", "40", "25"], answer: "35", explanation: "Students below 80 = 5+12+18 = 35.", xp: 20 },
  { id: "QS-SHS1-108", category: "Perimeter, Area & Volume", mission_title: "The Sector Area", question: "A sector of a circle has radius 6 cm and an angle of 60°. What is the area of the sector? (Use π = 22/7)", options: ["18.86 cm²", "18 cm²", "22 cm²", "15.43 cm²"], answer: "18.86 cm²", explanation: "Area = (θ/360°) × πr² = (60/360) × (22/7) × 36 = (1/6) × (22×36/7) = (1/6) × 113.14 ≈ 18.86 cm².", xp: 30 },
  { id: "QS-SHS1-109", category: "Word Problems", mission_title: "The Currency Convert", question: "A student spends 2/5 of his pocket money on food and 1/4 on transport. What fraction is left?", options: ["7/20", "3/20", "9/20", "11/20"], answer: "7/20", explanation: "Spent = 2/5 + 1/4 = 8/20 + 5/20 = 13/20. Remaining = 1 − 13/20 = 7/20.", xp: 20 },
  { id: "QS-SHS1-110", category: "Algebra & Expressions", mission_title: "The Zero Condition", question: "For what value of x is the algebraic fraction (x−3)/(x+5) equal to zero?", options: ["x = −5", "x = 3", "x = 5", "x = −3"], answer: "x = 3", explanation: "A fraction equals zero when numerator = 0. x−3 = 0 → x = 3. (Note: x ≠ −5 as that makes it undefined.)", xp: 20 },
  { id: "QS-SHS1-111", category: "Geometry & Pythagoras", mission_title: "The Corresponding Angles", question: "Two parallel lines are cut by a transversal. One corresponding angle is 73°. What is the other corresponding angle?", options: ["107°", "73°", "17°", "37°"], answer: "73°", explanation: "Corresponding angles are equal when lines are parallel. The other corresponding angle is also 73°.", xp: 15 },
  { id: "QS-SHS1-112", category: "Probability", mission_title: "The Fruit Bowl", question: "A bowl has 6 oranges and 4 mangoes. Two fruits are picked without replacement. What is the probability that both are oranges?", options: ["3/10", "1/3", "36/100", "1/5"], answer: "1/3", explanation: "P(first orange) = 6/10. P(second orange) = 5/9. P(both) = 6/10 × 5/9 = 30/90 = 1/3.", xp: 30 },
  { id: "QS-SHS1-113", category: "Vectors & Trigonometry", mission_title: "The Bearing Direction", question: "A point B is due South of point A. What is the bearing of B from A?", options: ["000°", "090°", "180°", "270°"], answer: "180°", explanation: "Bearings: North = 000°, East = 090°, South = 180°, West = 270°. Due South = 180°.", xp: 20 },
  { id: "QS-SHS1-114", category: "Fractions & Percentages", mission_title: "The Closing Balance", question: "Ama had GH₵500 in her account. She deposited 30% more and then withdrew GH₵80. What is her closing balance?", options: ["GH₵535", "GH₵565", "GH₵570", "GH₵580"], answer: "GH₵570", explanation: "Deposit = 30% × 500 = GH₵150. Balance after deposit = 650. After withdrawal = 650−80 = GH₵570.", xp: 25 },
  { id: "QS-SHS1-115", category: "Profit, Loss & Interest", mission_title: "The Rate Puzzle", question: "A principal of GH₵5,000 earns a simple interest of GH₵600 in 2 years. What is the interest rate per year?", options: ["5%", "6%", "8%", "10%"], answer: "6%", explanation: "I = PRT/100. 600 = (5000 × R × 2)/100. 600 = 100R. R = 6%.", xp: 25 },
  { id: "QS-SHS1-116", category: "Algebra & Expressions", mission_title: "The Binomial Product", question: "Expand: (3x − 2)(2x + 5)", options: ["6x² + 11x − 10", "6x² − 11x + 10", "6x² + 11x + 10", "6x² − x − 10"], answer: "6x² + 11x − 10", explanation: "3x·2x + 3x·5 + (−2)·2x + (−2)·5 = 6x²+15x−4x−10 = 6x²+11x−10.", xp: 25 },
  { id: "QS-SHS1-117", category: "Linear Equations & Inequalities", mission_title: "The Mapping Machine", question: "A function is defined as f(x) = 2x² − 3. Find f(−2).", options: ["5", "1", "−1", "−5"], answer: "5", explanation: "f(−2) = 2(−2)² − 3 = 2×4 − 3 = 8 − 3 = 5.", xp: 25 },
  { id: "QS-SHS1-118", category: "Statistics & Averages", mission_title: "The Missing Frequency", question: "A data set has 5 values. The mean is 12. Four values are: 10, 15, 8, and 14. What is the fifth value?", options: ["11", "12", "13", "14"], answer: "13", explanation: "Sum = 5×12 = 60. Sum of known = 10+15+8+14 = 47. Fifth value = 60−47 = 13.", xp: 20 },
  { id: "QS-SHS1-119", category: "Perimeter, Area & Volume", mission_title: "The Path Around", question: "A circular garden has a circumference of 88 m. What is its radius? (Use π = 22/7)", options: ["12 m", "14 m", "16 m", "18 m"], answer: "14 m", explanation: "C = 2πr. 88 = 2×(22/7)×r. r = 88 × 7/(2×22) = 616/44 = 14 m.", xp: 25 },
  { id: "QS-SHS1-120", category: "Word Problems", mission_title: "The Tile Problem", question: "A room is 6 m by 5 m. Square tiles of side 50 cm are used. How many tiles are needed to cover the floor?", options: ["100", "120", "150", "200"], answer: "120", explanation: "Room area = 6×5 = 30 m². Tile area = 0.5×0.5 = 0.25 m². Tiles needed = 30/0.25 = 120.", xp: 25 },
  { id: "QS-SHS1-121", category: "Fractions & Percentages", mission_title: "The Property of Integers", question: "Which property is demonstrated by: 5 + (3 + 2) = (5 + 3) + 2?", options: ["Commutative", "Distributive", "Associative", "Identity"], answer: "Associative", explanation: "The Associative Property states that the grouping of numbers does not change the result: (a+b)+c = a+(b+c).", xp: 20 },
  { id: "QS-SHS1-122", category: "Geometry & Pythagoras", mission_title: "The Right Angle Proof", question: "A triangle has sides 9 cm, 40 cm, and 41 cm. Is it right-angled?", options: ["Yes, 9²+40² = 41²", "No, the sides do not satisfy Pythagoras", "Only if the longest side is the hypotenuse", "Cannot be determined without angles"], answer: "Yes, 9²+40² = 41²", explanation: "9²+40² = 81+1600 = 1681 = 41². The Pythagorean theorem is satisfied.", xp: 25 },
  { id: "QS-SHS1-123", category: "Probability", mission_title: "The Independent Events", question: "P(A) = 0.4 and P(B) = 0.5 where A and B are independent events. What is P(A and B)?", options: ["0.09", "0.20", "0.45", "0.90"], answer: "0.20", explanation: "For independent events: P(A and B) = P(A) × P(B) = 0.4 × 0.5 = 0.20.", xp: 20 },
  { id: "QS-SHS1-124", category: "Algebra & Expressions", mission_title: "The Common Factor", question: "Factorise: 12a²b − 8ab²", options: ["4ab(3a − 2b)", "4a(3ab − 2b²)", "8ab(a − b)", "4b(3a² − 2ab)"], answer: "4ab(3a − 2b)", explanation: "HCF of 12a²b and 8ab² is 4ab. 12a²b ÷ 4ab = 3a. 8ab² ÷ 4ab = 2b. So: 4ab(3a−2b).", xp: 25 },
  { id: "QS-SHS1-125", category: "Linear Equations & Inequalities", mission_title: "The Y-intercept Finder", question: "A straight line passes through (2, 5) with gradient 2. What is the y-intercept?", options: ["0", "1", "2", "3"], answer: "1", explanation: "y = mx + c. 5 = 2(2) + c. 5 = 4 + c. c = 1.", xp: 25 },
  { id: "QS-SHS1-126", category: "Statistics & Averages", mission_title: "The Line Graph", question: "A student's test scores over 5 weeks: 55, 62, 70, 68, 75. What is the percentage improvement from week 1 to week 5?", options: ["30%", "35%", "36.36%", "40%"], answer: "36.36%", explanation: "Improvement = 75−55 = 20. % improvement = (20/55)×100 ≈ 36.36%.", xp: 25 },
  { id: "QS-SHS1-127", category: "Perimeter, Area & Volume", mission_title: "The Irregular Shape", question: "An L-shaped room is made of two rectangles: one is 6m×4m and the other is 3m×2m. What is the total area?", options: ["26 m²", "28 m²", "30 m²", "32 m²"], answer: "30 m²", explanation: "Area = (6×4) + (3×2) = 24 + 6 = 30 m².", xp: 20 },
  { id: "QS-SHS1-128", category: "Vectors & Trigonometry", mission_title: "The Angle From Trig", question: "If sin θ = 0.5, what is the value of θ for 0° ≤ θ ≤ 90°?", options: ["30°", "45°", "60°", "90°"], answer: "30°", explanation: "sin 30° = 0.5. Therefore θ = 30°.", xp: 20 },
  { id: "QS-SHS1-129", category: "Word Problems", mission_title: "The School Trip Budget", question: "A school trip costs GH₵45 per student. 60 students are going. The school subsidises 20% of the total cost. How much do students collectively pay?", options: ["GH₵1,800", "GH₵2,000", "GH₵2,160", "GH₵2,250"], answer: "GH₵2,160", explanation: "Total cost = 45×60 = GH₵2,700. Subsidy = 20%×2700 = GH₵540. Students pay = 2700−540 = GH₵2,160.", xp: 25 },
  { id: "QS-SHS1-130", category: "Fractions & Percentages", mission_title: "The Distributor", question: "Simplify: 5/6 × 18/25", options: ["3/5", "5/9", "1/3", "4/5"], answer: "3/5", explanation: "5/6 × 18/25 = (5×18)/(6×25) = 90/150 = 3/5.", xp: 20 },
  { id: "QS-SHS1-131", category: "Algebra & Expressions", mission_title: "The Sequence Gap", question: "A number pattern is: 4, 7, 10, 13... What is the 20th term?", options: ["58", "61", "64", "67"], answer: "61", explanation: "First term a = 4, common difference d = 3. nth term = a+(n−1)d = 4+19×3 = 4+57 = 61.", xp: 25 },
  { id: "QS-SHS1-132", category: "Geometry & Pythagoras", mission_title: "The Exterior Polygon", question: "What is the size of each exterior angle of a regular octagon?", options: ["40°", "45°", "50°", "55°"], answer: "45°", explanation: "Sum of exterior angles of any polygon = 360°. Each exterior angle of regular octagon = 360°/8 = 45°.", xp: 20 },
  { id: "QS-SHS1-133", category: "Probability", mission_title: "The Unlikely Event", question: "A bag has 3 white and 7 black balls. What is the probability of NOT picking a black ball?", options: ["7/10", "3/10", "3/7", "1/3"], answer: "3/10", explanation: "P(black) = 7/10. P(not black) = 1−7/10 = 3/10.", xp: 15 },
  { id: "QS-SHS1-134", category: "Profit, Loss & Interest", mission_title: "The Marked Price", question: "An item is marked at GH₵250. A trader gives a 12% discount. What is the selling price?", options: ["GH₵210", "GH₵218", "GH₵220", "GH₵225"], answer: "GH₵220", explanation: "Discount = 12% × 250 = GH₵30. Selling price = 250−30 = GH₵220.", xp: 20 },
  { id: "QS-SHS1-135", category: "Perimeter, Area & Volume", mission_title: "The Prism Volume", question: "A rectangular prism has dimensions 10 cm × 4 cm × 3 cm. What is its volume?", options: ["100 cm³", "110 cm³", "120 cm³", "130 cm³"], answer: "120 cm³", explanation: "Volume = l × w × h = 10 × 4 × 3 = 120 cm³.", xp: 15 },
  { id: "QS-SHS1-136", category: "Word Problems", mission_title: "The Mixture Problem", question: "A drink is made by mixing juice and water in the ratio 3:5. If 24 litres of juice is used, how many litres of the drink are made in total?", options: ["48 litres", "56 litres", "60 litres", "64 litres"], answer: "64 litres", explanation: "Juice = 3 parts = 24 litres. Each part = 8 litres. Total = 8 parts = 8×8 = 64 litres.", xp: 25 },
  { id: "QS-SHS1-137", category: "Linear Equations & Inequalities", mission_title: "The Equation of a Line", question: "What is the equation of the line through (0, 4) and (3, 10)?", options: ["y = 2x + 4", "y = 3x + 4", "y = 2x + 3", "y = x + 4"], answer: "y = 2x + 4", explanation: "Gradient = (10−4)/(3−0) = 6/3 = 2. y-intercept = 4. Equation: y = 2x+4.", xp: 25 },
  { id: "QS-SHS1-138", category: "Statistics & Averages", mission_title: "The Survey Result", question: "In a survey, 45 out of 150 people preferred Brand A. What percentage preferred Brand A?", options: ["25%", "30%", "33%", "35%"], answer: "30%", explanation: "(45/150) × 100 = 30%.", xp: 15 },
  { id: "QS-SHS1-139", category: "Algebra & Expressions", mission_title: "The Closure Check", question: "Which operation is NOT closed under the set of integers? (i.e., always gives an integer result)", options: ["Addition", "Subtraction", "Multiplication", "Division"], answer: "Division", explanation: "4 ÷ 3 = 1.33... which is not an integer. Division is not closed under integers.", xp: 20 },
  { id: "QS-SHS1-140", category: "Geometry & Pythagoras", mission_title: "The Quadrilateral Angles", question: "A quadrilateral has three angles: 85°, 110°, and 95°. What is the fourth angle?", options: ["60°", "65°", "70°", "75°"], answer: "70°", explanation: "Sum of interior angles of a quadrilateral = 360°. Fourth = 360°−85°−110°−95° = 70°.", xp: 15 },
  { id: "QS-SHS1-141", category: "Probability", mission_title: "The Certain Event", question: "A bag has only red balls. If you pick one ball, what is the probability it is red?", options: ["0", "0.5", "1", "Cannot be determined"], answer: "1", explanation: "If all balls are red, the event is certain. Probability of a certain event = 1.", xp: 10 },
  { id: "QS-SHS1-142", category: "Fractions & Percentages", mission_title: "The Household Budget", question: "A family earns GH₵3,000 per month. They spend 35% on food, 20% on education, and 15% on utilities. How much is left?", options: ["GH₵800", "GH₵850", "GH₵900", "GH₵1,000"], answer: "GH₵900", explanation: "Total spent = 35+20+15 = 70%. Remaining = 30%. 30% × 3000 = GH₵900.", xp: 20 },
  { id: "QS-SHS1-143", category: "Vectors & Trigonometry", mission_title: "The Vector Magnitude", question: "A vector has components (3, 4). What is its magnitude?", options: ["3.5", "5", "7", "12"], answer: "5", explanation: "Magnitude = √(3² + 4²) = √(9+16) = √25 = 5.", xp: 20 },
  { id: "QS-SHS1-144", category: "Perimeter, Area & Volume", mission_title: "The Arc Length", question: "A sector has radius 9 cm and central angle 80°. What is the arc length? (Use π = 22/7)", options: ["11.43 cm", "12.57 cm", "14 cm", "15.43 cm"], answer: "12.57 cm", explanation: "Arc length = (θ/360°) × 2πr = (80/360) × 2 × (22/7) × 9 = (2/9) × (44×9/7) = (2/9) × (396/7) = 792/63 ≈ 12.57 cm.", xp: 30 },
  { id: "QS-SHS1-145", category: "Word Problems", mission_title: "The Test Average", question: "Ama needs an average of 75 over 4 tests. She scored 68, 79, and 72 in the first three. What score does she need in the fourth test?", options: ["78", "80", "81", "82"], answer: "81", explanation: "Required total = 4×75 = 300. Current total = 68+79+72 = 219. Fourth score = 300−219 = 81.", xp: 25 },
  { id: "QS-SHS1-146", category: "Algebra & Expressions", mission_title: "The Commutative Check", question: "Which equation demonstrates the COMMUTATIVE property of multiplication?", options: ["3 × (4 × 5) = (3 × 4) × 5", "3 × (4 + 5) = 3×4 + 3×5", "5 × 3 = 3 × 5", "3 × 1 = 3"], answer: "5 × 3 = 3 × 5", explanation: "The commutative property states: a × b = b × a. Order doesn't matter. 5×3 = 3×5 demonstrates this.", xp: 15 },
  { id: "QS-SHS1-147", category: "Linear Equations & Inequalities", mission_title: "The Function Value", question: "If g(x) = 3x − 7, for what value of x does g(x) = 8?", options: ["4", "5", "6", "7"], answer: "5", explanation: "3x − 7 = 8. 3x = 15. x = 5.", xp: 20 },
  { id: "QS-SHS1-148", category: "Statistics & Averages", mission_title: "The Weighted Average", question: "A student scored 60 in a test worth 40% and 80 in a test worth 60%. What is their weighted average?", options: ["70", "72", "74", "76"], answer: "72", explanation: "Weighted avg = (60×0.4) + (80×0.6) = 24 + 48 = 72.", xp: 30 },
  { id: "QS-SHS1-149", category: "Geometry & Pythagoras", mission_title: "The Perpendicular Lines", question: "A line has a gradient of 3. What is the gradient of a line perpendicular to it?", options: ["3", "−3", "−1/3", "1/3"], answer: "−1/3", explanation: "For perpendicular lines: m₁ × m₂ = −1. So m₂ = −1/3.", xp: 25 },
  { id: "QS-SHS1-150", category: "Probability", mission_title: "The Event Union", question: "P(A) = 0.3, P(B) = 0.4, and A and B are mutually exclusive. What is P(A or B)?", options: ["0.12", "0.58", "0.70", "0.7"], answer: "0.7", explanation: "For mutually exclusive events: P(A or B) = P(A) + P(B) = 0.3 + 0.4 = 0.7.", xp: 20 },
  { id: "QS-SHS1-151", category: "Fractions & Percentages", mission_title: "The Shop Profit", question: "A trader marks up goods by 40% and then gives a 10% discount. What is the actual percentage profit?", options: ["26%", "30%", "32%", "34%"], answer: "26%", explanation: "Let cost = 100. Marked price = 140. Selling price = 140×0.9 = 126. Profit = 26%.", xp: 30 },
  { id: "QS-SHS1-152", category: "Algebra & Expressions", mission_title: "The Inverse Property", question: "What is the multiplicative inverse (reciprocal) of ⅔?", options: ["2/3", "3/2", "−2/3", "−3/2"], answer: "3/2", explanation: "The multiplicative inverse of a/b is b/a. Inverse of 2/3 = 3/2.", xp: 15 },
  { id: "QS-SHS1-153", category: "Word Problems", mission_title: "The Population Growth", question: "A town has a population of 20,000. It grows at 5% per year. What is the population after 2 years?", options: ["21,000", "22,000", "22,050", "22,500"], answer: "22,050", explanation: "Year 1: 20000×1.05 = 21000. Year 2: 21000×1.05 = 22050.", xp: 25 },
  { id: "QS-SHS1-154", category: "Geometry & Pythagoras", mission_title: "The Triangle Sides", question: "An equilateral triangle has a perimeter of 36 cm. What is the length of one side?", options: ["9 cm", "10 cm", "12 cm", "18 cm"], answer: "12 cm", explanation: "All three sides of an equilateral triangle are equal. Side = 36/3 = 12 cm.", xp: 15 },
  { id: "QS-SHS1-155", category: "Perimeter, Area & Volume", mission_title: "The Surface Area", question: "A cube has a side length of 4 cm. What is its total surface area?", options: ["64 cm²", "80 cm²", "96 cm²", "112 cm²"], answer: "96 cm²", explanation: "A cube has 6 faces. Each face area = 4² = 16 cm². Total = 6×16 = 96 cm².", xp: 20 },
  { id: "QS-SHS1-156", category: "Statistics & Averages", mission_title: "The Outlier Effect", question: "A data set is: 4, 5, 6, 5, 4, 100. Which measure of average is MOST affected by the value 100?", options: ["Mode", "Median", "Mean", "Range"], answer: "Mean", explanation: "The mean uses all values, so an extreme outlier (100) pulls it significantly. The median and mode are not affected as much.", xp: 25 },
  { id: "QS-SHS1-157", category: "Probability", mission_title: "The Spinner Game", question: "A spinner has 8 equal sections numbered 1 to 8. What is the probability of landing on an even number?", options: ["3/8", "1/2", "5/8", "3/4"], answer: "1/2", explanation: "Even numbers 1-8: 2, 4, 6, 8 — that is 4 numbers. P = 4/8 = 1/2.", xp: 15 },
  { id: "QS-SHS1-158", category: "Linear Equations & Inequalities", mission_title: "The Bracket Equation", question: "Solve: 2(3x − 4) = 3(x + 2)", options: ["x = 14/3", "x = 4", "x = 5", "x = 14"], answer: "x = 14/3", explanation: "6x − 8 = 3x + 6. 3x = 14. x = 14/3.", xp: 25 },
  { id: "QS-SHS1-159", category: "Vectors & Trigonometry", mission_title: "The Tower Height", question: "From a point 20 m from the base of a tower, the angle of elevation to the top is 45°. How tall is the tower?", options: ["10 m", "15 m", "20 m", "25 m"], answer: "20 m", explanation: "tan 45° = height/base. 1 = h/20. h = 20 m.", xp: 25 },
  { id: "QS-SHS1-160", category: "Word Problems", mission_title: "The Fuel Cost", question: "A car uses 1 litre of fuel for every 12 km. Fuel costs GH₵12 per litre. How much does it cost to drive 180 km?", options: ["GH₵160", "GH₵170", "GH₵180", "GH₵200"], answer: "GH₵180", explanation: "Fuel needed = 180/12 = 15 litres. Cost = 15×12 = GH₵180.", xp: 20 },
  { id: "QS-SHS1-161", category: "Algebra & Expressions", mission_title: "The Identity Property", question: "What is the additive identity element for real numbers?", options: ["1", "−1", "0", "∞"], answer: "0", explanation: "The additive identity is 0, because a + 0 = a for any real number a.", xp: 15 },
  { id: "QS-SHS1-162", category: "Perimeter, Area & Volume", mission_title: "The Swimming Pool", question: "A rectangular swimming pool is 25 m long, 10 m wide, and 2 m deep. What is its volume?", options: ["400 m³", "450 m³", "500 m³", "550 m³"], answer: "500 m³", explanation: "Volume = 25 × 10 × 2 = 500 m³.", xp: 15 },
  { id: "QS-SHS1-163", category: "Statistics & Averages", mission_title: "The Class Performance", question: "A class of 30 students takes a test. The mean mark is 65. Another class of 20 students has a mean of 70. What is the combined mean of all 50 students?", options: ["66", "67", "67.5", "68"], answer: "67", explanation: "Total marks = (30×65)+(20×70) = 1950+1400 = 3350. Combined mean = 3350/50 = 67.", xp: 30 },
  { id: "QS-SHS1-164", category: "Geometry & Pythagoras", mission_title: "The Vertically Opposite", question: "Two lines intersect. One angle formed is 42°. What is the vertically opposite angle?", options: ["48°", "138°", "42°", "90°"], answer: "42°", explanation: "Vertically opposite angles are equal. The angle directly opposite is also 42°.", xp: 15 },
  { id: "QS-SHS1-165", category: "Probability", mission_title: "The Impossible Event", question: "What is the probability of rolling a 7 on a standard six-sided die?", options: ["1/7", "1/6", "7/6", "0"], answer: "0", explanation: "A standard die has faces 1 to 6. Rolling a 7 is impossible. P(impossible event) = 0.", xp: 10 },
  { id: "QS-SHS1-166", category: "Fractions & Percentages", mission_title: "The Original Price", question: "After a 25% decrease, a laptop costs GH₵1,800. What was the original price?", options: ["GH₵2,200", "GH₵2,300", "GH₵2,400", "GH₵2,500"], answer: "GH₵2,400", explanation: "Original × 0.75 = 1800. Original = 1800/0.75 = GH₵2,400.", xp: 25 },
  { id: "QS-SHS1-167", category: "Vectors & Trigonometry", mission_title: "The Sine of 90", question: "What is sin 90°?", options: ["0", "1/2", "√3/2", "1"], answer: "1", explanation: "sin 90° = 1. This is a fundamental trigonometric value.", xp: 15 },
  { id: "QS-SHS1-168", category: "Word Problems", mission_title: "The Number Puzzle", question: "A number is multiplied by 5 and then 12 is subtracted. The result is 33. What is the number?", options: ["7", "8", "9", "10"], answer: "9", explanation: "Let the number = n. 5n − 12 = 33. 5n = 45. n = 9.", xp: 15 },
  { id: "QS-SHS1-169", category: "Algebra & Expressions", mission_title: "The Distributive Law", question: "Which equation demonstrates the DISTRIBUTIVE property?", options: ["4(3+5) = 4×3 + 4×5", "3+4 = 4+3", "2×(3×4) = (2×3)×4", "5+0 = 5"], answer: "4(3+5) = 4×3 + 4×5", explanation: "The distributive property: a(b+c) = ab + ac. Here 4(3+5) = 4×3 + 4×5 = 12+20 = 32.", xp: 15 },
  { id: "QS-SHS1-170", category: "Perimeter, Area & Volume", mission_title: "The Perimeter of a Sector", question: "A sector has radius 7 cm and angle 90°. What is its perimeter? (Use π = 22/7)", options: ["24 cm", "25 cm", "25.5 cm", "26 cm"], answer: "25 cm", explanation: "Arc length = (90/360)×2×(22/7)×7 = (1/4)×44 = 11 cm. Perimeter = arc + 2 radii = 11+7+7 = 25 cm.", xp: 30 },
  { id: "QS-SHS1-171", category: "Statistics & Averages", mission_title: "The Frequency Distribution", question: "The mode of a set of numbers is 7, the median is 8, and the mean is 9. A new value of 7 is added. What happens to the mode?", options: ["It increases", "It stays the same", "It decreases", "It cannot be determined"], answer: "It stays the same", explanation: "Adding another 7 reinforces 7 as the most frequent value. The mode remains 7.", xp: 20 },
  { id: "QS-SHS1-172", category: "Probability", mission_title: "The Sum of Seven", question: "Two dice are thrown. What is the probability that the sum of the faces is 7?", options: ["5/36", "6/36", "7/36", "8/36"], answer: "6/36", explanation: "Combinations that sum to 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 combinations. P = 6/36 = 1/6.", xp: 25 },
  { id: "QS-SHS1-173", category: "Profit, Loss & Interest", mission_title: "The Bank Interest", question: "A bank pays 15% simple interest per year. How long will it take for GH₵1,000 to earn GH₵450 in interest?", options: ["2 years", "3 years", "4 years", "5 years"], answer: "3 years", explanation: "I = PRT/100. 450 = (1000×15×T)/100. 450 = 150T. T = 3 years.", xp: 25 },
  { id: "QS-SHS1-174", category: "Vectors & Trigonometry", mission_title: "The Opposite Vector", question: "A vector AB has components (5, −3). What are the components of the vector BA?", options: ["(5, 3)", "(−5, 3)", "(3, −5)", "(−3, 5)"], answer: "(−5, 3)", explanation: "The reverse vector BA = −AB = (−5, 3). Each component is negated.", xp: 20 },
  { id: "QS-SHS1-175", category: "Word Problems", mission_title: "The Voter Count", question: "In an election, candidate A got 45% of the votes and candidate B got 35%. The remaining 4,000 votes went to candidate C. How many total votes were cast?", options: ["18,000", "20,000", "22,000", "25,000"], answer: "20,000", explanation: "C got 100−45−35 = 20% of votes. 20% = 4,000. Total = 4000/0.2 = 20,000.", xp: 25 },
  { id: "QS-SHS1-176", category: "Algebra & Expressions", mission_title: "The Fraction Operation", question: "Simplify: (3/(x+1)) + (2/(x−1))", options: ["(5x+1)/((x+1)(x−1))", "(5x−1)/((x+1)(x−1))", "5/(x²−1)", "(3x−3+2x+2)/((x+1)(x−1))"], answer: "(5x−1)/((x+1)(x−1))", explanation: "LCD = (x+1)(x−1). Numerator = 3(x−1)+2(x+1) = 3x−3+2x+2 = 5x−1.", xp: 30 },
  { id: "QS-SHS1-177", category: "Geometry & Pythagoras", mission_title: "The Bearing Return", question: "A person walks on a bearing of 060°. What bearing must they take to return directly to their starting point?", options: ["120°", "180°", "240°", "300°"], answer: "240°", explanation: "The back-bearing = original bearing + 180°. 060° + 180° = 240°.", xp: 25 },
  { id: "QS-SHS1-178", category: "Statistics & Averages", mission_title: "The Class Comparison", question: "Two sets of data have the same mean of 50. Set A has a range of 10, Set B has a range of 40. What does this tell us?", options: ["Set B is better", "Set A data is more spread out", "Set B data is more spread out than Set A", "They are identical"], answer: "Set B data is more spread out than Set A", explanation: "Range measures spread. A larger range means more spread. Set B (range 40) is more spread out than Set A (range 10).", xp: 20 },
  { id: "QS-SHS1-179", category: "Probability", mission_title: "The At Least One", question: "A fair coin is tossed 3 times. What is the probability of getting AT LEAST one Head?", options: ["1/8", "3/8", "6/8", "7/8"], answer: "7/8", explanation: "P(at least one H) = 1 − P(no Heads) = 1 − (1/2)³ = 1 − 1/8 = 7/8.", xp: 30 },
  { id: "QS-SHS1-180", category: "Fractions & Percentages", mission_title: "The Percentage Puzzle", question: "40% of a number is 60. What is 75% of the same number?", options: ["100", "105", "110", "112.5"], answer: "112.5", explanation: "40% = 60, so 100% = 150. 75% of 150 = 0.75×150 = 112.5.", xp: 25 },
  { id: "QS-SHS1-181", category: "Linear Equations & Inequalities", mission_title: "The Compound Inequality", question: "Find the integers that satisfy: −5 < 3x − 2 ≤ 10", options: ["−1, 0, 1, 2, 3, 4", "0, 1, 2, 3, 4", "−1, 0, 1, 2, 3", "1, 2, 3, 4"], answer: "0, 1, 2, 3, 4", explanation: "Add 2: −3 < 3x ≤ 12. Divide by 3: −1 < x ≤ 4. Integers: x = 0,1,2,3,4.", xp: 30 },
  { id: "QS-SHS1-182", category: "Perimeter, Area & Volume", mission_title: "The Hemisphere", question: "A hemisphere has a radius of 6 cm. What is its curved surface area? (Use π = 3.14)", options: ["188.4 cm²", "226.08 cm²", "113.04 cm²", "150 cm²"], answer: "226.08 cm²", explanation: "Curved surface area of hemisphere = 2πr² = 2 × 3.14 × 36 = 226.08 cm².", xp: 25 },
  { id: "QS-SHS1-183", category: "Word Problems", mission_title: "The Building Plan", question: "A map uses a scale of 1:500. On the map, a building is 4 cm long. What is the actual length of the building?", options: ["20 m", "200 m", "2000 m", "2 m"], answer: "20 m", explanation: "Actual = map × scale = 4 cm × 500 = 2000 cm = 20 m.", xp: 20 },
  { id: "QS-SHS1-184", category: "Algebra & Expressions", mission_title: "The Sequence Rule", question: "The sum of the first n terms of a sequence is Sn = n² + 2n. What is the 4th term of the sequence?", options: ["7", "9", "10", "11"], answer: "9", explanation: "S₄ = 16+8 = 24. S₃ = 9+6 = 15. 4th term = S₄ − S₃ = 24−15 = 9.", xp: 35 },
  { id: "QS-SHS1-185", category: "Vectors & Trigonometry", mission_title: "The Resultant Vector", question: "Two vectors: a = (3, 4) and b = (−1, 2). What is a + b?", options: ["(2, 6)", "(4, 2)", "(2, 2)", "(3, 6)"], answer: "(2, 6)", explanation: "a + b = (3+(−1), 4+2) = (2, 6).", xp: 20 },
  { id: "QS-SHS1-186", category: "Statistics & Averages", mission_title: "The Best Average", question: "A dataset is: 3, 3, 3, 4, 100. A teacher wants to represent the 'typical' value. Which measure is MOST appropriate?", options: ["Mean", "Median", "Mode", "Range"], answer: "Mode", explanation: "The mode (3) appears most frequently — most values are 3. The mean (≈22.6) is distorted by the outlier 100.", xp: 25 },
  { id: "QS-SHS1-187", category: "Geometry & Pythagoras", mission_title: "The Obtuse Triangle", question: "A triangle has angles 35° and 120°. What is the third angle? What type of triangle is it?", options: ["25°, acute", "25°, obtuse", "30°, right-angled", "25°, right-angled"], answer: "25°, obtuse", explanation: "Third angle = 180°−35°−120° = 25°. Since one angle (120°) > 90°, it is obtuse.", xp: 20 },
  { id: "QS-SHS1-188", category: "Probability", mission_title: "The Conditional Check", question: "A class has 12 boys and 8 girls. A student is chosen at random. Given the student is a girl, what is the probability she likes Science if 5 of the 8 girls like Science?", options: ["1/4", "1/2", "5/8", "5/20"], answer: "5/8", explanation: "Given it's a girl, we focus only on the 8 girls. 5 like Science. P = 5/8.", xp: 25 },
  { id: "QS-SHS1-189", category: "Profit, Loss & Interest", mission_title: "The Hire Purchase", question: "A TV costs GH₵1,200 cash. On hire purchase, you pay a deposit of GH₵300 plus 12 monthly payments of GH₵90. How much MORE do you pay on hire purchase than cash?", options: ["GH₵120", "GH₵160", "GH₵180", "GH₵200"], answer: "GH₵180", explanation: "HP total = 300 + (12×90) = 300+1080 = GH₵1,380. Extra = 1380−1200 = GH₵180.", xp: 25 },
  { id: "QS-SHS1-190", category: "Word Problems", mission_title: "The Exam Cutoff", question: "To pass an exam, a student needs at least 50%. Kofi scored 36 out of 80. Did he pass? By how many marks did he pass or fail?", options: ["Passed by 4 marks", "Failed by 4 marks", "Passed by 2 marks", "Failed by 2 marks"], answer: "Failed by 4 marks", explanation: "Pass mark = 50% of 80 = 40. Kofi scored 36. He failed by 40−36 = 4 marks.", xp: 20 },
  { id: "QS-SHS1-191", category: "Algebra & Expressions", mission_title: "The Perfect Square Expansion", question: "Expand: (2x − 3)²", options: ["4x² + 9", "4x² − 12x + 9", "4x² − 6x + 9", "4x² + 12x + 9"], answer: "4x² − 12x + 9", explanation: "(2x−3)² = (2x)² − 2(2x)(3) + 3² = 4x²−12x+9.", xp: 25 },
  { id: "QS-SHS1-192", category: "Perimeter, Area & Volume", mission_title: "The Compound Volume", question: "A shape is made of a cube (side 4 cm) with a smaller cube (side 2 cm) removed from its corner. What is the remaining volume?", options: ["56 cm³", "60 cm³", "64 cm³", "72 cm³"], answer: "56 cm³", explanation: "Large cube = 4³ = 64 cm³. Small cube = 2³ = 8 cm³. Remaining = 64−8 = 56 cm³.", xp: 25 },
  { id: "QS-SHS1-193", category: "Statistics & Averages", mission_title: "The Data Spread", question: "Data set A has mean 20 and range 4. Data set B has mean 20 and range 30. Which data set is more consistent?", options: ["Data set A — smaller range means less spread", "Data set B — larger range means more data", "They are equally consistent", "Cannot be determined"], answer: "Data set A — smaller range means less spread", explanation: "A smaller range indicates data values are closer together — meaning more consistency. Data set A is more consistent.", xp: 20 },
  { id: "QS-SHS1-194", category: "Vectors & Trigonometry", mission_title: "The Height Finder", question: "A tree casts a shadow of 15 m. The angle of elevation of the sun is 30°. How tall is the tree?", options: ["5√3 m", "15√3 m", "5 m", "15/√3 m"], answer: "5√3 m", explanation: "tan 30° = height/15. height = 15 × tan 30° = 15 × (1/√3) = 15/√3 = 5√3 m.", xp: 30 },
  { id: "QS-SHS1-195", category: "Probability", mission_title: "The Final Draw", question: "A lottery has 100 tickets numbered 1-100. Tickets numbered as multiples of 5 win a prize. What is the probability of winning?", options: ["1/10", "1/5", "1/4", "1/20"], answer: "1/5", explanation: "Multiples of 5 from 1-100: 5,10,15,...,100 = 20 tickets. P = 20/100 = 1/5.", xp: 20 },
  { id: "QS-SHS1-196", category: "Word Problems", mission_title: "The Road Trip", question: "A journey of 360 km is partly by train at 90 km/h and the rest by bus at 60 km/h. The total journey time is 5 hours. How far is the train portion?", options: ["160 km", "180 km", "200 km", "220 km"], answer: "180 km", explanation: "Let train distance = d. d/90 + (360−d)/60 = 5. Multiply by 180: 2d + 3(360−d) = 900. 2d+1080−3d = 900. d = 180 km.", xp: 35 },
  { id: "QS-SHS1-197", category: "Linear Equations & Inequalities", mission_title: "The Simultaneous Final", question: "Solve: 3x − 2y = 8 and x + y = 6. What is y?", options: ["1", "2", "3", "4"], answer: "2", explanation: "From second: x = 6−y. Substitute: 3(6−y)−2y = 8. 18−3y−2y = 8. 5y = 10. y = 2.", xp: 25 },
  { id: "QS-SHS1-198", category: "Algebra & Expressions", mission_title: "The Sum Formula", question: "The sum of the first n terms of an arithmetic sequence is Sn = n/2 × (2a + (n−1)d). For a=3, d=4, n=10, find S₁₀.", options: ["190", "200", "210", "220"], answer: "210", explanation: "S₁₀ = 10/2 × (2×3 + 9×4) = 5 × (6+36) = 5 × 42 = 210.", xp: 35 },
  { id: "QS-SHS1-199", category: "Geometry & Pythagoras", mission_title: "The Altitude of a Triangle", question: "In a right-angled triangle with legs 5 cm and 12 cm, what is the area?", options: ["25 cm²", "30 cm²", "60 cm²", "65 cm²"], answer: "30 cm²", explanation: "Area = ½ × base × height = ½ × 5 × 12 = 30 cm².", xp: 15 },
  { id: "QS-SHS1-200", category: "Word Problems", mission_title: "The ATLAS Final Sprint", question: "A student scores 70% on a test worth 40 marks. She then scores 85% on a second test worth 60 marks. What is her total score out of 100?", options: ["76", "78", "79", "80"], answer: "79", explanation: "Test 1: 70% of 40 = 28. Test 2: 85% of 60 = 51. Total = 28+51 = 79 out of 100.", xp: 25 },
];

// ── Helper: find which option key matches the answer text ─────────────────
function findAnswerKey(raw: RawQuantQuestion): string {
  const keys = ['A', 'B', 'C', 'D'];
  for (let i = 0; i < raw.options.length; i++) {
    if (raw.options[i] === raw.answer) return keys[i];
  }
  return 'A'; // fallback (should never happen)
}

// ── Build the full typed question bank ─────────────────────────────────────
export const QUANT_ARENA_QUESTIONS: Question[] = RAW.map((raw, idx) => {
  const correctKey = findAnswerKey(raw);
  return {
    id: idx + 1,
    domain: 'Math',
    question: raw.question,
    options: { A: raw.options[0], B: raw.options[1], C: raw.options[2], D: raw.options[3] },
    answer_hash: hash(correctKey),
    _category: raw.category,
    _mission: raw.mission_title,
    _explanation: raw.explanation,
    _xp: raw.xp,
  };
});

// ── Get a random subset of questions (shuffled) ────────────────────────────
export function getRandomQuantQuestions(count: number): Question[] {
  const shuffled = [...QUANT_ARENA_QUESTIONS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

// ── Get questions by category ──────────────────────────────────────────────
export function getQuantQuestionsByCategory(category: string): Question[] {
  return QUANT_ARENA_QUESTIONS.filter((q: any) => q._category === category);
}

// ── Get question IDs already used (for dedup) ──────────────────────────────
export const QUANT_QUESTION_IDS = new Set(QUANT_ARENA_QUESTIONS.map((q) => q.id));
